package bo.com.ganadero.alertas.application;
import bo.com.ganadero.alertas.domain.*;import bo.com.ganadero.animales.domain.AnimalRepository;import bo.com.ganadero.shared.error.*;import bo.com.ganadero.shared.security.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class AlertaQueryService{
 private final AlertaRepository repo;private final AnimalRepository animales;private final UserContext context;
 public AlertaQueryService(AlertaRepository r,AnimalRepository a,UserContext c){repo=r;animales=a;context=c;}
 @Transactional(readOnly=true)public List<Alerta> listar(EstadoAlerta estado,TipoAlerta tipo,UUID animal){CurrentUser u=context.requirePermission("ALERTA_VER");return visibles(u,repo.listar(u.empresaId(),estado,tipo,animal));}
 @Transactional(readOnly=true)public Alerta obtener(UUID id){CurrentUser u=context.requirePermission("ALERTA_VER");Alerta a=repo.buscar(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.ALERTA_NOT_FOUND));if(!visible(u,a))throw new BusinessException(ErrorCode.ALERTA_NOT_FOUND);return a;}
 @Transactional(readOnly=true)public ConteoAlertas noLeidas(){CurrentUser u=context.requirePermission("ALERTA_VER");List<Alerta> a=visibles(u,repo.listar(u.empresaId(),null,null,null)).stream().filter(x->x.estado()==EstadoAlerta.PENDIENTE||x.estado()==EstadoAlerta.ENVIADA).toList();return new ConteoAlertas(a.size(),contar(a,SeveridadAlerta.URGENTE),contar(a,SeveridadAlerta.CRITICA));}
 @Transactional(readOnly=true)public ResumenAlertas resumen(){CurrentUser u=context.requirePermission("ALERTA_VER");List<Alerta>a=visibles(u,repo.listar(u.empresaId(),null,null,null));LocalDate hoy=LocalDate.now(ZoneId.of("America/La_Paz"));return new ResumenAlertas(a.stream().filter(x->x.estado()==EstadoAlerta.PENDIENTE||x.estado()==EstadoAlerta.ENVIADA).count(),a.stream().filter(x->x.severidad()==SeveridadAlerta.URGENTE||x.severidad()==SeveridadAlerta.CRITICA).filter(x->x.estado()!=EstadoAlerta.RESUELTA&&x.estado()!=EstadoAlerta.CANCELADA).count(),a.stream().filter(x->x.fechaProgramada().atZone(ZoneId.of("America/La_Paz")).toLocalDate().equals(hoy)).count(),a.stream().filter(x->x.estado()==EstadoAlerta.RESUELTA).count());}
 @Transactional public Alerta atender(UUID id){CurrentUser u=context.requirePermission("ALERTA_ATENDER");obtener(id);return repo.atender(id,u.empresaId(),u.userId());}@Transactional public Alerta resolver(UUID id){CurrentUser u=context.requirePermission("ALERTA_RESOLVER");obtener(id);return repo.resolver(id,u.empresaId(),u.userId());}@Transactional public int procesarVencidas(int limite){context.requirePermission("ALERTA_RESOLVER");if(limite<1||limite>1000)throw new BusinessException(ErrorCode.VALIDATION_ERROR);return repo.activarVencidas(Instant.now(),limite);}
 private long contar(List<Alerta>a,SeveridadAlerta s){return a.stream().filter(x->x.severidad()==s).count();}private List<Alerta>visibles(CurrentUser u,List<Alerta>a){return a.stream().filter(x->visible(u,x)).toList();}private boolean visible(CurrentUser u,Alerta a){if(a.animalId()==null||u.accesoTodasPropiedades())return true;return animales.findById(a.animalId(),u.empresaId()).map(x->context.hasPropertyAccess(u,x.propiedadActualId())).orElse(false);}
 public record ConteoAlertas(long total,long urgentes,long criticas){}public record ResumenAlertas(long pendientes,long urgentes,long hoy,long resueltas){}
}
