package bo.com.ganadero.alertas.application;

public enum TipoAlerta {
    PROXIMO_PARTO,
    DIAGNOSTICO_GESTACION_PENDIENTE,
    DESTETE_PROXIMO,
    VACUNACION_PROXIMA,
    TRATAMIENTO_PENDIENTE,
    TRATAMIENTO_ATRASADO,
    RETIRO_SANITARIO,
    CUARENTENA_POR_FINALIZAR,
    CASO_CLINICO_CRITICO
}
