package bo.com.ganadero.shared.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "La solicitud contiene datos inválidos."),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED, "La solicitud requiere autenticación."),
    EMPRESA_NOT_FOUND(HttpStatus.NOT_FOUND, "La empresa no existe."),
    MEMBERSHIP_NOT_FOUND(HttpStatus.FORBIDDEN, "El usuario no posee una membresía activa."),
    USER_NOT_AUTHORIZED(HttpStatus.FORBIDDEN, "El usuario no tiene permiso para realizar esta operación."),
    TOO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS, "Se superó el límite de solicitudes. Intenta nuevamente en un minuto."),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "El usuario no existe en la empresa."),
    USER_ALREADY_MEMBER(HttpStatus.CONFLICT, "El usuario ya pertenece a la empresa."),
    BOOTSTRAP_DISABLED(HttpStatus.NOT_FOUND, "El recurso no existe."),
    BOOTSTRAP_TOKEN_INVALID(HttpStatus.FORBIDDEN, "No autorizado."),
    BOOTSTRAP_ALREADY_COMPLETED(HttpStatus.CONFLICT, "La empresa inicial ya fue creada."),
    IDEMPOTENCY_KEY_REQUIRED(HttpStatus.BAD_REQUEST, "Idempotency-Key es obligatorio."),
    IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, "La clave de idempotencia ya fue usada con otra solicitud."),
    SUPABASE_AUTH_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "El servicio de identidad no está disponible."),
    STORAGE_FILE_INVALID(HttpStatus.UNPROCESSABLE_CONTENT, "El archivo no cumple la política de seguridad."),
    SYSTEM_STATUS_DISABLED(HttpStatus.NOT_FOUND, "El recurso no existe."),
    ROLE_NOT_FOUND(HttpStatus.NOT_FOUND, "El rol no existe o no está disponible para la empresa."),
    ROLE_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Ya existe un rol con ese código."),
    LAST_ACTIVE_OWNER(HttpStatus.UNPROCESSABLE_CONTENT, "No se puede bloquear o degradar al último propietario activo."),
    CANNOT_SELF_BLOCK(HttpStatus.UNPROCESSABLE_CONTENT, "No puedes bloquear tu propia cuenta."),
    CANNOT_REMOVE_OWN_OWNER_ROLE(HttpStatus.UNPROCESSABLE_CONTENT, "No puedes quitarte tu propio rol de propietario."),
    SYSTEM_ROLE_IMMUTABLE(HttpStatus.UNPROCESSABLE_CONTENT, "Los datos estructurales de un rol del sistema no pueden modificarse."),
    PROPERTY_NOT_FOUND(HttpStatus.NOT_FOUND, "La propiedad no existe."),
    PROPERTY_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Ya existe una propiedad con ese código."),
    PROPERTY_HAS_ACTIVE_ANIMALS(HttpStatus.UNPROCESSABLE_CONTENT, "La propiedad contiene animales activos y no puede desactivarse."),
    PROPERTY_ACCESS_DENIED(HttpStatus.FORBIDDEN, "El usuario no tiene acceso a la propiedad."),
    SECTOR_NOT_FOUND(HttpStatus.NOT_FOUND, "El sector no existe."),
    SECTOR_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Ya existe un sector con ese código en la propiedad."),
    GRASS_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "El tipo de pasto no existe."),
    PADDOCK_NOT_FOUND(HttpStatus.NOT_FOUND, "El potrero no existe."),
    PADDOCK_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Ya existe un potrero con ese código en la propiedad."),
    PADDOCK_HAS_ACTIVE_ANIMALS(HttpStatus.UNPROCESSABLE_CONTENT, "El potrero contiene animales activos y no puede desactivarse."),
    ANIMAL_NOT_FOUND(HttpStatus.NOT_FOUND, "El animal no existe."),
    ANIMAL_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Ya existe un animal con ese código."),
    BREED_NOT_FOUND(HttpStatus.NOT_FOUND, "La raza no existe."),
    ANIMAL_CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "La categoría del animal no existe."),
    ANIMAL_CATEGORY_SEX_MISMATCH(HttpStatus.UNPROCESSABLE_CONTENT, "La categoría no corresponde al sexo del animal."),
    INVALID_ANIMAL_LOCATION(HttpStatus.UNPROCESSABLE_CONTENT, "El potrero no pertenece a la propiedad indicada."),
    INVALID_ANIMAL_STATE_TRANSITION(HttpStatus.UNPROCESSABLE_CONTENT, "El cambio de estado del animal no está permitido."),
    IDENTIFIER_ALREADY_EXISTS(HttpStatus.CONFLICT, "El identificador ya se encuentra registrado."),
    IDENTIFIER_NOT_FOUND(HttpStatus.NOT_FOUND, "El identificador del animal no existe."),
    IDENTIFIER_ALREADY_RETIRED(HttpStatus.CONFLICT, "El identificador ya fue retirado y no puede modificarse."),
    IDENTIFIER_INVALID_VALUE(HttpStatus.UNPROCESSABLE_CONTENT, "El valor del identificador no es válido para el tipo indicado."),
    IDENTIFIER_VERSION_CONFLICT(HttpStatus.CONFLICT, "El identificador fue modificado por otro usuario."),
    IDENTIFIER_QR_MANUAL_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_CONTENT, "El identificador QR debe generarse desde el servidor."),
    INVALID_QR(HttpStatus.BAD_REQUEST, "El código QR no es válido o fue manipulado."),
    UNSUPPORTED_QR_VERSION(HttpStatus.UNPROCESSABLE_CONTENT, "La versión del código QR no es compatible con esta aplicación."),
    QR_NOT_FOUND(HttpStatus.NOT_FOUND, "El código QR no corresponde a un animal accesible."),
    IDENTIFIER_QR_IMMUTABLE(HttpStatus.UNPROCESSABLE_CONTENT, "El identificador QR no puede editarse; usa reemplazo de QR."),
    PARENTESCO_NOT_FOUND(HttpStatus.NOT_FOUND, "El parentesco no existe."),
    PARENTESCO_ALREADY_EXISTS(HttpStatus.CONFLICT, "El animal ya posee un progenitor de ese tipo."),
    PARENTESCO_CYCLE(HttpStatus.UNPROCESSABLE_CONTENT, "La relación de parentesco genera un ciclo."),
    ANIMAL_NOT_ACTIVE(HttpStatus.UNPROCESSABLE_CONTENT, "El animal no se encuentra activo."),
    LOT_NOT_FOUND(HttpStatus.NOT_FOUND, "El lote no existe."),
    LOT_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Ya existe un lote con ese código."),
    LOT_ALREADY_CLOSED(HttpStatus.UNPROCESSABLE_CONTENT, "El lote ya está cerrado."),
    LOT_CLOSED(HttpStatus.CONFLICT, "El lote está cerrado y no admite más animales."),
    LOT_VERSION_CONFLICT(HttpStatus.CONFLICT, "El lote fue modificado por otro usuario."),
    LOT_HAS_ACTIVE_ANIMALS(HttpStatus.CONFLICT, "El lote tiene animales activos y no puede cerrarse."),
    ANIMAL_ALREADY_IN_LOT(HttpStatus.CONFLICT, "El animal ya pertenece a este lote."),
    ANIMAL_NOT_IN_LOT(HttpStatus.CONFLICT, "El animal no pertenece al lote indicado."),
    ANIMAL_STATUS_NOT_ALLOWED(HttpStatus.CONFLICT, "El estado del animal no permite su ingreso a un lote."),
    ANIMAL_VERSION_CONFLICT(HttpStatus.CONFLICT, "El animal fue modificado por otro usuario."),
    ANIMAL_COMPANY_MISMATCH(HttpStatus.CONFLICT, "El animal pertenece a otra empresa."),
    ANIMAL_PROPERTY_MISMATCH(HttpStatus.CONFLICT, "El animal no pertenece a la propiedad del lote."),
    DUPLICATE_ANIMAL_IN_REQUEST(HttpStatus.BAD_REQUEST, "La solicitud contiene animales duplicados."),
    DUPLICATE_ANIMAL_IN_MOVEMENT(HttpStatus.BAD_REQUEST, "El movimiento contiene animales duplicados."),
    INVALID_MEMBERSHIP_DATE(HttpStatus.BAD_REQUEST, "Las fechas de la membresía del lote no son válidas."),
    MEMBERSHIP_VERSION_CONFLICT(HttpStatus.CONFLICT, "La membresía del lote fue modificada por otro usuario."),
    MOVEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "El movimiento no existe."),
    MOVEMENT_ALREADY_ANNULLED(HttpStatus.CONFLICT, "El movimiento ya fue anulado."),
    MOVEMENT_EMPTY(HttpStatus.UNPROCESSABLE_CONTENT, "El movimiento debe incluir al menos un animal."),
    INVALID_MOVEMENT_DESTINATION(HttpStatus.UNPROCESSABLE_CONTENT, "El destino del movimiento no es válido."),
    INVALID_MOVEMENT_ORIGIN(HttpStatus.UNPROCESSABLE_CONTENT, "El origen del movimiento no coincide con la ubicación actual."),
    MOVEMENT_ALREADY_CONFIRMED(HttpStatus.CONFLICT, "El movimiento ya fue confirmado."),
    MOVEMENT_ALREADY_REVERTED(HttpStatus.CONFLICT, "El movimiento ya fue revertido."),
    MOVEMENT_REVERT_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_CONTENT, "El movimiento no puede revertirse en su estado o tipo actual."),
    MOVEMENT_CANNOT_BE_REVERSED(HttpStatus.CONFLICT, "Los animales ya no se encuentran donde el movimiento los dejó; no se puede revertir."),
    MOVEMENT_VERSION_CONFLICT(HttpStatus.CONFLICT, "El movimiento fue modificado por otro usuario."),
    INVALID_MOVEMENT_STATE_TRANSITION(HttpStatus.CONFLICT, "La transición de estado del movimiento no está permitida."),
    VERSION_CONFLICT(HttpStatus.CONFLICT, "El registro fue modificado por otro usuario."),
    PESAJE_NOT_FOUND(HttpStatus.NOT_FOUND, "El pesaje no existe."),
    PESAJE_ALREADY_ANNULLED(HttpStatus.CONFLICT, "El pesaje ya fue anulado."),
    PESAJE_DUPLICATED(HttpStatus.CONFLICT, "Ya existe un pesaje registrado para esta operación."),
    DISPOSITIVO_NOT_FOUND(HttpStatus.NOT_FOUND, "El dispositivo de sincronización no está registrado."),
    DISPOSITIVO_BLOQUEADO(HttpStatus.FORBIDDEN, "El dispositivo de sincronización está bloqueado."),
    OPERACION_TIPO_DESCONOCIDO(HttpStatus.UNPROCESSABLE_CONTENT, "El tipo de operación de sincronización no es válido."),
    OPERACION_DUPLICADA(HttpStatus.CONFLICT, "La operación ya fue procesada por el servidor."),
    DOCUMENTO_NOT_FOUND(HttpStatus.NOT_FOUND, "El documento no existe."),
    FOTO_PRINCIPAL_CONFIRMATION_REQUIRED(HttpStatus.UNPROCESSABLE_CONTENT, "La fotografía principal no puede eliminarse sin confirmación o reemplazo."),
    ENTIDAD_NO_SINCRONIZABLE(HttpStatus.UNPROCESSABLE_CONTENT, "La entidad no admite sincronización."),
    INVITACION_NOT_FOUND(HttpStatus.NOT_FOUND, "La invitación no existe en la empresa."),
    INVITACION_ACTIVA_EXISTE(HttpStatus.CONFLICT, "Ya existe una invitación activa para este correo."),
    INVITACION_ESTADO_INVALIDO(HttpStatus.UNPROCESSABLE_CONTENT, "La invitación no permite esa acción en su estado actual."),
    INVITACION_VENCIDA(HttpStatus.UNPROCESSABLE_CONTENT, "La invitación venció."),
    INVITACION_CANCELADA(HttpStatus.UNPROCESSABLE_CONTENT, "La invitación fue cancelada."),
    INVITACION_YA_ACEPTADA(HttpStatus.UNPROCESSABLE_CONTENT, "La invitación ya fue aceptada."),
    INVITACION_LIMITE_REENVIOS(HttpStatus.UNPROCESSABLE_CONTENT, "Se alcanzó el límite de reenvíos de la invitación."),
    OWNER_ROLE_REQUIRES_OWNER(HttpStatus.FORBIDDEN, "Solo un propietario puede asignar o retirar el rol PROPIETARIO."),
    BUSINESS_RULE_VIOLATION(HttpStatus.UNPROCESSABLE_CONTENT, "La operación incumple una regla de negocio."),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Ocurrió un error interno.");

    private final HttpStatus status;
    private final String defaultMessage;

    ErrorCode(HttpStatus status, String defaultMessage) {
        this.status = status;
        this.defaultMessage = defaultMessage;
    }

    public HttpStatus status() { return status; }
    public String defaultMessage() { return defaultMessage; }
}
