package bo.com.ganadero.potreros.infrastructure;
import bo.com.ganadero.potreros.domain.*; import bo.com.ganadero.shared.error.*;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*; import java.util.*;
@Repository class JdbcPotreroAdapter implements PotreroRepository,TipoPastoRepository {
 private final JdbcClient jdbc; JdbcPotreroAdapter(JdbcClient j){jdbc=j;}
 private static final String SELECT="select id,empresa_id,propiedad_id,sector_id,codigo,nombre,superficie_ha,tipo_pasto_id,capacidad_ua,tiene_agua,estado,case when geometria is null then null else st_astext(geometria::geometry) end geometria_wkt,activo,version from campo.potreros";
 public List<Potrero> findAll(UUID empresa,Set<UUID> allowed,UUID property,EstadoPotrero state,UUID sector){StringBuilder sql=new StringBuilder(SELECT+" where empresa_id=:e");if(!allowed.isEmpty())sql.append(" and propiedad_id in (:allowed)");if(property!=null)sql.append(" and propiedad_id=:property");if(state!=null)sql.append(" and estado=:state");if(sector!=null)sql.append(" and sector_id=:sector");sql.append(" order by nombre");JdbcClient.StatementSpec q=jdbc.sql(sql.toString()).param("e",empresa);if(!allowed.isEmpty())q=q.param("allowed",allowed);if(property!=null)q=q.param("property",property);if(state!=null)q=q.param("state",state.name());if(sector!=null)q=q.param("sector",sector);return q.query(this::paddock).list();}
 public Optional<Potrero> findById(UUID id,UUID empresa){return jdbc.sql(SELECT+" where id=:id and empresa_id=:e").param("id",id).param("e",empresa).query(this::paddock).optional();}
 public Potrero create(Potrero p,UUID actor){try{jdbc.sql("insert into campo.potreros(id,empresa_id,propiedad_id,sector_id,codigo,nombre,superficie_ha,tipo_pasto_id,capacidad_ua,tiene_agua,estado,geometria,activo,created_by,updated_by) values(:id,:e,:property,:sector,:code,:name,:area,:grass,:capacity,:water,:state,case when :geometry is null then null else st_geogfromtext(:geometry) end,:active,:actor,:actor)").params(params(p,actor)).update();}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.PADDOCK_CODE_ALREADY_EXISTS);}return findById(p.id(),p.empresaId()).orElseThrow();}
 public Potrero update(Potrero p,UUID actor){int changed;try{changed=jdbc.sql("update campo.potreros set propiedad_id=:property,sector_id=coalesce(:sector,sector_id),codigo=coalesce(:code,codigo),nombre=coalesce(:name,nombre),superficie_ha=coalesce(:area,superficie_ha),tipo_pasto_id=coalesce(:grass,tipo_pasto_id),capacidad_ua=coalesce(:capacity,capacidad_ua),tiene_agua=:water,estado=:state,geometria=case when :geometry is null then geometria else st_geogfromtext(:geometry) end,activo=:active,updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e and version=:version").params(params(p,actor)).update();}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.PADDOCK_CODE_ALREADY_EXISTS);}if(changed==0)throw new BusinessException(findById(p.id(),p.empresaId()).isPresent()?ErrorCode.VERSION_CONFLICT:ErrorCode.PADDOCK_NOT_FOUND);return findById(p.id(),p.empresaId()).orElseThrow();}
 public boolean propertyExists(UUID p,UUID e){return jdbc.sql("select exists(select 1 from core.propiedades where id=:p and empresa_id=:e and activo)").param("p",p).param("e",e).query(Boolean.class).single();}
 public boolean sectorBelongs(UUID s,UUID p,UUID e){return jdbc.sql("select exists(select 1 from campo.sectores where id=:s and propiedad_id=:p and empresa_id=:e and activo)").param("s",s).param("p",p).param("e",e).query(Boolean.class).single();}
 public boolean grassTypeExists(UUID g,UUID e){return jdbc.sql("select exists(select 1 from campo.tipos_pasto where id=:g and activo and (empresa_id is null or empresa_id=:e))").param("g",g).param("e",e).query(Boolean.class).single();}
 public boolean hasActiveAnimals(UUID p,UUID e){Boolean exists=jdbc.sql("select to_regclass('ganado.animales') is not null").query(Boolean.class).single();if(!Boolean.TRUE.equals(exists))return false;return jdbc.sql("select exists(select 1 from ganado.animales where empresa_id=:e and potrero_id=:p and estado='ACTIVO')").param("e",e).param("p",p).query(Boolean.class).single();}
 public List<TipoPasto> findActive(UUID e){return jdbc.sql("select * from campo.tipos_pasto where activo and (empresa_id is null or empresa_id=:e) order by nombre").param("e",e).query(this::grass).list();}
 private Map<String,Object> params(Potrero p,UUID actor){Map<String,Object> m=new HashMap<>();m.put("id",p.id());m.put("e",p.empresaId());m.put("property",p.propiedadId());m.put("sector",p.sectorId());m.put("code",p.codigo());m.put("name",p.nombre());m.put("area",p.superficieHa());m.put("grass",p.tipoPastoId());m.put("capacity",p.capacidadUa());m.put("water",p.tieneAgua());m.put("state",p.estado().name());m.put("geometry",p.geometriaWkt());m.put("active",p.activo());m.put("version",p.version());m.put("actor",actor);return m;}
 private Potrero paddock(ResultSet r,int n)throws SQLException{return new Potrero(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getObject("propiedad_id",UUID.class),r.getObject("sector_id",UUID.class),r.getString("codigo"),r.getString("nombre"),r.getBigDecimal("superficie_ha"),r.getObject("tipo_pasto_id",UUID.class),r.getBigDecimal("capacidad_ua"),r.getBoolean("tiene_agua"),EstadoPotrero.valueOf(r.getString("estado")),r.getString("geometria_wkt"),r.getBoolean("activo"),r.getLong("version"));}
 private TipoPasto grass(ResultSet r,int n)throws SQLException{return new TipoPasto(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getString("codigo"),r.getString("nombre"),r.getString("nombre_cientifico"),r.getString("descripcion"),r.getBoolean("activo"));}
}
