package bo.com.ganadero.sanidad.infrastructure;
import bo.com.ganadero.animales.domain.SexoAnimal; import bo.com.ganadero.sanidad.domain.*; import bo.com.ganadero.shared.db.Rows; import bo.com.ganadero.shared.error.*;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*; import java.time.*; import java.util.*;
@Repository public class JdbcSanidadRepository implements SanidadRepository {
 private final JdbcClient jdbc; public JdbcSanidadRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public List<Enfermedad> enfermedades(UUID e,boolean all){return jdbc.sql("select * from enfermedad where 1=1"+(all?"":" and activo")+" order by nombre")
  .query(this::enfermedad).list();}
 public Optional<Enfermedad> enfermedad(UUID id,UUID e){return jdbc.sql("select * from enfermedad where id=:id").param("id",id.toString()).query(this::enfermedad).optional();}
 public Enfermedad crearEnfermedad(Enfermedad v){jdbc.sql("insert into enfermedad(id,codigo,nombre,descripcion,es_notificable,activo) values(:id,:c,:n,:d,:not,:a)")
  .param("id",v.id().toString()).param("c",v.codigo()).param("n",v.nombre()).param("d",v.descripcion()).param("not",v.esNotificable()).param("a",v.activo()).update();return enfermedad(v.id(),v.empresaId()).orElseThrow();}
 public Enfermedad cambiarEstadoEnfermedad(UUID id,UUID e,boolean a){int n=jdbc.sql("update enfermedad set activo=:a,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where id=:id").param("a",a).param("id",id.toString()).update();if(n==0)throw new BusinessException(ErrorCode.SANIDAD_ENFERMEDAD_NOT_FOUND);return enfermedad(id,e).orElseThrow();}
 public List<PlanSanitario> planes(UUID e){return jdbc.sql("select * from plan_sanitario order by fecha_inicio desc").query(this::plan).list();}
 public Optional<PlanSanitario> plan(UUID id,UUID e){return jdbc.sql("select * from plan_sanitario where id=:id").param("id",id.toString()).query(this::plan).optional();}
 public PlanSanitario crearPlan(PlanSanitario v,UUID a){jdbc.sql("insert into plan_sanitario(id,nombre,descripcion,fecha_inicio,fecha_fin,estado,created_by,updated_by) values(:id,:n,:d,:ini,:fin,:estado,:a,:a)")
   .param("id",v.id().toString()).param("n",v.nombre()).param("d",v.descripcion()).param("ini",v.fechaInicio()==null?null:v.fechaInicio().toString()).param("fin",v.fechaFin()==null?null:v.fechaFin().toString()).param("estado",v.estado().name()).param("a",a.toString()).update();return plan(v.id(),v.empresaId()).orElseThrow();}
 public PlanSanitario cambiarEstadoPlan(UUID id,UUID e,EstadoPlanSanitario estado,long version,UUID actor){int n=jdbc.sql("update plan_sanitario set estado=:s,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and version=:v")
  .param("s",estado.name()).param("a",actor.toString()).param("id",id.toString()).param("v",version).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return plan(id,e).orElseThrow();}
 public List<PlanSanitarioItem> items(UUID p,UUID e,boolean all){return jdbc.sql("select * from plan_sanitario_item where plan_id=:p"+(all?"":" and activo")+" order by created_at").param("p",p.toString()).query(this::item).list();}
 public PlanSanitarioItem crearItem(PlanSanitarioItem v,UUID a){jdbc.sql("insert into plan_sanitario_item(id,plan_id,tipo_actividad,producto_id,producto_recomendado_texto,categoria_animal_id,sexo_aplicable,edad_min_dias,edad_max_dias,dosis,unidad_dosis,frecuencia_dias,dias_alerta,via_administracion,obligatorio,activo,created_by,updated_by) values(:id,:p,:tipo,:prod,:texto,:cat,:sexo,:emin,:emax,:dosis,:unidad,:freq,:alerta,:via,:obl,:activo,:a,:a)")
  .params(params(v,a)).update();return items(v.planId(),v.empresaId(),true).stream().filter(x->x.id().equals(v.id())).findFirst().orElseThrow();}
 public PlanSanitarioItem cambiarEstadoItem(UUID id,UUID p,UUID e,boolean activo,long version,UUID actor){int n=jdbc.sql("update plan_sanitario_item set activo=:activo,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and plan_id=:p and version=:v")
  .param("activo",activo).param("a",actor.toString()).param("id",id.toString()).param("p",p.toString()).param("v",version).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return items(p,e,true).stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();}
 private Map<String,Object> params(PlanSanitarioItem v,UUID a){Map<String,Object>p=new HashMap<>();p.put("id",v.id().toString());p.put("p",v.planId().toString());p.put("tipo",v.tipoActividad().name());p.put("prod",v.productoId()==null?null:v.productoId().toString());p.put("texto",v.productoRecomendadoTexto());p.put("cat",v.categoriaAnimalId()==null?null:v.categoriaAnimalId().toString());p.put("sexo",v.sexoAplicable()==null?null:v.sexoAplicable().name());p.put("emin",v.edadMinDias());p.put("emax",v.edadMaxDias());p.put("dosis",v.dosis());p.put("unidad",v.unidadDosis());p.put("freq",v.frecuenciaDias());p.put("alerta",v.diasAlerta());p.put("via",v.viaAdministracion());p.put("obl",v.obligatorio());p.put("activo",v.activo());p.put("a",a.toString());return p;}
  private Enfermedad enfermedad(ResultSet r,int n)throws SQLException{return new Enfermedad(Rows.uuid(r,"id"),null,r.getString("codigo"),r.getString("nombre"),r.getString("descripcion"),r.getBoolean("es_notificable"),r.getBoolean("activo"),Rows.instant(r,"created_at"),Rows.instant(r,"updated_at"));}
  private PlanSanitario plan(ResultSet r,int n)throws SQLException{return new PlanSanitario(Rows.uuid(r,"id"),null,r.getString("nombre"),r.getString("descripcion"),r.getString("fecha_inicio")==null?null:LocalDate.parse(r.getString("fecha_inicio")),r.getString("fecha_fin")==null?null:LocalDate.parse(r.getString("fecha_fin")),EstadoPlanSanitario.valueOf(r.getString("estado")),Rows.instant(r,"created_at"),Rows.instant(r,"updated_at"),r.getLong("version"));}
 private PlanSanitarioItem item(ResultSet r,int n)throws SQLException{String s=r.getString("sexo_aplicable");return new PlanSanitarioItem(Rows.uuid(r,"id"),null,Rows.uuid(r,"plan_id"),TipoActividadSanitaria.valueOf(r.getString("tipo_actividad")),Rows.uuid(r,"producto_id"),r.getString("producto_recomendado_texto"),Rows.uuid(r,"categoria_animal_id"),s==null?null:SexoAnimal.valueOf(s),r.getObject("edad_min_dias",Integer.class),r.getObject("edad_max_dias",Integer.class),r.getBigDecimal("dosis"),r.getString("unidad_dosis"),r.getObject("frecuencia_dias",Integer.class),r.getInt("dias_alerta"),r.getString("via_administracion"),r.getBoolean("obligatorio"),r.getBoolean("activo"),r.getLong("version"));}
}
