package bo.com.ganadero.sanidad.infrastructure;import bo.com.ganadero.sanidad.domain.*;import bo.com.ganadero.shared.db.Rows;import bo.com.ganadero.shared.error.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.*;import java.util.*;
@Repository public class JdbcClinicaRepository implements ClinicaRepository{private final JdbcClient j;public JdbcClinicaRepository(JdbcClient j){this.j=j;}
public CasoClinico crearCaso(CasoClinico c,UUID a){j.sql("insert into caso_clinico(id,animal_id,fecha_inicio,sintomas,enfermedad_id,diagnostico_texto,severidad,estado,veterinario_id,observaciones,restriccion_movimiento,created_by,updated_by) values(:id,:an,:f,:s,:enf,:d,:sev,:est,:v,:o,:rm,:a,:a)").param("id",c.id().toString()).param("an",c.animalId().toString()).param("f",str(c.fechaInicio())).param("s",c.sintomas()).param("enf",c.enfermedadId()==null?null:c.enfermedadId().toString()).param("d",c.diagnosticoTexto()).param("sev",c.severidad().name()).param("est",c.estado().name()).param("v",c.veterinarioId()).param("o",c.observaciones()).param("rm",c.restriccionMovimiento()==null?null:c.restriccionMovimiento().name()).param("a",a.toString()).update();return caso(c.id(),c.empresaId()).orElseThrow();}
public Optional<CasoClinico>caso(UUID id,UUID e){return j.sql("select * from caso_clinico where id=:id").param("id",id.toString()).query(this::mc).optional();}
public List<CasoClinico>casos(UUID e,UUID a){String sql="select * from caso_clinico"+(a==null?"":" where animal_id=:a")+" order by fecha_inicio desc";var q=j.sql(sql);if(a!=null)q=q.param("a",a.toString());return q.query(this::mc).list();}
public void estadoCaso(UUID id,UUID e,EstadoCasoClinico s,Instant f,String r,UUID a){j.sql("update caso_clinico set estado=:s,fecha_cierre=:f,resultado=:r,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id").param("s",s.name()).param("f",str(f)).param("r",r).param("a",a.toString()).param("id",id.toString()).update();}
public Tratamiento crearTratamiento(Tratamiento t,UUID a){j.sql("insert into tratamiento(id,caso_clinico_id,animal_id,fecha_inicio,fecha_fin_estimada,diagnostico,veterinario_id,estado,observaciones,restriccion_movimiento,created_by,updated_by) values(:id,:c,:an,:ini,:fin,:d,:v,:s,:o,:rm,:a,:a)").param("id",t.id().toString()).param("c",t.casoClinicoId()==null?null:t.casoClinicoId().toString()).param("an",t.animalId().toString()).param("ini",str(t.fechaInicio())).param("fin",str(t.fechaFinEstimada())).param("d",t.diagnostico()).param("v",t.veterinarioId()).param("s",t.estado().name()).param("o",t.observaciones()).param("rm",t.restriccionMovimiento()==null?null:t.restriccionMovimiento().name()).param("a",a.toString()).update();return tratamiento(t.id(),t.empresaId()).orElseThrow();}
public Optional<Tratamiento>tratamiento(UUID id,UUID e){return j.sql("select * from tratamiento where id=:id").param("id",id.toString()).query(this::mt).optional();}
public List<Tratamiento>tratamientos(UUID e,UUID a){String sql="select * from tratamiento"+(a==null?"":" where animal_id=:a")+" order by fecha_inicio desc";var q=j.sql(sql);if(a!=null)q=q.param("a",a.toString());return q.query(this::mt).list();}
public TratamientoDetalle crearDetalle(TratamientoDetalle d){j.sql("insert into tratamiento_detalle(id,tratamiento_id,producto_id,lote_producto_id,dosis,unidad_dosis,frecuencia_horas,duracion_dias,via_administracion,retiro_carne_dias,retiro_leche_dias,producto_texto) values(:id,:t,:p,:lp,:d,:u,:f,:dur,:v,:rc,:rl,:pt)").param("id",d.id().toString()).param("t",d.tratamientoId().toString()).param("p",d.productoId()==null?null:d.productoId().toString()).param("lp",d.loteProductoId()==null?null:d.loteProductoId().toString()).param("d",d.dosis()).param("u",d.unidadDosis()).param("f",d.frecuenciaHoras()).param("dur",d.duracionDias()).param("v",d.viaAdministracion()).param("rc",d.retiroCarneDias()).param("rl",d.retiroLecheDias()).param("pt",d.productoTexto()).update();return d;}
public List<TratamientoDetalle>detalles(UUID t,UUID e){return j.sql("select * from tratamiento_detalle where tratamiento_id=:t").param("t",t.toString()).query(this::md).list();}
public AplicacionTratamiento crearAplicacion(AplicacionTratamiento a){j.sql("insert into aplicacion_tratamiento(id,tratamiento_detalle_id,fecha_programada,dosis_programada,estado) values(:id,:d,:f,:dp,:s) on conflict do nothing").param("id",a.id().toString()).param("d",a.tratamientoDetalleId().toString()).param("f",str(a.fechaProgramada())).param("dp",a.dosisProgramada()).param("s",a.estado().name()).update();return a;}
public List<AplicacionTratamiento>aplicaciones(UUID t,UUID e){return j.sql("select a.*,d.producto_texto from aplicacion_tratamiento a join tratamiento_detalle d on d.id=a.tratamiento_detalle_id where d.tratamiento_id=:t order by fecha_programada").param("t",t.toString()).query(this::ma).list();}
public Optional<AplicacionTratamiento>aplicacion(UUID id,UUID t,UUID e){return aplicaciones(t,e).stream().filter(a->a.id().equals(id)).findFirst();}
public void activar(UUID id,UUID e,UUID a){j.sql("update tratamiento set estado='ACTIVO',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and estado in('BORRADOR','SUSPENDIDO')").param("a",a.toString()).param("id",id.toString()).update();}
public void cancelarFuturas(UUID t,UUID e){j.sql("update aplicacion_tratamiento set estado='CANCELADA',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where tratamiento_detalle_id in (select id from tratamiento_detalle where tratamiento_id=:t) and estado in('PENDIENTE','ATRASADA')").param("t",t.toString()).update();}
public AplicacionTratamiento aplicar(UUID id,UUID t,UUID e,Instant f,java.math.BigDecimal d,UUID actor,String o,long v,java.time.LocalDate rc,java.time.LocalDate rl){int n=j.sql("update aplicacion_tratamiento set estado='APLICADA',fecha_aplicada=:f,dosis_aplicada=:d,aplicado_por=:a,observaciones=:o,retiro_carne_hasta=:rc,retiro_leche_hasta=:rl,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where id=:id and tratamiento_detalle_id in (select id from tratamiento_detalle where tratamiento_id=:t) and estado in('PENDIENTE','ATRASADA') and version=:v").param("f",str(f)).param("d",d).param("a",actor.toString()).param("o",o).param("rc",rc==null?null:rc.toString()).param("rl",rl==null?null:rl.toString()).param("id",id.toString()).param("t",t.toString()).param("v",v).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return aplicacion(id,t,e).orElseThrow();}
public List<AplicacionTratamiento> marcarAtrasadas(UUID e,Instant now){List<AplicacionTratamiento> pendientes=j.sql("select a.*,d.producto_texto from aplicacion_tratamiento a join tratamiento_detalle d on d.id=a.tratamiento_detalle_id where a.estado='PENDIENTE' and a.fecha_programada<:n").param("n",str(now)).query(this::ma).list();if(!pendientes.isEmpty())j.sql("update aplicacion_tratamiento set estado='ATRASADA',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where estado='PENDIENTE' and fecha_programada<:n").param("n",str(now)).update();return pendientes.stream().map(a->new AplicacionTratamiento(a.id(),a.empresaId(),a.tratamientoDetalleId(),a.fechaProgramada(),a.fechaAplicada(),a.dosisProgramada(),a.dosisAplicada(),a.aplicadoPor(),EstadoAplicacionTratamiento.ATRASADA,a.observaciones(),a.version()+1,a.retiroCarneHasta(),a.retiroLecheHasta(),a.productoTexto())).toList();}
public void finalizar(UUID id,UUID e,UUID a){j.sql("update tratamiento set estado='FINALIZADO',fecha_fin_real=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and estado='ACTIVO'").param("a",a.toString()).param("id",id.toString()).update();}
 public void reprogramarFin(UUID id,UUID e,Instant f,UUID a){j.sql("update tratamiento set fecha_fin_estimada=:f,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id").param("f",str(f)).param("a",a.toString()).param("id",id.toString()).update();}
public ControlNeonatal crearControl(ControlNeonatal c,UUID a){j.sql("insert into control_neonatal(id,animal_id,fecha_control,momento,calostrado,ombligo_desinfectado,ombligo_estado,diarrea,estado_general,lactancia,temperatura_c,observaciones,created_by,updated_by) values(:id,:an,:f,:m,:cal,:od,:oe,:di,:eg,:lac,:temp,:o,:a,:a)").param("id",c.id().toString()).param("an",c.animalId().toString()).param("f",c.fechaControl().toString()).param("m",c.momento().name()).param("cal",c.calostrado().name()).param("od",c.ombligoDesinfectado()).param("oe",c.ombligoEstado()).param("di",c.diarrea()).param("eg",c.estadoGeneral()).param("lac",c.lactancia()).param("temp",c.temperaturaC()).param("o",c.observaciones()).param("a",a.toString()).update();return c;}
public List<ControlNeonatal> controles(UUID e,UUID a){String sql="select * from control_neonatal"+(a==null?"":" where animal_id=:a")+" order by fecha_control,created_at";var q=j.sql(sql);if(a!=null)q=q.param("a",a.toString());return q.query(this::mcn).list();}
public ControlEctoparasitario crearControlEcto(ControlEctoparasitario c,UUID a){j.sql("insert into control_ectoparasitario(id,animal_id,lote_ganadero_id,tipo,nivel_carga,tratado,producto,principio_activo,fecha,observaciones,created_by,updated_by) values(:id,:an,:lo,:t,:n,:tr,:p,:pa,:f,:o,:a,:a)").param("id",c.id().toString()).param("an",c.animalId()==null?null:c.animalId().toString()).param("lo",c.loteGanaderoId()==null?null:c.loteGanaderoId().toString()).param("t",c.tipo().name()).param("n",c.nivelCarga().name()).param("tr",c.tratado()).param("p",c.producto()).param("pa",c.principioActivo()).param("f",c.fecha().toString()).param("o",c.observaciones()).param("a",a.toString()).update();return c;}
public List<ControlEctoparasitario> controlesEcto(UUID e,UUID a,UUID l){StringBuilder sql=new StringBuilder("select * from control_ectoparasitario where 1=1");if(a!=null)sql.append(" and animal_id=:a");if(l!=null)sql.append(" and lote_ganadero_id=:l");sql.append(" order by fecha desc");var q=j.sql(sql.toString());if(a!=null)q=q.param("a",a.toString());if(l!=null)q=q.param("l",l.toString());return q.query(this::mce).list();}
public List<String> principiosActivosRecientes(UUID e,UUID a,UUID l,int limite){StringBuilder sql=new StringBuilder("select principio_activo from control_ectoparasitario where principio_activo is not null");if(a!=null)sql.append(" and animal_id=:a");if(l!=null)sql.append(" and lote_ganadero_id=:l");sql.append(" order by fecha desc limit :lim");var q=j.sql(sql.toString()).param("lim",limite);if(a!=null)q=q.param("a",a.toString());if(l!=null)q=q.param("l",l.toString());return q.query(String.class).list();}
public ExamenReproductivo crearExamen(ExamenReproductivo x,List<PruebaReproductiva> pruebas,UUID a){j.sql("insert into examen_reproductivo(id,animal_id,fecha,resultado,veterinario_id,circunferencia_escrotal_cm,motilidad_espermatica_pct,morfologia_pct,libido,capacidad_servicio,peso_kg,porcentaje_peso_adulto,condicion_corporal,desarrollo_reproductivo,observaciones,created_by,updated_by) values(:id,:an,:f,:r,:v,:ce,:me,:mor,:li,:cs,:pk,:ppa,:cc,:dr,:o,:a,:a)").param("id",x.id().toString()).param("an",x.animalId().toString()).param("f",x.fecha().toString()).param("r",x.resultado().name()).param("v",x.veterinarioId()).param("ce",x.circunferenciaEscrotalCm()).param("me",x.motilidadEspermaticaPct()).param("mor",x.morfologiaPct()).param("li",x.libido()).param("cs",x.capacidadServicio()).param("pk",x.pesoKg()).param("ppa",x.porcentajePesoAdulto()).param("cc",x.condicionCorporal()).param("dr",x.desarrolloReproductivo()).param("o",x.observaciones()).param("a",a.toString()).update();for(PruebaReproductiva p:pruebas){j.sql("insert into examen_reproductivo_prueba(id,examen_id,enfermedad,resultado) values(:id,:ex,:e,:r)").param("id",UUID.randomUUID().toString()).param("ex",x.id().toString()).param("e",p.enfermedad().name()).param("r",p.resultado().name()).update();}return x;}
public List<ExamenReproductivo> examenes(UUID e,UUID a){String sql="select * from examen_reproductivo"+(a==null?"":" where animal_id=:a")+" order by fecha desc";var q=j.sql(sql);if(a!=null)q=q.param("a",a.toString());return q.query(this::mer).list().stream().map(this::conPruebas).toList();}
private ExamenReproductivo conPruebas(ExamenReproductivo x){return new ExamenReproductivo(x.id(),x.empresaId(),x.animalId(),x.fecha(),x.resultado(),x.veterinarioId(),x.circunferenciaEscrotalCm(),x.motilidadEspermaticaPct(),x.morfologiaPct(),x.libido(),x.capacidadServicio(),x.pesoKg(),x.porcentajePesoAdulto(),x.condicionCorporal(),x.desarrolloReproductivo(),x.observaciones(),x.version(),pruebasDe(x.id()));}
private List<PruebaReproductiva> pruebasDe(UUID examenId){return j.sql("select * from examen_reproductivo_prueba where examen_id=:e order by enfermedad").param("e",examenId.toString()).query(this::mpr).list();}
private CasoClinico mc(ResultSet r,int n)throws SQLException{String rm=r.getString("restriccion_movimiento");return new CasoClinico(Rows.uuid(r,"id"),null,Rows.uuid(r,"animal_id"),Rows.instant(r,"fecha_inicio"),r.getString("sintomas"),Rows.uuid(r,"enfermedad_id"),r.getString("diagnostico_texto"),SeveridadCaso.valueOf(r.getString("severidad")),EstadoCasoClinico.valueOf(r.getString("estado")),r.getString("veterinario_id"),Rows.instant(r,"fecha_cierre"),r.getString("resultado"),r.getString("observaciones"),r.getLong("version"),rm==null?null:RestriccionMovimiento.valueOf(rm));}
private Tratamiento mt(ResultSet r,int n)throws SQLException{String rm=r.getString("restriccion_movimiento");return new Tratamiento(Rows.uuid(r,"id"),null,Rows.uuid(r,"caso_clinico_id"),Rows.uuid(r,"animal_id"),Rows.instant(r,"fecha_inicio"),Rows.instant(r,"fecha_fin_estimada"),Rows.instant(r,"fecha_fin_real"),r.getString("diagnostico"),r.getString("veterinario_id"),EstadoTratamiento.valueOf(r.getString("estado")),r.getString("observaciones"),r.getLong("version"),rm==null?null:RestriccionMovimiento.valueOf(rm));}
private TratamientoDetalle md(ResultSet r,int n)throws SQLException{return new TratamientoDetalle(Rows.uuid(r,"id"),null,Rows.uuid(r,"tratamiento_id"),Rows.uuid(r,"producto_id"),Rows.uuid(r,"lote_producto_id"),r.getBigDecimal("dosis"),r.getString("unidad_dosis"),r.getInt("frecuencia_horas"),r.getInt("duracion_dias"),r.getString("via_administracion"),r.getInt("retiro_carne_dias"),r.getInt("retiro_leche_dias"),r.getString("producto_texto"));}
private AplicacionTratamiento ma(ResultSet r,int n)throws SQLException{return new AplicacionTratamiento(Rows.uuid(r,"id"),null,Rows.uuid(r,"tratamiento_detalle_id"),Rows.instant(r,"fecha_programada"),Rows.instant(r,"fecha_aplicada"),r.getBigDecimal("dosis_programada"),r.getBigDecimal("dosis_aplicada"),Rows.uuid(r,"aplicado_por"),EstadoAplicacionTratamiento.valueOf(r.getString("estado")),r.getString("observaciones"),r.getLong("version"),Rows.localDate(r,"retiro_carne_hasta"),Rows.localDate(r,"retiro_leche_hasta"),r.getString("producto_texto"));}
private ControlNeonatal mcn(ResultSet r,int n)throws SQLException{return new ControlNeonatal(Rows.uuid(r,"id"),null,Rows.uuid(r,"animal_id"),Rows.localDate(r,"fecha_control"),MomentoControlNeonatal.valueOf(r.getString("momento")),EstadoCalostrado.valueOf(r.getString("calostrado")),r.getBoolean("ombligo_desinfectado"),r.getString("ombligo_estado"),r.getBoolean("diarrea"),r.getString("estado_general"),r.getString("lactancia"),r.getBigDecimal("temperatura_c"),r.getString("observaciones"),r.getLong("version"));}
private ControlEctoparasitario mce(ResultSet r,int n)throws SQLException{return new ControlEctoparasitario(Rows.uuid(r,"id"),null,Rows.uuid(r,"animal_id"),Rows.uuid(r,"lote_ganadero_id"),TipoEctoparasito.valueOf(r.getString("tipo")),NivelCargaParasitaria.valueOf(r.getString("nivel_carga")),r.getBoolean("tratado"),r.getString("producto"),r.getString("principio_activo"),Rows.localDate(r,"fecha"),r.getString("observaciones"),r.getLong("version"));}
private ExamenReproductivo mer(ResultSet r,int n)throws SQLException{return new ExamenReproductivo(Rows.uuid(r,"id"),null,Rows.uuid(r,"animal_id"),Rows.localDate(r,"fecha"),ResultadoExamenReproductivo.valueOf(r.getString("resultado")),r.getString("veterinario_id"),r.getBigDecimal("circunferencia_escrotal_cm"),r.getBigDecimal("motilidad_espermatica_pct"),r.getBigDecimal("morfologia_pct"),r.getString("libido"),r.getString("capacidad_servicio"),r.getBigDecimal("peso_kg"),r.getBigDecimal("porcentaje_peso_adulto"),r.getBigDecimal("condicion_corporal"),r.getString("desarrollo_reproductivo"),r.getString("observaciones"),r.getLong("version"),List.of());}
private PruebaReproductiva mpr(ResultSet r,int n)throws SQLException{return new PruebaReproductiva(EnfermedadReproductiva.valueOf(r.getString("enfermedad")),ResultadoPruebaReproductiva.valueOf(r.getString("resultado")));}
private static String str(Instant i){return i==null?null:i.toString();}
}
