package bo.com.ganadero.sanidad.infrastructure;
import bo.com.ganadero.sanidad.domain.*; import bo.com.ganadero.shared.error.*; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*;import java.time.*;import java.util.*;
@Repository public class JdbcJornadaSanitariaRepository implements JornadaSanitariaRepository{
 private final JdbcClient jdbc;public JdbcJornadaSanitariaRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public JornadaSanitaria crear(JornadaSanitaria j,UUID a){jdbc.sql("insert into sanidad.jornadas_sanitarias(id,empresa_id,tipo_jornada,fecha_inicio,fecha_fin,propiedad_id,potrero_id,lote_ganadero_id,responsable_id,veterinario_id,estado,observaciones,operation_id,created_by,updated_by) values(:id,:e,:t,:ini,:fin,:p,:pot,:lote,:r,:v,:estado,:o,:op,:a,:a)").params(params(j,a)).update();return buscar(j.id(),j.empresaId()).orElseThrow();}
 public Optional<JornadaSanitaria> buscar(UUID id,UUID e){return jdbc.sql("select * from sanidad.jornadas_sanitarias where id=:id and empresa_id=:e").param("id",id).param("e",e).query(this::mapJ).optional();}
 public Optional<JornadaSanitaria> buscarPorOperacion(UUID op,UUID e){return jdbc.sql("select * from sanidad.jornadas_sanitarias where operation_id=:op and empresa_id=:e").param("op",op).param("e",e).query(this::mapJ).optional();}
 public List<JornadaSanitaria> listar(UUID e){return jdbc.sql("select * from sanidad.jornadas_sanitarias where empresa_id=:e order by fecha_inicio desc").param("e",e).query(this::mapJ).list();}
 public void reemplazarSeleccion(UUID j,UUID e,Collection<UUID> a){jdbc.sql("delete from sanidad.jornada_animales where jornada_id=:j and empresa_id=:e").param("j",j).param("e",e).update();for(UUID id:a)jdbc.sql("insert into sanidad.jornada_animales(jornada_id,empresa_id,animal_id) values(:j,:e,:a) on conflict do nothing").param("j",j).param("e",e).param("a",id).update();}
 public List<UUID> seleccion(UUID j,UUID e){return jdbc.sql("select animal_id from sanidad.jornada_animales where jornada_id=:j and empresa_id=:e order by animal_id").param("j",j).param("e",e).query(UUID.class).list();}
 public JornadaSanitaria iniciarConfirmacion(UUID id,UUID e,long v,UUID op,UUID a){int n=jdbc.sql("update sanidad.jornadas_sanitarias set estado='EN_PROCESO',operation_id=:op,updated_at=now(),updated_by=:a,version=version+1 where id=:id and empresa_id=:e and estado='BORRADOR' and version=:v").param("op",op).param("a",a).param("id",id).param("e",e).param("v",v).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return buscar(id,e).orElseThrow();}
 public JornadaSanitaria confirmar(UUID id,UUID e,UUID a){jdbc.sql("update sanidad.jornadas_sanitarias set estado='CONFIRMADA',fecha_fin=coalesce(fecha_fin,current_date),updated_at=now(),updated_by=:a,version=version+1 where id=:id and empresa_id=:e and estado='EN_PROCESO'").param("a",a).param("id",id).param("e",e).update();return buscar(id,e).orElseThrow();}
 public AplicacionSanitaria crearAplicacion(AplicacionSanitaria x,UUID a){jdbc.sql("insert into sanidad.aplicaciones_sanitarias(id,empresa_id,jornada_id,plan_item_id,animal_id,producto_id,lote_producto_id,dosis,unidad_dosis,via_administracion,fecha_aplicacion,proxima_aplicacion,retiro_carne_hasta,retiro_leche_hasta,aplicado_por,resultado,observaciones,idempotency_key,estado,created_by) values(:id,:e,:j,:pi,:animal,:p,:lp,:d,:u,:via,:f,:prox,:rc,:rl,:por,:res,:o,:key,:estado,:a) on conflict(empresa_id,idempotency_key) do nothing").params(params(x,a)).update();return aplicaciones(x.jornadaId(),x.empresaId()).stream().filter(y->y.animalId().equals(x.animalId())).findFirst().orElseThrow();}
 public List<AplicacionSanitaria> aplicaciones(UUID j,UUID e){return jdbc.sql("select * from sanidad.aplicaciones_sanitarias where jornada_id=:j and empresa_id=:e order by created_at").param("j",j).param("e",e).query(this::mapA).list();}
 public List<UUID> aplicacionesPrevias(UUID e,UUID animal,UUID item,UUID excluir){return jdbc.sql("select id from sanidad.aplicaciones_sanitarias where empresa_id=:e and animal_id=:a and plan_item_id=:i and id<>:x and estado='APLICADA'").param("e",e).param("a",animal).param("i",item).param("x",excluir).query(UUID.class).list();}
 private Map<String,Object>params(JornadaSanitaria j,UUID a){Map<String,Object>p=new HashMap<>();p.put("id",j.id());p.put("e",j.empresaId());p.put("t",j.tipoJornada().name());p.put("ini",j.fechaInicio());p.put("fin",j.fechaFin());p.put("p",j.propiedadId());p.put("pot",j.potreroId());p.put("lote",j.loteGanaderoId());p.put("r",j.responsableId());p.put("v",j.veterinarioId());p.put("estado",j.estado().name());p.put("o",j.observaciones());p.put("op",j.operationId());p.put("a",a);return p;}
 private Map<String,Object>params(AplicacionSanitaria x,UUID a){Map<String,Object>p=new HashMap<>();p.put("id",x.id());p.put("e",x.empresaId());p.put("j",x.jornadaId());p.put("pi",x.planItemId());p.put("animal",x.animalId());p.put("p",x.productoId());p.put("lp",x.loteProductoId());p.put("d",x.dosis());p.put("u",x.unidadDosis());p.put("via",x.viaAdministracion());p.put("f",x.fechaAplicacion());p.put("prox",x.proximaAplicacion());p.put("rc",x.retiroCarneHasta());p.put("rl",x.retiroLecheHasta());p.put("por",x.aplicadoPor());p.put("res",x.resultado());p.put("o",x.observaciones());p.put("key",x.idempotencyKey());p.put("estado",x.estado());p.put("a",a);return p;}
 private JornadaSanitaria mapJ(ResultSet r,int n)throws SQLException{return new JornadaSanitaria(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),TipoActividadSanitaria.valueOf(r.getString("tipo_jornada")),r.getObject("fecha_inicio",LocalDate.class),r.getObject("fecha_fin",LocalDate.class),r.getObject("propiedad_id",UUID.class),r.getObject("potrero_id",UUID.class),r.getObject("lote_ganadero_id",UUID.class),r.getObject("responsable_id",UUID.class),r.getObject("veterinario_id",UUID.class),EstadoJornada.valueOf(r.getString("estado")),r.getString("observaciones"),r.getObject("operation_id",UUID.class),r.getLong("version"));}
 private AplicacionSanitaria mapA(ResultSet r,int n)throws SQLException{return new AplicacionSanitaria(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getObject("jornada_id",UUID.class),r.getObject("plan_item_id",UUID.class),r.getObject("animal_id",UUID.class),r.getObject("producto_id",UUID.class),r.getObject("lote_producto_id",UUID.class),r.getBigDecimal("dosis"),r.getString("unidad_dosis"),r.getString("via_administracion"),r.getObject("fecha_aplicacion",LocalDate.class),r.getObject("proxima_aplicacion",LocalDate.class),r.getObject("retiro_carne_hasta",LocalDate.class),r.getObject("retiro_leche_hasta",LocalDate.class),r.getObject("aplicado_por",UUID.class),r.getString("resultado"),r.getString("observaciones"),r.getString("idempotency_key"),r.getString("estado"),r.getLong("version"));}
}
