package bo.com.ganadero.sanidad.infrastructure;
import bo.com.ganadero.animales.domain.SexoAnimal; import bo.com.ganadero.sanidad.domain.*; import bo.com.ganadero.shared.error.*;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*; import java.time.*; import java.util.*;
@Repository public class JdbcSanidadRepository implements SanidadRepository {
 private final JdbcClient jdbc; public JdbcSanidadRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public List<Enfermedad> enfermedades(UUID e,boolean all){return jdbc.sql("select * from sanidad.enfermedades where (empresa_id is null or empresa_id=:e)"+(all?"":" and activo")+" order by nombre")
  .param("e",e).query(this::enfermedad).list();}
 public Optional<Enfermedad> enfermedad(UUID id,UUID e){return jdbc.sql("select * from sanidad.enfermedades where id=:id and (empresa_id is null or empresa_id=:e)").param("id",id).param("e",e).query(this::enfermedad).optional();}
 public Enfermedad crearEnfermedad(Enfermedad v){jdbc.sql("insert into sanidad.enfermedades(id,empresa_id,codigo,nombre,descripcion,es_notificable,activo) values(:id,:e,:c,:n,:d,:not,:a)")
  .param("id",v.id()).param("e",v.empresaId()).param("c",v.codigo()).param("n",v.nombre()).param("d",v.descripcion()).param("not",v.esNotificable()).param("a",v.activo()).update();return enfermedad(v.id(),v.empresaId()).orElseThrow();}
 public Enfermedad cambiarEstadoEnfermedad(UUID id,UUID e,boolean a){int n=jdbc.sql("update sanidad.enfermedades set activo=:a,updated_at=now() where id=:id and empresa_id=:e").param("a",a).param("id",id).param("e",e).update();if(n==0)throw new BusinessException(ErrorCode.SANIDAD_ENFERMEDAD_NOT_FOUND);return enfermedad(id,e).orElseThrow();}
 public List<PlanSanitario> planes(UUID e){return jdbc.sql("select * from sanidad.planes_sanitarios where empresa_id=:e order by fecha_inicio desc").param("e",e).query(this::plan).list();}
 public Optional<PlanSanitario> plan(UUID id,UUID e){return jdbc.sql("select * from sanidad.planes_sanitarios where id=:id and empresa_id=:e").param("id",id).param("e",e).query(this::plan).optional();}
 public PlanSanitario crearPlan(PlanSanitario v,UUID a){jdbc.sql("insert into sanidad.planes_sanitarios(id,empresa_id,nombre,descripcion,fecha_inicio,fecha_fin,estado,created_by,updated_by) values(:id,:e,:n,:d,:ini,:fin,:estado,:a,:a)")
   .param("id",v.id()).param("e",v.empresaId()).param("n",v.nombre()).param("d",v.descripcion()).param("ini",v.fechaInicio()).param("fin",v.fechaFin()).param("estado",v.estado().name()).param("a",a).update();return plan(v.id(),v.empresaId()).orElseThrow();}
 public PlanSanitario cambiarEstadoPlan(UUID id,UUID e,EstadoPlanSanitario estado,long version,UUID actor){int n=jdbc.sql("update sanidad.planes_sanitarios set estado=:s,updated_at=now(),updated_by=:a,version=version+1 where id=:id and empresa_id=:e and version=:v")
  .param("s",estado.name()).param("a",actor).param("id",id).param("e",e).param("v",version).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return plan(id,e).orElseThrow();}
 public List<PlanSanitarioItem> items(UUID p,UUID e,boolean all){return jdbc.sql("select * from sanidad.plan_sanitario_items where plan_id=:p and empresa_id=:e"+(all?"":" and activo")+" order by created_at").param("p",p).param("e",e).query(this::item).list();}
 public PlanSanitarioItem crearItem(PlanSanitarioItem v,UUID a){jdbc.sql("insert into sanidad.plan_sanitario_items(id,empresa_id,plan_id,tipo_actividad,producto_id,producto_recomendado_texto,categoria_animal_id,sexo_aplicable,edad_min_dias,edad_max_dias,dosis,unidad_dosis,frecuencia_dias,dias_alerta,via_administracion,obligatorio,activo,created_by,updated_by) values(:id,:e,:p,:tipo,:prod,:texto,:cat,:sexo,:emin,:emax,:dosis,:unidad,:freq,:alerta,:via,:obl,:activo,:a,:a)")
  .params(params(v,a)).update();return items(v.planId(),v.empresaId(),true).stream().filter(x->x.id().equals(v.id())).findFirst().orElseThrow();}
 public PlanSanitarioItem cambiarEstadoItem(UUID id,UUID p,UUID e,boolean activo,long version,UUID actor){int n=jdbc.sql("update sanidad.plan_sanitario_items set activo=:activo,updated_at=now(),updated_by=:a,version=version+1 where id=:id and plan_id=:p and empresa_id=:e and version=:v")
  .param("activo",activo).param("a",actor).param("id",id).param("p",p).param("e",e).param("v",version).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return items(p,e,true).stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();}
 private Map<String,Object> params(PlanSanitarioItem v,UUID a){Map<String,Object>p=new HashMap<>();p.put("id",v.id());p.put("e",v.empresaId());p.put("p",v.planId());p.put("tipo",v.tipoActividad().name());p.put("prod",v.productoId());p.put("texto",v.productoRecomendadoTexto());p.put("cat",v.categoriaAnimalId());p.put("sexo",v.sexoAplicable()==null?null:v.sexoAplicable().name());p.put("emin",v.edadMinDias());p.put("emax",v.edadMaxDias());p.put("dosis",v.dosis());p.put("unidad",v.unidadDosis());p.put("freq",v.frecuenciaDias());p.put("alerta",v.diasAlerta());p.put("via",v.viaAdministracion());p.put("obl",v.obligatorio());p.put("activo",v.activo());p.put("a",a);return p;}
  private Enfermedad enfermedad(ResultSet r,int n)throws SQLException{return new Enfermedad(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getString("codigo"),r.getString("nombre"),r.getString("descripcion"),r.getBoolean("es_notificable"),r.getBoolean("activo"),instant(r,"created_at"),instant(r,"updated_at"));}
  private PlanSanitario plan(ResultSet r,int n)throws SQLException{return new PlanSanitario(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getString("nombre"),r.getString("descripcion"),r.getObject("fecha_inicio",LocalDate.class),r.getObject("fecha_fin",LocalDate.class),EstadoPlanSanitario.valueOf(r.getString("estado")),instant(r,"created_at"),instant(r,"updated_at"),r.getLong("version"));}
  private static Instant instant(ResultSet r,String c)throws SQLException{OffsetDateTime v=r.getObject(c,OffsetDateTime.class);return v==null?null:v.toInstant();}
 private PlanSanitarioItem item(ResultSet r,int n)throws SQLException{String s=r.getString("sexo_aplicable");return new PlanSanitarioItem(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getObject("plan_id",UUID.class),TipoActividadSanitaria.valueOf(r.getString("tipo_actividad")),r.getObject("producto_id",UUID.class),r.getString("producto_recomendado_texto"),r.getObject("categoria_animal_id",UUID.class),s==null?null:SexoAnimal.valueOf(s),r.getObject("edad_min_dias",Integer.class),r.getObject("edad_max_dias",Integer.class),r.getBigDecimal("dosis"),r.getString("unidad_dosis"),r.getObject("frecuencia_dias",Integer.class),r.getInt("dias_alerta"),r.getString("via_administracion"),r.getBoolean("obligatorio"),r.getBoolean("activo"),r.getLong("version"));}
}
