package bo.com.ganadero.sanidad.infrastructure;
import bo.com.ganadero.sanidad.domain.*; import bo.com.ganadero.shared.db.Rows; import bo.com.ganadero.shared.error.*; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*;import java.time.*;import java.util.*;
@Repository public class JdbcJornadaSanitariaRepository implements JornadaSanitariaRepository{
 private final JdbcClient jdbc;public JdbcJornadaSanitariaRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public JornadaSanitaria crear(JornadaSanitaria j,UUID a){jdbc.sql("insert into jornada_sanitaria(id,tipo_jornada,fecha_inicio,fecha_fin,potrero_id,lote_ganadero_id,responsable_id,veterinario_id,estado,observaciones,operation_id,created_by,updated_by) values(:id,:t,:ini,:fin,:pot,:lote,:r,:v,:estado,:o,:op,:a,:a)").params(params(j,a)).update();return buscar(j.id(),j.empresaId()).orElseThrow();}
 public Optional<JornadaSanitaria> buscar(UUID id,UUID e){return jdbc.sql("select * from jornada_sanitaria where id=:id").param("id",id.toString()).query(this::mapJ).optional();}
 public Optional<JornadaSanitaria> buscarPorOperacion(UUID op,UUID e){return jdbc.sql("select * from jornada_sanitaria where operation_id=:op").param("op",op.toString()).query(this::mapJ).optional();}
 public List<JornadaSanitaria> listar(UUID e){return jdbc.sql("select * from jornada_sanitaria order by fecha_inicio desc").query(this::mapJ).list();}
 public void reemplazarSeleccion(UUID j,UUID e,Collection<UUID> a){jdbc.sql("delete from jornada_animal where jornada_id=:j").param("j",j.toString()).update();for(UUID id:a)jdbc.sql("insert into jornada_animal(jornada_id,animal_id) values(:j,:a) on conflict do nothing").param("j",j.toString()).param("a",id.toString()).update();}
 public List<UUID> seleccion(UUID j,UUID e){return jdbc.sql("select animal_id from jornada_animal where jornada_id=:j order by animal_id").param("j",j.toString()).query(String.class).list().stream().map(UUID::fromString).toList();}
 public JornadaSanitaria iniciarConfirmacion(UUID id,UUID e,long v,UUID op,UUID a){int n=jdbc.sql("update jornada_sanitaria set estado='EN_PROCESO',operation_id=:op,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and estado='BORRADOR' and version=:v").param("op",op.toString()).param("a",a.toString()).param("id",id.toString()).param("v",v).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return buscar(id,e).orElseThrow();}
 public JornadaSanitaria confirmar(UUID id,UUID e,UUID a){jdbc.sql("update jornada_sanitaria set estado='CONFIRMADA',fecha_fin=coalesce(fecha_fin,date('now')),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and estado='EN_PROCESO'").param("a",a.toString()).param("id",id.toString()).update();return buscar(id,e).orElseThrow();}
 public AplicacionSanitaria crearAplicacion(AplicacionSanitaria x,UUID a){jdbc.sql("insert into aplicacion_sanitaria(id,jornada_id,plan_item_id,animal_id,producto_id,lote_producto_id,dosis,unidad_dosis,via_administracion,fecha_aplicacion,proxima_aplicacion,retiro_carne_hasta,retiro_leche_hasta,aplicado_por,resultado,observaciones,idempotency_key,estado,created_by) values(:id,:j,:pi,:animal,:p,:lp,:d,:u,:via,:f,:prox,:rc,:rl,:por,:res,:o,:key,:estado,:a) on conflict(idempotency_key) do nothing").params(params(x,a)).update();return aplicaciones(x.jornadaId(),x.empresaId()).stream().filter(y->y.animalId().equals(x.animalId())).findFirst().orElseThrow();}
 public List<AplicacionSanitaria> aplicaciones(UUID j,UUID e){return jdbc.sql("select * from aplicacion_sanitaria where jornada_id=:j order by created_at").param("j",j.toString()).query(this::mapA).list();}
 public List<UUID> aplicacionesPrevias(UUID e,UUID animal,UUID item,UUID excluir){return jdbc.sql("select id from aplicacion_sanitaria where animal_id=:a and plan_item_id=:i and id<>:x and estado='APLICADA'").param("a",animal.toString()).param("i",item.toString()).param("x",excluir.toString()).query(String.class).list().stream().map(UUID::fromString).toList();}
 private Map<String,Object>params(JornadaSanitaria j,UUID a){Map<String,Object>p=new HashMap<>();p.put("id",j.id().toString());p.put("t",j.tipoJornada().name());p.put("ini",j.fechaInicio()==null?null:j.fechaInicio().toString());p.put("fin",j.fechaFin()==null?null:j.fechaFin().toString());p.put("pot",j.potreroId()==null?null:j.potreroId().toString());p.put("lote",j.loteGanaderoId()==null?null:j.loteGanaderoId().toString());p.put("r",j.responsableId()==null?null:j.responsableId().toString());p.put("v",j.veterinarioId()==null?null:j.veterinarioId().toString());p.put("estado",j.estado().name());p.put("o",j.observaciones());p.put("op",j.operationId()==null?null:j.operationId().toString());p.put("a",a.toString());return p;}
 private Map<String,Object>params(AplicacionSanitaria x,UUID a){Map<String,Object>p=new HashMap<>();p.put("id",x.id().toString());p.put("j",x.jornadaId().toString());p.put("pi",x.planItemId()==null?null:x.planItemId().toString());p.put("animal",x.animalId().toString());p.put("p",x.productoId()==null?null:x.productoId().toString());p.put("lp",x.loteProductoId()==null?null:x.loteProductoId().toString());p.put("d",x.dosis());p.put("u",x.unidadDosis());p.put("via",x.viaAdministracion());p.put("f",x.fechaAplicacion()==null?null:x.fechaAplicacion().toString());p.put("prox",x.proximaAplicacion()==null?null:x.proximaAplicacion().toString());p.put("rc",x.retiroCarneHasta()==null?null:x.retiroCarneHasta().toString());p.put("rl",x.retiroLecheHasta()==null?null:x.retiroLecheHasta().toString());p.put("por",x.aplicadoPor()==null?null:x.aplicadoPor().toString());p.put("res",x.resultado());p.put("o",x.observaciones());p.put("key",x.idempotencyKey());p.put("estado",x.estado());p.put("a",a.toString());return p;}
 private JornadaSanitaria mapJ(ResultSet r,int n)throws SQLException{return new JornadaSanitaria(Rows.uuid(r,"id"),null,TipoActividadSanitaria.valueOf(r.getString("tipo_jornada")),r.getString("fecha_inicio")==null?null:LocalDate.parse(r.getString("fecha_inicio")),r.getString("fecha_fin")==null?null:LocalDate.parse(r.getString("fecha_fin")),null,Rows.uuid(r,"potrero_id"),Rows.uuid(r,"lote_ganadero_id"),Rows.uuid(r,"responsable_id"),Rows.uuid(r,"veterinario_id"),EstadoJornada.valueOf(r.getString("estado")),r.getString("observaciones"),Rows.uuid(r,"operation_id"),r.getLong("version"));}
 private AplicacionSanitaria mapA(ResultSet r,int n)throws SQLException{return new AplicacionSanitaria(Rows.uuid(r,"id"),null,Rows.uuid(r,"jornada_id"),Rows.uuid(r,"plan_item_id"),Rows.uuid(r,"animal_id"),Rows.uuid(r,"producto_id"),Rows.uuid(r,"lote_producto_id"),r.getBigDecimal("dosis"),r.getString("unidad_dosis"),r.getString("via_administracion"),r.getString("fecha_aplicacion")==null?null:LocalDate.parse(r.getString("fecha_aplicacion")),r.getString("proxima_aplicacion")==null?null:LocalDate.parse(r.getString("proxima_aplicacion")),r.getString("retiro_carne_hasta")==null?null:LocalDate.parse(r.getString("retiro_carne_hasta")),r.getString("retiro_leche_hasta")==null?null:LocalDate.parse(r.getString("retiro_leche_hasta")),Rows.uuid(r,"aplicado_por"),r.getString("resultado"),r.getString("observaciones"),r.getString("idempotency_key"),r.getString("estado"),r.getLong("version"));}
}
