package bo.com.ganadero.sanidad.infrastructure;import bo.com.ganadero.sanidad.domain.*;import bo.com.ganadero.shared.db.Rows;import bo.com.ganadero.shared.error.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.*;import java.util.*;
@Repository public class JdbcClinicaRepository implements ClinicaRepository{private final JdbcClient j;public JdbcClinicaRepository(JdbcClient j){this.j=j;}
public CasoClinico crearCaso(CasoClinico c,UUID a){j.sql("insert into caso_clinico(id,animal_id,fecha_inicio,sintomas,enfermedad_id,diagnostico_texto,severidad,estado,veterinario_id,observaciones,created_by,updated_by) values(:id,:an,:f,:s,:enf,:d,:sev,:est,:v,:o,:a,:a)").param("id",c.id().toString()).param("an",c.animalId().toString()).param("f",str(c.fechaInicio())).param("s",c.sintomas()).param("enf",c.enfermedadId()==null?null:c.enfermedadId().toString()).param("d",c.diagnosticoTexto()).param("sev",c.severidad().name()).param("est",c.estado().name()).param("v",c.veterinarioId()==null?null:c.veterinarioId().toString()).param("o",c.observaciones()).param("a",a.toString()).update();return caso(c.id(),c.empresaId()).orElseThrow();}
public Optional<CasoClinico>caso(UUID id,UUID e){return j.sql("select * from caso_clinico where id=:id").param("id",id.toString()).query(this::mc).optional();}
public List<CasoClinico>casos(UUID e,UUID a){String sql="select * from caso_clinico"+(a==null?"":" where animal_id=:a")+" order by fecha_inicio desc";var q=j.sql(sql);if(a!=null)q=q.param("a",a.toString());return q.query(this::mc).list();}
public void estadoCaso(UUID id,UUID e,EstadoCasoClinico s,Instant f,String r,UUID a){j.sql("update caso_clinico set estado=:s,fecha_cierre=:f,resultado=:r,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id").param("s",s.name()).param("f",str(f)).param("r",r).param("a",a.toString()).param("id",id.toString()).update();}
public Tratamiento crearTratamiento(Tratamiento t,UUID a){j.sql("insert into tratamiento(id,caso_clinico_id,animal_id,fecha_inicio,fecha_fin_estimada,diagnostico,veterinario_id,estado,observaciones,created_by,updated_by) values(:id,:c,:an,:ini,:fin,:d,:v,:s,:o,:a,:a)").param("id",t.id().toString()).param("c",t.casoClinicoId()==null?null:t.casoClinicoId().toString()).param("an",t.animalId().toString()).param("ini",str(t.fechaInicio())).param("fin",str(t.fechaFinEstimada())).param("d",t.diagnostico()).param("v",t.veterinarioId()==null?null:t.veterinarioId().toString()).param("s",t.estado().name()).param("o",t.observaciones()).param("a",a.toString()).update();return tratamiento(t.id(),t.empresaId()).orElseThrow();}
public Optional<Tratamiento>tratamiento(UUID id,UUID e){return j.sql("select * from tratamiento where id=:id").param("id",id.toString()).query(this::mt).optional();}
public List<Tratamiento>tratamientos(UUID e,UUID a){String sql="select * from tratamiento"+(a==null?"":" where animal_id=:a")+" order by fecha_inicio desc";var q=j.sql(sql);if(a!=null)q=q.param("a",a.toString());return q.query(this::mt).list();}
public TratamientoDetalle crearDetalle(TratamientoDetalle d){j.sql("insert into tratamiento_detalle(id,tratamiento_id,producto_id,lote_producto_id,dosis,unidad_dosis,frecuencia_horas,duracion_dias,via_administracion,retiro_carne_dias,retiro_leche_dias) values(:id,:t,:p,:lp,:d,:u,:f,:dur,:v,:rc,:rl)").param("id",d.id().toString()).param("t",d.tratamientoId().toString()).param("p",d.productoId()==null?null:d.productoId().toString()).param("lp",d.loteProductoId()==null?null:d.loteProductoId().toString()).param("d",d.dosis()).param("u",d.unidadDosis()).param("f",d.frecuenciaHoras()).param("dur",d.duracionDias()).param("v",d.viaAdministracion()).param("rc",d.retiroCarneDias()).param("rl",d.retiroLecheDias()).update();return d;}
public List<TratamientoDetalle>detalles(UUID t,UUID e){return j.sql("select * from tratamiento_detalle where tratamiento_id=:t").param("t",t.toString()).query(this::md).list();}
public AplicacionTratamiento crearAplicacion(AplicacionTratamiento a){j.sql("insert into aplicacion_tratamiento(id,tratamiento_detalle_id,fecha_programada,dosis_programada,estado) values(:id,:d,:f,:dp,:s) on conflict do nothing").param("id",a.id().toString()).param("d",a.tratamientoDetalleId().toString()).param("f",str(a.fechaProgramada())).param("dp",a.dosisProgramada()).param("s",a.estado().name()).update();return a;}
public List<AplicacionTratamiento>aplicaciones(UUID t,UUID e){return j.sql("select a.* from aplicacion_tratamiento a join tratamiento_detalle d on d.id=a.tratamiento_detalle_id where d.tratamiento_id=:t order by fecha_programada").param("t",t.toString()).query(this::ma).list();}
public Optional<AplicacionTratamiento>aplicacion(UUID id,UUID t,UUID e){return aplicaciones(t,e).stream().filter(a->a.id().equals(id)).findFirst();}
public void activar(UUID id,UUID e,UUID a){j.sql("update tratamiento set estado='ACTIVO',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and estado in('BORRADOR','SUSPENDIDO')").param("a",a.toString()).param("id",id.toString()).update();}
public void cancelarFuturas(UUID t,UUID e){j.sql("update aplicacion_tratamiento set estado='CANCELADA',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where tratamiento_detalle_id in (select id from tratamiento_detalle where tratamiento_id=:t) and estado in('PENDIENTE','ATRASADA')").param("t",t.toString()).update();}
public AplicacionTratamiento aplicar(UUID id,UUID t,UUID e,Instant f,java.math.BigDecimal d,UUID actor,String o,long v){int n=j.sql("update aplicacion_tratamiento set estado='APLICADA',fecha_aplicada=:f,dosis_aplicada=:d,aplicado_por=:a,observaciones=:o,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where id=:id and tratamiento_detalle_id in (select id from tratamiento_detalle where tratamiento_id=:t) and estado in('PENDIENTE','ATRASADA') and version=:v").param("f",str(f)).param("d",d).param("a",actor.toString()).param("o",o).param("id",id.toString()).param("t",t.toString()).param("v",v).update();if(n==0)throw new BusinessException(ErrorCode.VERSION_CONFLICT);return aplicacion(id,t,e).orElseThrow();}
public List<AplicacionTratamiento> marcarAtrasadas(UUID e,Instant now){List<AplicacionTratamiento> pendientes=j.sql("select * from aplicacion_tratamiento where estado='PENDIENTE' and fecha_programada<:n").param("n",str(now)).query(this::ma).list();if(!pendientes.isEmpty())j.sql("update aplicacion_tratamiento set estado='ATRASADA',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where estado='PENDIENTE' and fecha_programada<:n").param("n",str(now)).update();return pendientes.stream().map(a->new AplicacionTratamiento(a.id(),a.empresaId(),a.tratamientoDetalleId(),a.fechaProgramada(),a.fechaAplicada(),a.dosisProgramada(),a.dosisAplicada(),a.aplicadoPor(),EstadoAplicacionTratamiento.ATRASADA,a.observaciones(),a.version()+1)).toList();}
public void finalizar(UUID id,UUID e,UUID a){j.sql("update tratamiento set estado='FINALIZADO',fecha_fin_real=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:a,version=version+1 where id=:id and estado='ACTIVO'").param("a",a.toString()).param("id",id.toString()).update();}
private CasoClinico mc(ResultSet r,int n)throws SQLException{return new CasoClinico(Rows.uuid(r,"id"),null,Rows.uuid(r,"animal_id"),Rows.instant(r,"fecha_inicio"),r.getString("sintomas"),Rows.uuid(r,"enfermedad_id"),r.getString("diagnostico_texto"),SeveridadCaso.valueOf(r.getString("severidad")),EstadoCasoClinico.valueOf(r.getString("estado")),Rows.uuid(r,"veterinario_id"),Rows.instant(r,"fecha_cierre"),r.getString("resultado"),r.getString("observaciones"),r.getLong("version"));}
private Tratamiento mt(ResultSet r,int n)throws SQLException{return new Tratamiento(Rows.uuid(r,"id"),null,Rows.uuid(r,"caso_clinico_id"),Rows.uuid(r,"animal_id"),Rows.instant(r,"fecha_inicio"),Rows.instant(r,"fecha_fin_estimada"),Rows.instant(r,"fecha_fin_real"),r.getString("diagnostico"),Rows.uuid(r,"veterinario_id"),EstadoTratamiento.valueOf(r.getString("estado")),r.getString("observaciones"),r.getLong("version"));}
private TratamientoDetalle md(ResultSet r,int n)throws SQLException{return new TratamientoDetalle(Rows.uuid(r,"id"),null,Rows.uuid(r,"tratamiento_id"),Rows.uuid(r,"producto_id"),Rows.uuid(r,"lote_producto_id"),r.getBigDecimal("dosis"),r.getString("unidad_dosis"),r.getInt("frecuencia_horas"),r.getInt("duracion_dias"),r.getString("via_administracion"),r.getInt("retiro_carne_dias"),r.getInt("retiro_leche_dias"));}
private AplicacionTratamiento ma(ResultSet r,int n)throws SQLException{return new AplicacionTratamiento(Rows.uuid(r,"id"),null,Rows.uuid(r,"tratamiento_detalle_id"),Rows.instant(r,"fecha_programada"),Rows.instant(r,"fecha_aplicada"),r.getBigDecimal("dosis_programada"),r.getBigDecimal("dosis_aplicada"),Rows.uuid(r,"aplicado_por"),EstadoAplicacionTratamiento.valueOf(r.getString("estado")),r.getString("observaciones"),r.getLong("version"));}
private static String str(Instant i){return i==null?null:i.toString();}
}
