package bo.com.ganadero.propiedades.application;
import bo.com.ganadero.propiedades.domain.*; import bo.com.ganadero.shared.codigos.*; import bo.com.ganadero.shared.error.*; import bo.com.ganadero.shared.security.*;
import org.springframework.context.ApplicationEventPublisher; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.Instant; import java.util.*;
@Service public class PropiedadService {
 private final PropiedadRepository propiedades; private final SectorRepository sectores; private final UserContext context; private final ApplicationEventPublisher events; private final CodigoService codigos;
 public PropiedadService(PropiedadRepository p,SectorRepository s,UserContext c,ApplicationEventPublisher e,CodigoService codes){propiedades=p;sectores=s;context=c;events=e;codigos=codes;}
 @Transactional(readOnly=true) public List<Propiedad> list(){CurrentUser u=context.requirePermission("PROPIEDAD_VER");if(!u.accesoTodasPropiedades()&&u.propiedadesPermitidas().isEmpty())return List.of();return propiedades.findAll(u.empresaId(),u.propiedadesPermitidas());}
 @Transactional(readOnly=true) public Propiedad get(UUID id){CurrentUser u=context.requirePermission("PROPIEDAD_VER");context.requirePropertyAccess(u,id);return require(id,u.empresaId());}
 @Transactional public Propiedad create(PropiedadCommand c){CurrentUser u=context.requirePermission("PROPIEDAD_CREAR");String codigo=codigos.paraCreacion(u,TipoCodigo.PROPIEDAD,null,null,c.codigo());Propiedad p=new Propiedad(UUID.randomUUID(),u.empresaId(),codigo,c.nombre(),c.descripcion(),c.departamento(),c.municipio(),c.localidad(),c.direccionReferencia(),c.superficieHa(),c.ubicacionWkt(),c.limiteGeograficoWkt(),true,0);Propiedad saved=propiedades.create(p,u.userId());audit(u,"CREAR","PROPIEDAD",saved.id());return saved;}
 @Transactional public Propiedad update(UUID id,PropiedadCommand c){CurrentUser u=context.requirePermission("PROPIEDAD_EDITAR");context.requirePropertyAccess(u,id);Propiedad old=require(id,u.empresaId());boolean active=c.activo()==null?old.activo():c.activo();if(old.activo()&&!active&&propiedades.hasActiveAnimals(id,u.empresaId()))throw new BusinessException(ErrorCode.PROPERTY_HAS_ACTIVE_ANIMALS);String codigo=codigos.paraActualizacion(u,TipoCodigo.PROPIEDAD,null,null,old.codigo(),c.codigo());Propiedad p=new Propiedad(id,u.empresaId(),codigo,c.nombre(),c.descripcion(),c.departamento(),c.municipio(),c.localidad(),c.direccionReferencia(),c.superficieHa(),c.ubicacionWkt(),c.limiteGeograficoWkt(),active,Objects.requireNonNull(c.version()));Propiedad saved=propiedades.update(p,u.userId());audit(u,"ACTUALIZAR","PROPIEDAD",id);return saved;}
 @Transactional(readOnly=true) public List<Sector> sectors(UUID property){CurrentUser u=context.requirePermission("PROPIEDAD_VER");context.requirePropertyAccess(u,property);require(property,u.empresaId());return sectores.findAll(property,u.empresaId());}
 @Transactional public Sector createSector(UUID property,SectorCommand c){CurrentUser u=context.requirePermission("PROPIEDAD_CREAR");context.requirePropertyAccess(u,property);require(property,u.empresaId());String codigo=codigos.paraCreacion(u,TipoCodigo.SECTOR,property,null,c.codigo());Sector saved=sectores.create(new Sector(UUID.randomUUID(),u.empresaId(),property,codigo,c.nombre(),c.descripcion(),true,0),u.userId());audit(u,"CREAR","SECTOR",saved.id());return saved;}
 @Transactional public Sector updateSector(UUID id,SectorCommand c){CurrentUser u=context.requirePermission("PROPIEDAD_EDITAR");Sector old=sectores.findSectorById(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SECTOR_NOT_FOUND));context.requirePropertyAccess(u,old.propiedadId());String codigo=codigos.paraActualizacion(u,TipoCodigo.SECTOR,old.propiedadId(),null,old.codigo(),c.codigo());Sector saved=sectores.update(new Sector(id,u.empresaId(),old.propiedadId(),codigo,c.nombre(),c.descripcion(),c.activo()==null?old.activo():c.activo(),Objects.requireNonNull(c.version())),u.userId());audit(u,"ACTUALIZAR","SECTOR",id);return saved;}
 private Propiedad require(UUID id,UUID empresa){return propiedades.findById(id,empresa).orElseThrow(()->new BusinessException(ErrorCode.PROPERTY_NOT_FOUND));}
 private void audit(CurrentUser u,String a,String e,UUID id){events.publishEvent(new CampoAuditEvent(u.empresaId(),u.userId(),a,e,id,Instant.now()));}
}
