package bo.com.ganadero.sanidad.application;

import bo.com.ganadero.alertas.application.*;import bo.com.ganadero.animales.domain.*;import bo.com.ganadero.sanidad.domain.*;import bo.com.ganadero.shared.error.*;import bo.com.ganadero.shared.security.*;import bo.com.ganadero.timeline.application.*;import bo.com.ganadero.timeline.domain.TipoEventoAnimal;import org.springframework.beans.factory.ObjectProvider;import org.springframework.context.ApplicationEventPublisher;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.*;import java.util.*;

@Service public class ClinicaService{
 private static final Duration ANTICIPACION=Duration.ofMinutes(30);private final ClinicaRepository repo;private final AnimalRepository animales;private final UserContext context;private final ObjectProvider<ProductoSanitarioPort> productos;private final ObjectProvider<MotorAlertas>alertas;private final TimelineEventPublisher timeline;private final ApplicationEventPublisher events;
 public ClinicaService(ClinicaRepository r,AnimalRepository a,UserContext c,ObjectProvider<ProductoSanitarioPort> p,ObjectProvider<MotorAlertas> al,TimelineEventPublisher t,ApplicationEventPublisher e){repo=r;animales=a;context=c;productos=p;alertas=al;timeline=t;events=e;}
 @Transactional public CasoClinico crearCaso(CrearCasoClinicoCommand c){CurrentUser u=context.requirePermission("SANIDAD_CASO_CREAR");Animal a=animal(u,c.animalId());activo(a);CasoClinico caso=repo.crearCaso(new CasoClinico(UUID.randomUUID(),u.empresaId(),a.id(),c.fechaInicio(),c.sintomas(),c.enfermedadId(),c.diagnosticoTexto(),c.severidad(),EstadoCasoClinico.ABIERTO,c.veterinarioId(),null,null,c.observaciones(),0),u.userId());timeline(u,a.id(),TipoEventoAnimal.CASO_CLINICO_ABIERTO,caso.id(),"Caso clinico "+c.severidad());audit(u,"CREAR_CASO_CLINICO","CASO_CLINICO",caso.id());if(c.severidad()==SeveridadCaso.CRITICA)alertaInmediata(u,a.id(),TipoAlerta.CASO_CLINICO_CRITICO,"CASO_CLINICO",caso.id());return caso;}
 @Transactional(readOnly=true)public List<CasoClinico> casos(UUID animalId){CurrentUser u=context.requirePermission("SANIDAD_VER");if(animalId!=null)animal(u,animalId);return repo.casos(u.empresaId(),animalId);}
 @Transactional public CasoClinico cerrarCaso(UUID id,String resultado){CurrentUser u=context.requirePermission("SANIDAD_CASO_CREAR");CasoClinico c=caso(u,id);repo.estadoCaso(id,u.empresaId(),EstadoCasoClinico.CERRADO,Instant.now(),resultado,u.userId());timeline(u,c.animalId(),TipoEventoAnimal.CASO_CLINICO_CERRADO,id,resultado);resolver(u,"CASO_CLINICO",id);audit(u,"CERRAR_CASO_CLINICO","CASO_CLINICO",id);return caso(u,id);}
 @Transactional public Tratamiento crearTratamiento(CrearTratamientoCommand c){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Animal a=animal(u,c.animalId());activo(a);if(c.fechaFinEstimada().isBefore(c.fechaInicio())||c.detalles()==null||c.detalles().isEmpty())throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_SIN_DETALLES);if(c.casoClinicoId()!=null&& !caso(u,c.casoClinicoId()).animalId().equals(a.id()))throw new BusinessException(ErrorCode.SANIDAD_CASO_NOT_FOUND);Tratamiento t=repo.crearTratamiento(new Tratamiento(UUID.randomUUID(),u.empresaId(),c.casoClinicoId(),a.id(),c.fechaInicio(),c.fechaFinEstimada(),null,c.diagnostico(),c.veterinarioId(),EstadoTratamiento.BORRADOR,c.observaciones(),0),u.userId());for(var d:c.detalles()){ProductoSanitarioPort.ProductoSanitarioInfo info=producto(u,d.productoId());int rc=info==null?nvl(d.retiroCarneDias()):info.retiroCarneDias(),rl=info==null?nvl(d.retiroLecheDias()):info.retiroLecheDias();repo.crearDetalle(new TratamientoDetalle(UUID.randomUUID(),u.empresaId(),t.id(),d.productoId(),d.loteProductoId(),d.dosis(),d.unidadDosis(),d.frecuenciaHoras(),d.duracionDias(),d.viaAdministracion(),rc,rl));}audit(u,"CREAR_TRATAMIENTO","TRATAMIENTO",t.id());return t;}
 @Transactional(readOnly=true)public List<Tratamiento> tratamientos(UUID animalId){CurrentUser u=context.requirePermission("SANIDAD_VER");return repo.tratamientos(u.empresaId(),animalId);}
 @Transactional(readOnly=true)public List<AplicacionTratamiento> aplicaciones(UUID id){CurrentUser u=context.requirePermission("SANIDAD_VER");tratamiento(u,id);return repo.aplicaciones(id,u.empresaId());}
 @Transactional public List<AplicacionTratamiento> activar(UUID id){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Tratamiento t=tratamiento(u,id);if(t.estado()!=EstadoTratamiento.BORRADOR&&t.estado()!=EstadoTratamiento.SUSPENDIDO)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_ESTADO_INVALIDO);generar(u,t);repo.activar(id,u.empresaId(),u.userId());if(t.casoClinicoId()!=null)repo.estadoCaso(t.casoClinicoId(),u.empresaId(),EstadoCasoClinico.EN_TRATAMIENTO,null,null,u.userId());timeline(u,t.animalId(),TipoEventoAnimal.TRATAMIENTO_INICIADO,id,"Tratamiento iniciado");audit(u,"ACTIVAR_TRATAMIENTO","TRATAMIENTO",id);return repo.aplicaciones(id,u.empresaId());}
 @Transactional public List<AplicacionTratamiento> regenerar(UUID id){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Tratamiento t=tratamiento(u,id);if(t.estado()!=EstadoTratamiento.ACTIVO)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_ESTADO_INVALIDO);for(AplicacionTratamiento a:repo.aplicaciones(id,u.empresaId()))if(a.estado()==EstadoAplicacionTratamiento.PENDIENTE||a.estado()==EstadoAplicacionTratamiento.ATRASADA)cancelar(u,a.id());repo.cancelarFuturas(id,u.empresaId());generar(u,t);audit(u,"REGENERAR_TRATAMIENTO","TRATAMIENTO",id);return repo.aplicaciones(id,u.empresaId());}
 @Transactional public AplicacionTratamiento aplicar(UUID tid,UUID aid,AplicarTratamientoCommand c){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_APLICAR");Tratamiento t=tratamiento(u,tid);if(t.estado()!=EstadoTratamiento.ACTIVO)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_ESTADO_INVALIDO);repo.aplicacion(aid,tid,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_APLICACION_NOT_FOUND));AplicacionTratamiento a=repo.aplicar(aid,tid,u.empresaId(),Instant.now(),c.dosisAplicada(),u.userId(),c.observaciones(),c.version());timeline(u,t.animalId(),TipoEventoAnimal.TRATAMIENTO_APLICADO,aid,"Aplicacion de tratamiento registrada");resolver(u,"APLICACION_TRATAMIENTO",aid);audit(u,"APLICAR_TRATAMIENTO","APLICACION_TRATAMIENTO",aid);return a;}
 @Transactional public List<AplicacionTratamiento> marcarAtrasadas(){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_APLICAR");List<AplicacionTratamiento> out=repo.marcarAtrasadas(u.empresaId(),Instant.now());for(AplicacionTratamiento a:out){Tratamiento t=tratamientoPorDetalle(u,a.tratamientoDetalleId());Animal animal=animal(u,t.animalId());Map<String,Object>metadata=new HashMap<>();metadata.put("animalCodigo",animal.codigo());if(animal.nombre()!=null&&!animal.nombre().isBlank())metadata.put("animalNombre",animal.nombre());MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.crearInmediata(new ProgramarAlertaCommand(u.empresaId(),t.animalId(),TipoAlerta.TRATAMIENTO_ATRASADO,Instant.now(),"APLICACION_TRATAMIENTO",a.id(),metadata));}return out;}
 @Transactional public Tratamiento finalizar(UUID id){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Tratamiento t=tratamiento(u,id);List<AplicacionTratamiento>aplicaciones=repo.aplicaciones(id,u.empresaId());boolean incompleto=aplicaciones.stream().anyMatch(a->a.estado()==EstadoAplicacionTratamiento.PENDIENTE||a.estado()==EstadoAplicacionTratamiento.ATRASADA);if(incompleto)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_INCOMPLETO);repo.finalizar(id,u.empresaId(),u.userId());for(AplicacionTratamiento a:aplicaciones)resolver(u,"APLICACION_TRATAMIENTO",a.id());if(t.casoClinicoId()!=null)repo.estadoCaso(t.casoClinicoId(),u.empresaId(),EstadoCasoClinico.EN_OBSERVACION,null,null,u.userId());timeline(u,t.animalId(),TipoEventoAnimal.TRATAMIENTO_FINALIZADO,id,"Tratamiento finalizado");audit(u,"FINALIZAR_TRATAMIENTO","TRATAMIENTO",id);return tratamiento(u,id);}
 private void generar(CurrentUser u,Tratamiento t){List<TratamientoDetalle> ds=repo.detalles(t.id(),u.empresaId());if(ds.isEmpty())throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_SIN_DETALLES);for(TratamientoDetalle d:ds){Instant limite=t.fechaInicio().plus(Duration.ofDays(d.duracionDias()));for(Instant f=t.fechaInicio();f.isBefore(limite);f=f.plus(Duration.ofHours(d.frecuenciaHoras()))){Instant programada=f;if(repo.aplicaciones(t.id(),u.empresaId()).stream().anyMatch(x->x.tratamientoDetalleId().equals(d.id())&&x.fechaProgramada().equals(programada)&&x.estado()!=EstadoAplicacionTratamiento.CANCELADA))continue;AplicacionTratamiento a=repo.crearAplicacion(new AplicacionTratamiento(UUID.randomUUID(),u.empresaId(),d.id(),programada,null,d.dosis(),null,null,EstadoAplicacionTratamiento.PENDIENTE,null,0));MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),t.animalId(),TipoAlerta.TRATAMIENTO_PROXIMO,programada.minus(ANTICIPACION),"APLICACION_TRATAMIENTO",a.id(),Map.of("fechaAplicacion",programada.toString())));}}}
 private Tratamiento tratamientoPorDetalle(CurrentUser u,UUID detalle){return repo.tratamientos(u.empresaId(),null).stream().filter(t->repo.detalles(t.id(),u.empresaId()).stream().anyMatch(d->d.id().equals(detalle))).findFirst().orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_NOT_FOUND));}private Tratamiento tratamiento(CurrentUser u,UUID id){return repo.tratamiento(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_NOT_FOUND));}private CasoClinico caso(CurrentUser u,UUID id){return repo.caso(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_CASO_NOT_FOUND));}private Animal animal(CurrentUser u,UUID id){return animales.findById(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.ANIMAL_NOT_FOUND));}private void activo(Animal a){if(a.estado()!=EstadoAnimal.ACTIVO)throw new BusinessException(ErrorCode.ANIMAL_NOT_ACTIVE);}private int nvl(Integer i){return i==null?0:i;}private ProductoSanitarioPort.ProductoSanitarioInfo producto(CurrentUser u,UUID id){if(id==null)return null;ProductoSanitarioPort p=productos.getIfAvailable();if(p==null)return null;if(!p.existeYEstaActivo(u.empresaId(),id))throw new BusinessException(ErrorCode.SANIDAD_PRODUCTO_INVALIDO);return p.informacion(u.empresaId(),id);}private void cancelar(CurrentUser u,UUID id){MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.cancelarPorOrigen(u.empresaId(),"APLICACION_TRATAMIENTO",id,"CALENDARIO_REGENERADO");}private void resolver(CurrentUser u,String tipo,UUID id){MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.resolverPorOrigen(u.empresaId(),tipo,id);}private void alertaInmediata(CurrentUser u,UUID animal,TipoAlerta tipo,String origen,UUID id){MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.crearInmediata(new ProgramarAlertaCommand(u.empresaId(),animal,tipo,Instant.now(),origen,id,Map.of()));}private void timeline(CurrentUser u,UUID animal,TipoEventoAnimal tipo,UUID origen,String descripcion){timeline.publish(new RegistrarEventoTimeline(u.empresaId(),animal,tipo,null,descripcion,null,origen,Map.of(),u.userId(),Instant.now(),null));}private void audit(CurrentUser u,String accion,String entidad,UUID id){events.publishEvent(new SanidadAuditEvent(u.empresaId(),u.userId(),accion,entidad,id,Instant.now()));}
}
