package bo.com.ganadero.sanidad.application;

import bo.com.ganadero.alertas.application.*;import bo.com.ganadero.animales.domain.*;import bo.com.ganadero.sanidad.domain.*;import bo.com.ganadero.shared.error.*;import bo.com.ganadero.shared.security.*;import bo.com.ganadero.timeline.application.*;import bo.com.ganadero.timeline.domain.TipoEventoAnimal;import org.springframework.beans.factory.ObjectProvider;import org.springframework.context.ApplicationEventPublisher;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.*;import java.util.*;

@Service public class ClinicaService{
 private final ConfiguracionSanitariaService configuracion;private static final Duration ANTICIPACION=Duration.ofMinutes(30);private final ClinicaRepository repo;private final AnimalRepository animales;private final UserContext context;private final SanidadRepository planes;private final EventoCalendarioSanitarioRepository eventos;private final ObjectProvider<MotorAlertas>alertas;private final TimelineEventPublisher timeline;private final ApplicationEventPublisher events;
 public ClinicaService(ClinicaRepository r,AnimalRepository a,UserContext c,SanidadRepository planes,EventoCalendarioSanitarioRepository eventos,ObjectProvider<MotorAlertas> al,TimelineEventPublisher t,ApplicationEventPublisher e,ConfiguracionSanitariaService configuracion){this.configuracion=configuracion;repo=r;animales=a;context=c;this.planes=planes;this.eventos=eventos;alertas=al;timeline=t;events=e;}
 @Transactional public CasoClinico crearCaso(CrearCasoClinicoCommand c){CurrentUser u=context.requirePermission("SANIDAD_CASO_CREAR");Animal a=animal(u,c.animalId());activo(a);ReglasSanitarias.fechaAnimal(a,c.fechaInicio());RestriccionMovimiento restriccion=c.restriccionMovimiento()!=null?c.restriccionMovimiento():restriccionPorDefecto(c.severidad());CasoClinico caso=repo.crearCaso(new CasoClinico(UUID.randomUUID(),u.empresaId(),a.id(),c.fechaInicio(),c.sintomas(),c.enfermedadId(),c.diagnosticoTexto(),c.severidad(),EstadoCasoClinico.ABIERTO,c.veterinarioId(),null,null,c.observaciones(),0,restriccion),u.userId());timeline(u,a.id(),TipoEventoAnimal.CASO_CLINICO_ABIERTO,caso.id(),"Caso clinico "+c.severidad());audit(u,"CREAR_CASO_CLINICO","CASO_CLINICO",caso.id());if(c.severidad()==SeveridadCaso.CRITICA)alertaInmediata(u,a.id(),TipoAlerta.CASO_CLINICO_CRITICO,"CASO_CLINICO",caso.id());verificarHallazgo(u,"CASO_CLINICO","CASO_CLINICO_ABIERTO",caso.id(),a.id(),c.severidad());return caso;}
 /** Criterio por defecto cuando el veterinario no fija explícitamente restriccionMovimiento al crear el caso. */
 private RestriccionMovimiento restriccionPorDefecto(SeveridadCaso severidad){return switch(severidad){case CRITICA->RestriccionMovimiento.BLOQUEANTE;case GRAVE->RestriccionMovimiento.ADVERTENCIA;default->RestriccionMovimiento.INFORMATIVA;};}
 @Transactional(readOnly=true)public List<CasoClinico> casos(UUID animalId){CurrentUser u=context.requirePermission("SANIDAD_VER");if(animalId!=null)animal(u,animalId);return repo.casos(u.empresaId(),animalId);}
 @Transactional public CasoClinico cerrarCaso(UUID id,String resultado){CurrentUser u=context.requirePermission("SANIDAD_CASO_CREAR");CasoClinico c=caso(u,id);ReglasSanitarias.exigir(c.estado()!=EstadoCasoClinico.CERRADO&&c.estado()!=EstadoCasoClinico.ANULADO,"El caso ya está cerrado o anulado.");ReglasSanitarias.exigir(repo.tratamientos(u.empresaId(),c.animalId()).stream().noneMatch(t->id.equals(t.casoClinicoId())&&(t.estado()==EstadoTratamiento.ACTIVO||t.estado()==EstadoTratamiento.SUSPENDIDO)),"Finalice los tratamientos del caso antes de cerrarlo.");repo.estadoCaso(id,u.empresaId(),EstadoCasoClinico.CERRADO,Instant.now(),resultado,u.userId());timeline(u,c.animalId(),TipoEventoAnimal.CASO_CLINICO_CERRADO,id,resultado);resolver(u,"CASO_CLINICO",id);audit(u,"CERRAR_CASO_CLINICO","CASO_CLINICO",id);return caso(u,id);}
 @Transactional public Tratamiento crearTratamiento(CrearTratamientoCommand c){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Animal a=animal(u,c.animalId());activo(a);ReglasSanitarias.fechaAnimal(a,c.fechaInicio());if(c.fechaFinEstimada().isBefore(c.fechaInicio())||c.detalles()==null||c.detalles().isEmpty())throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_SIN_DETALLES);LocalDate ultimaDosis=ultimaDosisProgramada(c.fechaInicio(),c.detalles());ReglasSanitarias.exigir(!c.fechaFinEstimada().atZone(ReglasSanitarias.ZONA).toLocalDate().isBefore(ultimaDosis),"La fecha fin estimada es anterior a la última dosis programada ("+ultimaDosis+").");if(c.casoClinicoId()!=null&& !caso(u,c.casoClinicoId()).animalId().equals(a.id()))throw new BusinessException(ErrorCode.SANIDAD_CASO_NOT_FOUND);if(c.casoClinicoId()!=null){CasoClinico caso=caso(u,c.casoClinicoId());ReglasSanitarias.exigir(!c.fechaInicio().isBefore(caso.fechaInicio()),"El tratamiento no puede comenzar antes del caso clínico.");ReglasSanitarias.exigir(caso.estado()!=EstadoCasoClinico.CERRADO&&caso.estado()!=EstadoCasoClinico.ANULADO,"No puede asociar un tratamiento a un caso cerrado o anulado.");}RestriccionMovimiento restriccion=c.restriccionMovimiento()!=null?c.restriccionMovimiento():RestriccionMovimiento.ADVERTENCIA;Tratamiento t=repo.crearTratamiento(new Tratamiento(UUID.randomUUID(),u.empresaId(),c.casoClinicoId(),a.id(),c.fechaInicio(),c.fechaFinEstimada(),null,c.diagnostico(),c.veterinarioId(),EstadoTratamiento.BORRADOR,c.observaciones(),0,restriccion),u.userId());for(var d:c.detalles()){int rc=nvl(d.retiroCarneDias()),rl=nvl(d.retiroLecheDias());repo.crearDetalle(new TratamientoDetalle(UUID.randomUUID(),u.empresaId(),t.id(),d.productoId(),d.loteProductoId(),d.dosis(),d.unidadDosis(),d.frecuenciaHoras(),d.duracionDias(),d.viaAdministracion(),rc,rl,d.productoTexto()));}audit(u,"CREAR_TRATAMIENTO","TRATAMIENTO",t.id());return t;}
 @Transactional(readOnly=true)public List<Tratamiento> tratamientos(UUID animalId){CurrentUser u=context.requirePermission("SANIDAD_VER");return repo.tratamientos(u.empresaId(),animalId);}
 @Transactional(readOnly=true)public List<AplicacionTratamiento> aplicaciones(UUID id){CurrentUser u=context.requirePermission("SANIDAD_VER");tratamiento(u,id);return repo.aplicaciones(id,u.empresaId());}
 @Transactional public List<AplicacionTratamiento> activar(UUID id){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Tratamiento t=tratamiento(u,id);if(t.estado()!=EstadoTratamiento.BORRADOR&&t.estado()!=EstadoTratamiento.SUSPENDIDO)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_ESTADO_INVALIDO);activo(animal(u,t.animalId()));if(t.casoClinicoId()!=null){CasoClinico caso=caso(u,t.casoClinicoId());ReglasSanitarias.exigir(caso.estado()!=EstadoCasoClinico.CERRADO&&caso.estado()!=EstadoCasoClinico.ANULADO,"El caso asociado está cerrado o anulado.");}generar(u,t,t.fechaInicio(),false);repo.activar(id,u.empresaId(),u.userId());if(t.casoClinicoId()!=null)repo.estadoCaso(t.casoClinicoId(),u.empresaId(),EstadoCasoClinico.EN_TRATAMIENTO,null,null,u.userId());timeline(u,t.animalId(),TipoEventoAnimal.TRATAMIENTO_INICIADO,id,"Tratamiento iniciado");audit(u,"ACTIVAR_TRATAMIENTO","TRATAMIENTO",id);return repo.aplicaciones(id,u.empresaId());}
 @Transactional public List<AplicacionTratamiento> regenerar(UUID id){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Tratamiento t=tratamiento(u,id);if(t.estado()!=EstadoTratamiento.ACTIVO)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_ESTADO_INVALIDO);for(AplicacionTratamiento a:repo.aplicaciones(id,u.empresaId()))if(a.estado()==EstadoAplicacionTratamiento.PENDIENTE||a.estado()==EstadoAplicacionTratamiento.ATRASADA)cancelar(u,a.id());repo.cancelarFuturas(id,u.empresaId());Instant ultima=generar(u,t,Instant.now(),true);if(ultima!=null)repo.reprogramarFin(id,u.empresaId(),ultima.atZone(ReglasSanitarias.ZONA).toLocalDate().atStartOfDay(ReglasSanitarias.ZONA).toInstant(),u.userId());audit(u,"REGENERAR_TRATAMIENTO","TRATAMIENTO",id);return repo.aplicaciones(id,u.empresaId());}
 @Transactional public AplicacionTratamiento aplicar(UUID tid,UUID aid,AplicarTratamientoCommand c){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_APLICAR");Tratamiento t=tratamiento(u,tid);if(t.estado()!=EstadoTratamiento.ACTIVO)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_ESTADO_INVALIDO);activo(animal(u,t.animalId()));AplicacionTratamiento pendiente=repo.aplicacion(aid,tid,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_APLICACION_NOT_FOUND));ReglasSanitarias.exigir(!pendiente.fechaProgramada().isAfter(Instant.now()),"Todavía no corresponde aplicar esta dosis según el horario programado.");TratamientoDetalle detalle=repo.detalles(tid,u.empresaId()).stream().filter(d->d.id().equals(pendiente.tratamientoDetalleId())).findFirst().orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_APLICACION_NOT_FOUND));Instant ahora=Instant.now();LocalDate fechaAplicada=ahora.atZone(ReglasSanitarias.ZONA).toLocalDate();LocalDate rc=detalle.retiroCarneDias()>0?fechaAplicada.plusDays(detalle.retiroCarneDias()):null;LocalDate rl=detalle.retiroLecheDias()>0?fechaAplicada.plusDays(detalle.retiroLecheDias()):null;AplicacionTratamiento a=repo.aplicar(aid,tid,u.empresaId(),ahora,c.dosisAplicada(),u.userId(),c.observaciones(),c.version(),rc,rl);timeline(u,t.animalId(),TipoEventoAnimal.TRATAMIENTO_APLICADO,aid,"Aplicacion de tratamiento registrada");resolver(u,"APLICACION_TRATAMIENTO",aid);retiroAlertas(u,t.animalId(),aid,rc,rl);audit(u,"APLICAR_TRATAMIENTO","APLICACION_TRATAMIENTO",aid);return a;}
 private void retiroAlertas(CurrentUser u,UUID animalId,UUID origenId,LocalDate rc,LocalDate rl){MotorAlertas m=alertas.getIfAvailable();if(m==null)return;ZoneId zona=ReglasSanitarias.ZONA;if(rc!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),animalId,TipoAlerta.RETIRO_CARNE_VIGENTE,rc.atStartOfDay(zona).toInstant(),"APLICACION_TRATAMIENTO",origenId,Map.of("tipoRetiro","CARNE","hasta",rc.toString())));if(rl!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),animalId,TipoAlerta.RETIRO_LECHE_VIGENTE,rl.atStartOfDay(zona).toInstant(),"APLICACION_TRATAMIENTO",origenId,Map.of("tipoRetiro","LECHE","hasta",rl.toString())));}
 @Transactional public List<AplicacionTratamiento> marcarAtrasadas(){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_APLICAR");List<AplicacionTratamiento> out=repo.marcarAtrasadas(u.empresaId(),Instant.now());for(AplicacionTratamiento a:out){Tratamiento t=tratamientoPorDetalle(u,a.tratamientoDetalleId());Animal animal=animal(u,t.animalId());Map<String,Object>metadata=new HashMap<>();metadata.put("animalCodigo",animal.codigo());if(animal.nombre()!=null&&!animal.nombre().isBlank())metadata.put("animalNombre",animal.nombre());MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.crearInmediata(new ProgramarAlertaCommand(u.empresaId(),t.animalId(),TipoAlerta.TRATAMIENTO_ATRASADO,Instant.now(),"APLICACION_TRATAMIENTO",a.id(),metadata));}return out;}
 @Transactional public ControlNeonatal crearControl(CrearControlNeonatalCommand c){CurrentUser u=context.requirePermission("SANIDAD_NEONATAL_CREAR");Animal a=animal(u,c.animalId());activo(a);ReglasSanitarias.neonatal(a,c);ControlNeonatal control=repo.crearControl(new ControlNeonatal(UUID.randomUUID(),u.empresaId(),a.id(),c.fechaControl(),c.momento(),c.calostrado(),c.ombligoDesinfectado(),c.ombligoEstado(),c.diarrea(),c.estadoGeneral(),c.lactancia(),c.temperaturaC(),c.observaciones(),0),u.userId());timeline(u,a.id(),TipoEventoAnimal.CONTROL_NEONATAL_REGISTRADO,control.id(),"Control neonatal "+c.momento());audit(u,"CREAR_CONTROL_NEONATAL","CONTROL_NEONATAL",control.id());if(c.calostrado()==EstadoCalostrado.INSUFICIENTE||c.diarrea()){alertaNeonatal(u,a,control,c);verificarHallazgo(u,"CONTROL_NEONATAL","CONTROL_NEONATAL_ALERTA",control.id(),a.id(),null);}return control;}
 @Transactional(readOnly=true)public List<ControlNeonatal> controlesNeonatales(UUID animalId){CurrentUser u=context.requirePermission("SANIDAD_VER");if(animalId!=null)animal(u,animalId);return repo.controles(u.empresaId(),animalId);}
 @Transactional public ControlEctoparasitario crearControlEcto(CrearControlEctoparasitarioCommand c){CurrentUser u=context.requirePermission("SANIDAD_ECTOPARASITARIO_CREAR");destinoValido(c.animalId(),c.loteGanaderoId());ReglasSanitarias.fechaRealizada(c.fecha());UUID animalId=null;if(c.animalId()!=null){Animal a=animal(u,c.animalId());activo(a);ReglasSanitarias.fechaAnimal(a,c.fecha(),false);animalId=a.id();}ControlEctoparasitario control=repo.crearControlEcto(new ControlEctoparasitario(UUID.randomUUID(),u.empresaId(),animalId,c.loteGanaderoId(),c.tipo(),c.nivelCarga(),c.tratado(),c.producto(),c.principioActivo(),c.fecha(),c.observaciones(),0),u.userId());if(animalId!=null)timeline(u,animalId,TipoEventoAnimal.CONTROL_ECTOPARASITARIO_REGISTRADO,control.id(),"Control ectoparasitario "+c.tipo());audit(u,"CREAR_CONTROL_ECTOPARASITARIO","CONTROL_ECTOPARASITARIO",control.id());if(animalId!=null&&c.nivelCarga()==NivelCargaParasitaria.ALTO)verificarHallazgo(u,"CONTROL_ECTOPARASITARIO","CONTROL_ECTOPARASITARIO_POSITIVO",control.id(),animalId,null);return control;}
 @Transactional(readOnly=true)public List<ControlEctoparasitario> controlesEctoparasitarios(UUID animalId,UUID loteGanaderoId){CurrentUser u=context.requirePermission("SANIDAD_VER");if(animalId!=null)animal(u,animalId);return repo.controlesEcto(u.empresaId(),animalId,loteGanaderoId);}
 @Transactional(readOnly=true)public List<String> principiosActivosRecientes(UUID animalId,UUID loteGanaderoId){CurrentUser u=context.requirePermission("SANIDAD_VER");return repo.principiosActivosRecientes(u.empresaId(),animalId,loteGanaderoId,3);}
 private void destinoValido(UUID animalId,UUID loteGanaderoId){if((animalId==null)==(loteGanaderoId==null))throw new BusinessException(ErrorCode.SANIDAD_CONTROL_ECTO_DESTINO_INVALIDO);}
 @Transactional public ExamenReproductivo crearExamen(CrearExamenReproductivoCommand c){CurrentUser u=context.requirePermission("SANIDAD_EXAMEN_REPRODUCTIVO_CREAR");Animal a=animal(u,c.animalId());activo(a);ReglasSanitarias.fechaAnimal(a,c.fecha(),false);validarCamposPorSexo(a,c);configuracion.validarExamen(a,c);List<PruebaReproductiva> pruebas=pruebasValidadas(c.pruebas());ExamenReproductivo examen=repo.crearExamen(new ExamenReproductivo(UUID.randomUUID(),u.empresaId(),a.id(),c.fecha(),c.resultado(),c.veterinarioId(),c.circunferenciaEscrotalCm(),c.motilidadEspermaticaPct(),c.morfologiaPct(),c.libido(),c.capacidadServicio(),c.pesoKg(),c.porcentajePesoAdulto(),c.condicionCorporal(),c.desarrolloReproductivo(),c.observaciones(),0,pruebas),pruebas,u.userId());timeline(u,a.id(),TipoEventoAnimal.EXAMEN_REPRODUCTIVO_REGISTRADO,examen.id(),"Examen reproductivo "+c.resultado());audit(u,"CREAR_EXAMEN_REPRODUCTIVO","EXAMEN_REPRODUCTIVO",examen.id());if(c.resultado()==ResultadoExamenReproductivo.NO_APTO)verificarHallazgo(u,"EXAMEN_REPRODUCTIVO","EXAMEN_REPRODUCTIVO_NO_APTO",examen.id(),a.id(),null);return examen;}
 @Transactional(readOnly=true)public List<ExamenReproductivo> examenesReproductivos(UUID animalId){CurrentUser u=context.requirePermission("SANIDAD_VER");if(animalId!=null)animal(u,animalId);return repo.examenes(u.empresaId(),animalId);}
 private void validarCamposPorSexo(Animal a,CrearExamenReproductivoCommand c){boolean vaquilla=c.pesoKg()!=null||c.porcentajePesoAdulto()!=null||c.condicionCorporal()!=null||(c.desarrolloReproductivo()!=null&&!c.desarrolloReproductivo().isBlank());boolean toro=c.circunferenciaEscrotalCm()!=null||c.motilidadEspermaticaPct()!=null||c.morfologiaPct()!=null||(c.libido()!=null&&!c.libido().isBlank())||(c.capacidadServicio()!=null&&!c.capacidadServicio().isBlank());if(a.sexo()==SexoAnimal.MACHO&&vaquilla)throw new BusinessException(ErrorCode.SANIDAD_EXAMEN_CAMPO_NO_APLICABLE,"Los campos de evaluación de vaquilla no aplican a un animal macho.");if(a.sexo()==SexoAnimal.HEMBRA&&toro)throw new BusinessException(ErrorCode.SANIDAD_EXAMEN_CAMPO_NO_APLICABLE,"Los campos de evaluación de toro no aplican a un animal hembra.");}
 private List<PruebaReproductiva> pruebasValidadas(List<CrearExamenReproductivoCommand.Prueba> pruebas){if(pruebas==null)return List.of();Set<EnfermedadReproductiva> vistas=new HashSet<>();List<PruebaReproductiva> out=new ArrayList<>();for(CrearExamenReproductivoCommand.Prueba p:pruebas){if(!vistas.add(p.enfermedad()))throw new BusinessException(ErrorCode.SANIDAD_EXAMEN_PRUEBA_DUPLICADA,"La enfermedad "+p.enfermedad()+" está repetida en el checklist del examen.");out.add(new PruebaReproductiva(p.enfermedad(),p.resultado()));}return out;}
 @Transactional public Tratamiento finalizar(UUID id){CurrentUser u=context.requirePermission("SANIDAD_TRATAMIENTO_CREAR");Tratamiento t=tratamiento(u,id);ReglasSanitarias.exigir(t.estado()==EstadoTratamiento.ACTIVO,"Solo puede finalizar un tratamiento activo.");List<AplicacionTratamiento>aplicaciones=repo.aplicaciones(id,u.empresaId());boolean incompleto=aplicaciones.stream().anyMatch(a->a.estado()==EstadoAplicacionTratamiento.PENDIENTE||a.estado()==EstadoAplicacionTratamiento.ATRASADA);if(incompleto)throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_INCOMPLETO);repo.finalizar(id,u.empresaId(),u.userId());for(AplicacionTratamiento a:aplicaciones)resolver(u,"APLICACION_TRATAMIENTO",a.id());if(t.casoClinicoId()!=null)repo.estadoCaso(t.casoClinicoId(),u.empresaId(),EstadoCasoClinico.EN_OBSERVACION,null,null,u.userId());timeline(u,t.animalId(),TipoEventoAnimal.TRATAMIENTO_FINALIZADO,id,"Tratamiento finalizado");audit(u,"FINALIZAR_TRATAMIENTO","TRATAMIENTO",id);return tratamiento(u,id);}
 private Instant generar(CurrentUser u,Tratamiento t,Instant ancla,boolean soloRestantes){
  List<TratamientoDetalle> ds=repo.detalles(t.id(),u.empresaId());
  if(ds.isEmpty())throw new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_SIN_DETALLES);
  List<AplicacionTratamiento> existentes=repo.aplicaciones(t.id(),u.empresaId());
  Instant ultima=null;
  for(TratamientoDetalle d:ds){
   int frecuencia=d.frecuenciaHoras()<=0?24:d.frecuenciaHoras();
   int duracion=d.duracionDias();
   int planificadas=(int)Math.ceil((double)duracion*24/frecuencia);
   long aplicadas=existentes.stream().filter(a->a.tratamientoDetalleId().equals(d.id())&&a.estado()==EstadoAplicacionTratamiento.APLICADA).count();
   int aProgramar=soloRestantes?(int)Math.max(0,planificadas-aplicadas):planificadas;
   for(int k=0;k<aProgramar;k++){
    Instant programada=ancla.plus(Duration.ofHours((long)frecuencia*k));
    if(existentes.stream().anyMatch(x->x.tratamientoDetalleId().equals(d.id())&&x.fechaProgramada().equals(programada)&&x.estado()!=EstadoAplicacionTratamiento.CANCELADA))continue;
    AplicacionTratamiento a=repo.crearAplicacion(new AplicacionTratamiento(UUID.randomUUID(),u.empresaId(),d.id(),programada,null,d.dosis(),null,null,EstadoAplicacionTratamiento.PENDIENTE,null,0));
    if(ultima==null||programada.isAfter(ultima))ultima=programada;
    MotorAlertas m=alertas.getIfAvailable();
    if(m!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),t.animalId(),TipoAlerta.TRATAMIENTO_PROXIMO,programada.minus(ANTICIPACION),"APLICACION_TRATAMIENTO",a.id(),Map.of("fechaAplicacion",programada.toString())));
   }
  }
  return ultima;
 }
 private Tratamiento tratamientoPorDetalle(CurrentUser u,UUID detalle){return repo.tratamientos(u.empresaId(),null).stream().filter(t->repo.detalles(t.id(),u.empresaId()).stream().anyMatch(d->d.id().equals(detalle))).findFirst().orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_NOT_FOUND));}private Tratamiento tratamiento(CurrentUser u,UUID id){return repo.tratamiento(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_TRATAMIENTO_NOT_FOUND));}private CasoClinico caso(CurrentUser u,UUID id){return repo.caso(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_CASO_NOT_FOUND));}private Animal animal(CurrentUser u,UUID id){return animales.findById(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.ANIMAL_NOT_FOUND));}private void activo(Animal a){if(a.estado()!=EstadoAnimal.ACTIVO)throw new BusinessException(ErrorCode.ANIMAL_NOT_ACTIVE);}private int nvl(Integer i){return i==null?0:i;}private LocalDate ultimaDosisProgramada(Instant inicio,List<CrearTratamientoCommand.Detalle> ds){LocalDate mayor=inicio.atZone(ReglasSanitarias.ZONA).toLocalDate();if(ds==null)return mayor;for(CrearTratamientoCommand.Detalle d:ds){int duracion=d.duracionDias()==null?0:d.duracionDias();int frecuencia=(d.frecuenciaHoras()==null||d.frecuenciaHoras()<=0)?24:d.frecuenciaHoras();Instant limite=inicio.plus(Duration.ofDays(duracion));Instant ultima=inicio;for(Instant f=inicio;f.isBefore(limite);f=f.plus(Duration.ofHours(frecuencia)))ultima=f;LocalDate fecha=ultima.atZone(ReglasSanitarias.ZONA).toLocalDate();if(fecha.isAfter(mayor))mayor=fecha;}return mayor;}
 /** Sección 13: relaciona un hallazgo con actividades POR_HALLAZGO cuyo catálogo de disparadores lo incluya; evita duplicar un evento pendiente para el mismo hallazgo (índice único en evento_calendario_sanitario). */
 private void verificarHallazgo(CurrentUser u,String origenTipo,String tagHallazgo,UUID origenId,UUID animalId,SeveridadCaso severidad){
  for(PlanSanitario plan:planes.planes(u.empresaId())){
   if(plan.estado()!=EstadoPlanSanitario.ACTIVO)continue;
   for(PlanSanitarioItem item:planes.items(plan.id(),u.empresaId(),false)){
    if(item.modalidad()!=ModalidadActividad.POR_HALLAZGO)continue;
    if(!(item.modalidadConfig() instanceof ModalidadConfig.PorHallazgoConfig cfg))continue;
    if(cfg.tiposHallazgo()==null||!cfg.tiposHallazgo().contains(tagHallazgo))continue;
    if(severidad!=null&&cfg.severidadMinima()!=null&&severidad.ordinal()<SeveridadCaso.valueOf(cfg.severidadMinima()).ordinal())continue;
    Instant ahora=Instant.now();
    Instant plazo=cfg.plazoDias()==null?null:ahora.plus(Duration.ofDays(cfg.plazoDias()));
    eventos.crearSiNoExiste(new EventoCalendarioSanitario(UUID.randomUUID(),u.empresaId(),item.id(),animalId,
     origenTipo+":"+origenId,ahora,ahora,plazo,EstadoEventoCalendario.PROGRAMADO,ModalidadActividad.POR_HALLAZGO,
     origenTipo,origenId,null,null,"NORMAL",ahora,0));
   }
  }
 }
 private void cancelar(CurrentUser u,UUID id){MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.cancelarPorOrigen(u.empresaId(),"APLICACION_TRATAMIENTO",id,"CALENDARIO_REGENERADO");}private void resolver(CurrentUser u,String tipo,UUID id){MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.resolverPorOrigen(u.empresaId(),tipo,id);}private void alertaInmediata(CurrentUser u,UUID animal,TipoAlerta tipo,String origen,UUID id){MotorAlertas m=alertas.getIfAvailable();if(m!=null)m.crearInmediata(new ProgramarAlertaCommand(u.empresaId(),animal,tipo,Instant.now(),origen,id,Map.of()));}
 private void alertaNeonatal(CurrentUser u,Animal a,ControlNeonatal control,CrearControlNeonatalCommand c){MotorAlertas m=alertas.getIfAvailable();if(m==null)return;String motivo=c.calostrado()==EstadoCalostrado.INSUFICIENTE?"con calostrado insuficiente":"con diarrea";Map<String,Object> metadata=new HashMap<>();metadata.put("animalCodigo",a.codigo());if(a.nombre()!=null&&!a.nombre().isBlank())metadata.put("animalNombre",a.nombre());metadata.put("tituloPersonalizado","Control neonatal requiere seguimiento");metadata.put("mensajePersonalizado","Ternero "+a.codigo()+" "+motivo+" — requiere seguimiento inmediato");metadata.put("severidad","URGENTE");m.crearInmediata(new ProgramarAlertaCommand(u.empresaId(),a.id(),TipoAlerta.RECORDATORIO_SANIDAD,Instant.now(),"CONTROL_NEONATAL",control.id(),metadata));}private void timeline(CurrentUser u,UUID animal,TipoEventoAnimal tipo,UUID origen,String descripcion){timeline.publish(new RegistrarEventoTimeline(u.empresaId(),animal,tipo,null,descripcion,null,origen,Map.of(),u.userId(),Instant.now(),null));}private void audit(CurrentUser u,String accion,String entidad,UUID id){events.publishEvent(new SanidadAuditEvent(u.empresaId(),u.userId(),accion,entidad,id,Instant.now()));}
}
