package bo.com.ganadero.sanidad.application;
import bo.com.ganadero.alertas.application.*;import bo.com.ganadero.animales.domain.*;import bo.com.ganadero.sanidad.domain.*;import bo.com.ganadero.shared.error.*;import bo.com.ganadero.shared.security.*;import bo.com.ganadero.timeline.application.*;import bo.com.ganadero.timeline.domain.TipoEventoAnimal;
import org.springframework.beans.factory.ObjectProvider;import org.springframework.context.ApplicationEventPublisher;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.*;import java.util.*;
@Service public class JornadaSanitariaService{
 private final JornadaSanitariaRepository repo;private final SanidadRepository planes;private final AnimalRepository animales;private final UserContext context;private final ObjectProvider<ProductoSanitarioPort> productos;private final ObjectProvider<MotorAlertas>alertas;private final TimelineEventPublisher timeline;private final ApplicationEventPublisher events;
 public JornadaSanitariaService(JornadaSanitariaRepository r,SanidadRepository p,AnimalRepository a,UserContext c,ObjectProvider<ProductoSanitarioPort> prod,ObjectProvider<MotorAlertas> al,TimelineEventPublisher t,ApplicationEventPublisher e){repo=r;planes=p;animales=a;context=c;productos=prod;alertas=al;timeline=t;events=e;}
 @Transactional public JornadaSanitaria crear(CrearJornadaCommand c){CurrentUser u=context.requirePermission("SANIDAD_JORNADA_CREAR");context.requirePropertyAccess(u,c.propiedadId());UUID id=UUID.randomUUID();return repo.crear(new JornadaSanitaria(id,u.empresaId(),c.tipoJornada(),c.fechaInicio(),null,c.propiedadId(),c.potreroId(),c.loteGanaderoId(),c.responsableId(),c.veterinarioId(),EstadoJornada.BORRADOR,c.observaciones(),null,0),u.userId());}
 @Transactional(readOnly=true)public List<JornadaSanitaria>listar(){return repo.listar(context.requirePermission("SANIDAD_VER").empresaId());}
 @Transactional(readOnly=true)public List<Animal>elegibles(UUID propiedad,UUID lote,UUID categoria,SexoAnimal sexo){CurrentUser u=context.requirePermission("SANIDAD_VER");context.requirePropertyAccess(u,propiedad);return animales.findEligible(u.empresaId(),propiedad,lote,categoria,sexo);}
 @Transactional(readOnly=true)public ResultadoElegibilidad elegibilidad(UUID id,UUID planItemId,LocalDate fechaAplicacion){CurrentUser u=context.requirePermission("SANIDAD_VER");JornadaSanitaria j=require(id,u);PlanSanitarioItem item=requireItemCompatible(planItemId,u.empresaId(),j);List<AnimalElegibilidad>resultado=animales.findEligible(u.empresaId(),j.propiedadId(),j.loteGanaderoId(),null,null).stream().filter(a->j.potreroId()==null||j.potreroId().equals(a.potreroActualId())).map(a->evaluar(a,j,item,fechaAplicacion)).toList();return ResultadoElegibilidad.of(resultado);}
 @Transactional public List<UUID>seleccionar(UUID id,UUID planItemId,LocalDate fechaAplicacion,List<UUID>ids){CurrentUser u=context.requirePermission("SANIDAD_JORNADA_CREAR");JornadaSanitaria j=require(id,u);PlanSanitarioItem item=requireItemCompatible(planItemId,u.empresaId(),j);for(UUID animalId:ids){Animal a=animal(u,animalId);AnimalElegibilidad resultado=evaluar(a,j,item,fechaAplicacion);if(!resultado.elegible())throw new BusinessException(ErrorCode.SANIDAD_ANIMAL_NO_ELEGIBLE,a.codigo()+": "+String.join(" ",resultado.motivos()));}repo.reemplazarSeleccion(id,u.empresaId(),ids);return repo.seleccion(id,u.empresaId());}
 @Transactional public ConfirmacionJornadaResult confirmar(UUID id,ConfirmarJornadaCommand c){CurrentUser u=context.requirePermission("SANIDAD_JORNADA_CONFIRMAR");Optional<JornadaSanitaria> previa=repo.buscarPorOperacion(c.operationId(),u.empresaId());if(previa.isPresent()&&previa.get().estado()==EstadoJornada.CONFIRMADA)return new ConfirmacionJornadaResult(previa.get(),repo.aplicaciones(previa.get().id(),u.empresaId()),repo.aplicaciones(previa.get().id(),u.empresaId()).size());JornadaSanitaria j=require(id,u);List<UUID>seleccion=repo.seleccion(id,u.empresaId());if(seleccion.isEmpty())throw new BusinessException(ErrorCode.SANIDAD_JORNADA_SIN_ANIMALES);PlanSanitarioItem item=requireItemCompatible(c.planItemId(),u.empresaId(),j);ProductoSanitarioPort.ProductoSanitarioInfo info=producto(u,c.productoId());repo.iniciarConfirmacion(id,u.empresaId(),c.version(),c.operationId(),u.userId());List<AplicacionSanitaria>out=new ArrayList<>();for(UUID aid:seleccion){Animal a=animal(u,aid);AnimalElegibilidad elegibilidad=evaluar(a,j,item,c.fechaAplicacion());if(!elegibilidad.elegible())throw new BusinessException(ErrorCode.SANIDAD_ANIMAL_NO_ELEGIBLE,a.codigo()+": "+String.join(" ",elegibilidad.motivos()));LocalDate fecha=c.fechaAplicacion();LocalDate prox=item.frecuenciaDias()!=null?fecha.plusDays(item.frecuenciaDias()):null;LocalDate rc=info==null||info.retiroCarneDias()==0?null:fecha.plusDays(info.retiroCarneDias());LocalDate rl=info==null||info.retiroLecheDias()==0?null:fecha.plusDays(info.retiroLecheDias());String key=c.operationId()+":"+aid;AplicacionSanitaria ap=repo.crearAplicacion(new AplicacionSanitaria(UUID.randomUUID(),u.empresaId(),id,c.planItemId(),aid,c.productoId(),c.loteProductoId(),c.dosis(),c.unidadDosis(),c.viaAdministracion(),fecha,prox,rc,rl,u.userId(),c.resultado(),c.observaciones(),key,"APLICADA",0),u.userId());out.add(ap);publicar(u,ap,j);programar(u,ap,item);audit(u,"APLICAR_SANIDAD","APLICACION_SANITARIA",ap.id());}JornadaSanitaria done=repo.confirmar(id,u.empresaId(),u.userId());audit(u,"CONFIRMAR_JORNADA_SANITARIA","JORNADA_SANITARIA",id);return new ConfirmacionJornadaResult(done,out,out.size());}
 private PlanSanitarioItem buscarItem(UUID id,UUID e){return planes.planes(e).stream().flatMap(p->planes.items(p.id(),e,false).stream()).filter(i->i.id().equals(id)).findFirst().orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_PLAN_NOT_FOUND));}
 private PlanSanitarioItem requireItemCompatible(UUID id,UUID empresa,JornadaSanitaria jornada){PlanSanitarioItem item=buscarItem(id,empresa);if(!item.activo()||item.tipoActividad()!=jornada.tipoJornada())throw new BusinessException(ErrorCode.SANIDAD_ITEM_JORNADA_INCOMPATIBLE);return item;}
 private ProductoSanitarioPort.ProductoSanitarioInfo producto(CurrentUser u,UUID id){if(id==null)return null;ProductoSanitarioPort p=productos.getIfAvailable();if(p!=null&&!p.existeYEstaActivo(u.empresaId(),id))throw new BusinessException(ErrorCode.SANIDAD_PRODUCTO_INVALIDO);return p==null?new ProductoSanitarioPort.ProductoSanitarioInfo(id,0,0):p.informacion(u.empresaId(),id);}
 private AnimalElegibilidad evaluar(Animal a,JornadaSanitaria j,PlanSanitarioItem i,LocalDate fecha){List<String>motivos=new ArrayList<>();if(a.estado()!=EstadoAnimal.ACTIVO)motivos.add("El animal no está activo.");if(!a.propiedadActualId().equals(j.propiedadId()))motivos.add("El animal ya no pertenece a la propiedad de la jornada.");if(j.potreroId()!=null&&!j.potreroId().equals(a.potreroActualId()))motivos.add("El animal no pertenece al potrero de la jornada.");if(j.loteGanaderoId()!=null&&!j.loteGanaderoId().equals(a.loteActualId()))motivos.add("El animal no pertenece al lote de la jornada.");if(i.sexoAplicable()!=null&&i.sexoAplicable()!=a.sexo())motivos.add("El sexo del animal no coincide con la actividad.");if(i.categoriaAnimalId()!=null&&!i.categoriaAnimalId().equals(a.categoriaActualId()))motivos.add("La categoría del animal no coincide con la actividad.");Long edad=null;if(a.fechaNacimiento()!=null)edad=java.time.temporal.ChronoUnit.DAYS.between(a.fechaNacimiento(),fecha);if((i.edadMinDias()!=null||i.edadMaxDias()!=null)&&edad==null)motivos.add("El animal no tiene fecha de nacimiento para validar su edad.");if(edad!=null&&i.edadMinDias()!=null&&edad<i.edadMinDias())motivos.add("Tiene "+edad+" días; la actividad requiere al menos "+i.edadMinDias()+" días.");if(edad!=null&&i.edadMaxDias()!=null&&edad>i.edadMaxDias())motivos.add("Tiene "+edad+" días; la actividad permite como máximo "+i.edadMaxDias()+" días.");return new AnimalElegibilidad(a.id(),a.codigo(),a.nombre(),a.sexo(),a.estado(),edad,motivos.isEmpty(),List.copyOf(motivos));}
 private void publicar(CurrentUser u,AplicacionSanitaria a,JornadaSanitaria j){TipoEventoAnimal t=j.tipoJornada()==TipoActividadSanitaria.VACUNACION?TipoEventoAnimal.VACUNACION_APLICADA:TipoEventoAnimal.TRATAMIENTO_APLICADO;timeline.publish(new RegistrarEventoTimeline(u.empresaId(),a.animalId(),t,null,j.tipoJornada().name(),null,a.id(),Map.of("jornadaId",j.id()),u.userId(),Instant.now(),a.idempotencyKey()));}
 private void programar(CurrentUser u,AplicacionSanitaria a,PlanSanitarioItem i){MotorAlertas m=alertas.getIfAvailable();if(m==null)return;if(a.proximaAplicacion()!=null&&i!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),a.animalId(),TipoAlerta.VACUNACION_PROXIMA,a.proximaAplicacion().minusDays(i.diasAlerta()).atStartOfDay(ZoneOffset.UTC).toInstant(),a.proximaAplicacion().atStartOfDay(ZoneOffset.UTC).toInstant(),"APLICACION_SANITARIA",a.id(),Map.of()));if(a.retiroCarneHasta()!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),a.animalId(),TipoAlerta.RETIRO_SANITARIO,a.retiroCarneHasta().atStartOfDay(ZoneOffset.UTC).toInstant(),"RETIRO_CARNE",a.id(),Map.of("tipoRetiro","CARNE","hasta",a.retiroCarneHasta().toString())));if(a.retiroLecheHasta()!=null)m.programar(new ProgramarAlertaCommand(u.empresaId(),a.animalId(),TipoAlerta.RETIRO_SANITARIO,a.retiroLecheHasta().atStartOfDay(ZoneOffset.UTC).toInstant(),"RETIRO_LECHE",a.id(),Map.of("tipoRetiro","LECHE","hasta",a.retiroLecheHasta().toString())));}
 private JornadaSanitaria require(UUID id,CurrentUser u){JornadaSanitaria j=repo.buscar(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_JORNADA_NOT_FOUND));context.requirePropertyAccess(u,j.propiedadId());return j;}private Animal animal(CurrentUser u,UUID id){return animales.findById(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.ANIMAL_NOT_FOUND));}private void audit(CurrentUser u,String ac,String en,UUID id){events.publishEvent(new SanidadAuditEvent(u.empresaId(),u.userId(),ac,en,id,Instant.now()));}
}
