package bo.com.ganadero.sanidad.application;
import bo.com.ganadero.sanidad.domain.*; import bo.com.ganadero.shared.error.*; import bo.com.ganadero.shared.security.*;
import org.springframework.beans.factory.ObjectProvider; import org.springframework.context.ApplicationEventPublisher; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;
@Service public class PlanSanitarioService {
 private final SanidadRepository repo; private final UserContext context; private final ObjectProvider<ProductoSanitarioPort> productos; private final ApplicationEventPublisher events;
 public PlanSanitarioService(SanidadRepository repo,UserContext context,ObjectProvider<ProductoSanitarioPort> productos,ApplicationEventPublisher events){this.repo=repo;this.context=context;this.productos=productos;this.events=events;}
 @Transactional(readOnly=true) public List<Enfermedad> enfermedades(boolean inactivas){CurrentUser u=context.requirePermission("SANIDAD_VER");return repo.enfermedades(u.empresaId(),inactivas);}
 @Transactional public Enfermedad crearEnfermedad(CrearEnfermedadCommand c){CurrentUser u=context.requirePermission("SANIDAD_PLAN_ADMINISTRAR");UUID id=UUID.randomUUID();Enfermedad e=repo.crearEnfermedad(new Enfermedad(id,u.empresaId(),c.codigo().trim().toUpperCase(),c.nombre().trim(),c.descripcion(),c.esNotificable(),true,null,null));audit(u,"CREAR_ENFERMEDAD","ENFERMEDAD",id);return e;}
 @Transactional public Enfermedad estadoEnfermedad(UUID id,boolean activo){CurrentUser u=context.requirePermission("SANIDAD_PLAN_ADMINISTRAR");Enfermedad e=repo.cambiarEstadoEnfermedad(id,u.empresaId(),activo);audit(u,activo?"ACTIVAR_ENFERMEDAD":"DESACTIVAR_ENFERMEDAD","ENFERMEDAD",id);return e;}
 @Transactional(readOnly=true) public List<PlanSanitario> planes(){return repo.planes(context.requirePermission("SANIDAD_VER").empresaId());}
 @Transactional public PlanSanitario crearPlan(CrearPlanSanitarioCommand c){CurrentUser u=context.requirePermission("SANIDAD_PLAN_ADMINISTRAR");if(c.fechaFin()!=null&&c.fechaFin().isBefore(c.fechaInicio()))throw new BusinessException(ErrorCode.REPRODUCCION_FECHA_INVALIDA);UUID id=UUID.randomUUID();PlanSanitario p=repo.crearPlan(new PlanSanitario(id,u.empresaId(),c.nombre(),c.descripcion(),c.fechaInicio(),c.fechaFin(),EstadoPlanSanitario.BORRADOR,null,null,0),u.userId());audit(u,"CREAR_PLAN_SANITARIO","PLAN_SANITARIO",id);return p;}
 @Transactional public PlanSanitario cambiarEstado(UUID id,EstadoPlanSanitario nuevo,long version){CurrentUser u=context.requirePermission("SANIDAD_PLAN_ADMINISTRAR");PlanSanitario actual=repo.plan(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_PLAN_NOT_FOUND));if(!permitida(actual.estado(),nuevo))throw new BusinessException(ErrorCode.SANIDAD_TRANSICION_INVALIDA);if(nuevo==EstadoPlanSanitario.ACTIVO&&repo.planes(u.empresaId()).stream().anyMatch(p->p.estado()==EstadoPlanSanitario.ACTIVO&&!p.id().equals(id)))throw new BusinessException(ErrorCode.SANIDAD_PLAN_ACTIVO_EXISTE);PlanSanitario p=repo.cambiarEstadoPlan(id,u.empresaId(),nuevo,version,u.userId());audit(u,"CAMBIAR_ESTADO_PLAN","PLAN_SANITARIO",id);return p;}
 @Transactional(readOnly=true) public List<PlanSanitarioItem> items(UUID plan,boolean inactivos){CurrentUser u=context.requirePermission("SANIDAD_VER");requirePlan(plan,u);return repo.items(plan,u.empresaId(),inactivos);}
 @Transactional public PlanSanitarioItem crearItem(UUID planId,CrearPlanItemCommand c){CurrentUser u=context.requirePermission("SANIDAD_PLAN_ADMINISTRAR");requirePlan(planId,u);if(c.edadMinDias()!=null&&c.edadMaxDias()!=null&&c.edadMaxDias()<c.edadMinDias())throw new BusinessException(ErrorCode.SANIDAD_ITEM_EDAD_INVALIDA);ProductoSanitarioPort port=productos.getIfAvailable();if(c.productoId()!=null&&port!=null&&!port.existeYEstaActivo(u.empresaId(),c.productoId()))throw new BusinessException(ErrorCode.SANIDAD_PRODUCTO_INVALIDO);UUID id=UUID.randomUUID();PlanSanitarioItem i=repo.crearItem(new PlanSanitarioItem(id,u.empresaId(),planId,c.tipoActividad(),c.productoId(),c.productoRecomendadoTexto(),c.categoriaAnimalId(),c.sexoAplicable(),c.edadMinDias(),c.edadMaxDias(),c.dosis(),c.unidadDosis(),c.frecuenciaDias(),c.diasAlerta(),c.viaAdministracion(),c.obligatorio(),true,0),u.userId());audit(u,"CREAR_ITEM_PLAN","PLAN_SANITARIO_ITEM",id);return i;}
 @Transactional public PlanSanitarioItem estadoItem(UUID plan,UUID id,boolean activo,long version){CurrentUser u=context.requirePermission("SANIDAD_PLAN_ADMINISTRAR");requirePlan(plan,u);return repo.cambiarEstadoItem(id,plan,u.empresaId(),activo,version,u.userId());}
 @Transactional(readOnly=true) public ProximaActividadSanitaria calcularProxima(UUID plan,UUID item,LocalDate aplicacion){CurrentUser u=context.requirePermission("SANIDAD_VER");PlanSanitario p=requirePlan(plan,u);if(p.estado()!=EstadoPlanSanitario.ACTIVO)throw new BusinessException(ErrorCode.SANIDAD_TRANSICION_INVALIDA);PlanSanitarioItem i=repo.items(plan,u.empresaId(),false).stream().filter(x->x.id().equals(item)).findFirst().orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_PLAN_NOT_FOUND));if(i.frecuenciaDias()==null)return new ProximaActividadSanitaria(null,null);LocalDate proxima=aplicacion.plusDays(i.frecuenciaDias());return new ProximaActividadSanitaria(proxima,proxima.minusDays(i.diasAlerta()));}
 private PlanSanitario requirePlan(UUID id,CurrentUser u){return repo.plan(id,u.empresaId()).orElseThrow(()->new BusinessException(ErrorCode.SANIDAD_PLAN_NOT_FOUND));}
 private boolean permitida(EstadoPlanSanitario a,EstadoPlanSanitario n){return switch(a){case BORRADOR->n==EstadoPlanSanitario.ACTIVO||n==EstadoPlanSanitario.ANULADO;case ACTIVO->n==EstadoPlanSanitario.FINALIZADO||n==EstadoPlanSanitario.ANULADO;case FINALIZADO,ANULADO->false;};}
 private void audit(CurrentUser u,String accion,String entidad,UUID id){events.publishEvent(new SanidadAuditEvent(u.empresaId(),u.userId(),accion,entidad,id,Instant.now()));}
}
