package bo.com.ganadero.alertas.infrastructure;
import bo.com.ganadero.alertas.application.TipoAlerta;import bo.com.ganadero.alertas.domain.*;import bo.com.ganadero.shared.error.*;import tools.jackson.core.type.TypeReference;import tools.jackson.databind.ObjectMapper;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.Instant;import java.time.OffsetDateTime;import java.util.*;
@Repository public class JdbcAlertaRepository implements AlertaRepository{private final JdbcClient jdbc;private final ObjectMapper json;public JdbcAlertaRepository(JdbcClient j,ObjectMapper o){jdbc=j;json=o;}
 public Alerta programar(Alerta a){jdbc.sql("insert into alertas.alertas(id,empresa_id,animal_id,tipo,titulo,mensaje,severidad,fecha_programada,fecha_vencimiento,origen_tipo,origen_id,estado,metadata) values(:id,:e,:an,:t,:ti,:m,:s,:fp,:fv,:ot,:oi,:es,cast(:md as jsonb)) on conflict(empresa_id,tipo,origen_tipo,origen_id) where origen_id is not null and estado in('PROGRAMADA','PENDIENTE','ENVIADA','ATENDIDA','ERROR') do update set titulo=excluded.titulo,mensaje=excluded.mensaje,severidad=excluded.severidad,fecha_programada=excluded.fecha_programada,fecha_vencimiento=excluded.fecha_vencimiento,metadata=excluded.metadata,updated_at=now() returning id").param("id",a.id()).param("e",a.empresaId()).param("an",a.animalId()).param("t",a.tipo().name()).param("ti",a.titulo()).param("m",a.mensaje()).param("s",a.severidad().name()).param("fp",ts(a.fechaProgramada())).param("fv",ts(a.fechaVencimiento())).param("ot",a.origenTipo()).param("oi",a.origenId()).param("es",a.estado().name()).param("md",write(a.metadata())).query(UUID.class).single();return listar(a.empresaId(),null,null,null).stream().filter(x->x.tipo()==a.tipo()&&Objects.equals(x.origenTipo(),a.origenTipo())&&Objects.equals(x.origenId(),a.origenId())).findFirst().orElseThrow();}
 public Optional<Alerta>buscar(UUID id,UUID e){return jdbc.sql("select * from alertas.alertas where id=:id and empresa_id=:e").param("id",id).param("e",e).query(this::map).optional();}public List<Alerta>listar(UUID e,EstadoAlerta s,TipoAlerta t,UUID a){return jdbc.sql("select * from alertas.alertas where empresa_id=:e and (cast(:s as text) is null or estado=:s) and (cast(:t as text) is null or tipo=:t) and (cast(:a as uuid) is null or animal_id=:a) order by fecha_programada desc").param("e",e).param("s",s==null?null:s.name()).param("t",t==null?null:t.name()).param("a",a).query(this::map).list();}
 public void resolverOrigen(UUID e,String o,UUID id,UUID actor){jdbc.sql("update alertas.alertas set estado='RESUELTA',resuelta_at=now(),resuelta_por=:a,updated_at=now() where empresa_id=:e and origen_tipo=:o and origen_id=:id and estado in('PROGRAMADA','PENDIENTE','ENVIADA','ATENDIDA','ERROR')").param("a",actor).param("e",e).param("o",o).param("id",id).update();}public void cancelarOrigen(UUID e,String o,UUID id,String motivo){jdbc.sql("update alertas.alertas set estado='CANCELADA',cancelada_at=now(),motivo_cancelacion=:m,updated_at=now() where empresa_id=:e and origen_tipo=:o and origen_id=:id and estado in('PROGRAMADA','PENDIENTE','ENVIADA','ATENDIDA','ERROR')").param("m",motivo).param("e",e).param("o",o).param("id",id).update();}
 public Alerta atender(UUID id,UUID e,UUID a){return cambio(id,e,a,"ATENDIDA","atendida_at","atendida_por");}public Alerta resolver(UUID id,UUID e,UUID a){return cambio(id,e,a,"RESUELTA","resuelta_at","resuelta_por");}private Alerta cambio(UUID id,UUID e,UUID a,String estado,String fecha,String actor){int n=jdbc.sql("update alertas.alertas set estado='"+estado+"',"+fecha+"=now(),"+actor+"=:a,updated_at=now() where id=:id and empresa_id=:e and estado not in('RESUELTA','CANCELADA')").param("a",a).param("id",id).param("e",e).update();if(n==0)throw new BusinessException(ErrorCode.ALERTA_NOT_FOUND);return buscar(id,e).orElseThrow();}
  public int activarVencidas(Instant now,int limite){return jdbc.sql("with candidatas as(select id from alertas.alertas where estado='PROGRAMADA' and fecha_programada<=:n order by fecha_programada for update skip locked limit :l) update alertas.alertas a set estado='PENDIENTE',updated_at=now() from candidatas c where a.id=c.id").param("n",Timestamp.from(now)).param("l",limite).update();}
 public List<Alerta>listarPendientesEnvio(Instant ahora,int maxIntentos,int limite){return jdbc.sql("select * from alertas.alertas where (estado='PENDIENTE' or (estado='ERROR' and intentos_envio<:m)) and fecha_programada<=:n order by fecha_programada limit :l").param("m",maxIntentos).param("n",ts(ahora)).param("l",limite).query(this::map).list();}
 public void marcarEnviada(UUID id){jdbc.sql("update alertas.alertas set estado='ENVIADA',enviada_at=coalesce(enviada_at,now()),updated_at=now() where id=:id").param("id",id).update();}
 public void registrarFallo(UUID id,String error,int maxIntentos){String e=error==null?null:(error.length()>1000?error.substring(0,1000):error);jdbc.sql("update alertas.alertas set intentos_envio=intentos_envio+1,ultimo_error=:e,estado=case when intentos_envio+1>=:m then 'ERROR' else estado end,updated_at=now() where id=:id").param("e",e).param("m",maxIntentos).param("id",id).update();}
  private Alerta map(ResultSet r,int n)throws SQLException{return new Alerta(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getObject("animal_id",UUID.class),TipoAlerta.valueOf(r.getString("tipo")),r.getString("titulo"),r.getString("mensaje"),SeveridadAlerta.valueOf(r.getString("severidad")),instant(r,"fecha_programada"),instant(r,"fecha_vencimiento"),r.getString("origen_tipo"),r.getObject("origen_id",UUID.class),EstadoAlerta.valueOf(r.getString("estado")),read(r.getString("metadata")),instant(r,"enviada_at"),instant(r,"atendida_at"),instant(r,"resuelta_at"),instant(r,"cancelada_at"),r.getObject("atendida_por",UUID.class),r.getObject("resuelta_por",UUID.class),r.getString("motivo_cancelacion"),r.getInt("intentos_envio"),r.getString("ultimo_error"),instant(r,"created_at"),instant(r,"updated_at"));}private String write(Map<String,Object>m){try{return json.writeValueAsString(m==null?Map.of():m);}catch(Exception e){throw new IllegalArgumentException(e);}}private Map<String,Object>read(String s){try{return json.readValue(s,new TypeReference<>(){});}catch(Exception e){return Map.of();}} private static Instant instant(ResultSet r,String c)throws SQLException{OffsetDateTime v=r.getObject(c,OffsetDateTime.class);return v==null?null:v.toInstant();}private static Timestamp ts(Instant i){return i==null?null:Timestamp.from(i);}
}
