package bo.com.ganadero.alertas.infrastructure;
import bo.com.ganadero.alertas.application.TipoAlerta;import bo.com.ganadero.alertas.domain.*;import bo.com.ganadero.shared.db.Rows;import bo.com.ganadero.shared.error.*;import tools.jackson.core.type.TypeReference;import tools.jackson.databind.ObjectMapper;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.Instant;import java.util.*;
@Repository public class JdbcAlertaRepository implements AlertaRepository{private final JdbcClient jdbc;private final ObjectMapper json;public JdbcAlertaRepository(JdbcClient j,ObjectMapper o){jdbc=j;json=o;}
 public Alerta programar(Alerta a){String id=jdbc.sql("insert into alerta(id,animal_id,tipo,titulo,mensaje,severidad,fecha_programada,fecha_vencimiento,origen_tipo,origen_id,estado,metadata,clave_idempotencia) values(:id,:an,:t,:ti,:m,:s,:fp,:fv,:ot,:oi,:es,:md,:ci) on conflict(clave_idempotencia) do update set titulo=excluded.titulo,mensaje=excluded.mensaje,severidad=excluded.severidad,fecha_programada=excluded.fecha_programada,fecha_vencimiento=excluded.fecha_vencimiento,metadata=excluded.metadata,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') returning id").param("id",a.id()).param("an",a.animalId()).param("t",a.tipo().name()).param("ti",a.titulo()).param("m",a.mensaje()).param("s",a.severidad().name()).param("fp",ts(a.fechaProgramada())).param("fv",ts(a.fechaVencimiento())).param("ot",a.origenTipo()).param("oi",a.origenId()).param("es",a.estado().name()).param("md",write(a.metadata())).param("ci",a.claveIdempotencia()).query(String.class).single();return buscar(UUID.fromString(id),a.empresaId()).orElseThrow();}
 public Optional<Alerta> evolucionarOrigen(Alerta a,Collection<TipoAlerta> anteriores){if(anteriores==null||anteriores.isEmpty())return Optional.empty();String tipos=anteriores.stream().map(t->"'"+t.name()+"'").collect(java.util.stream.Collectors.joining(","));String sql="update alerta set tipo=:t,titulo=:ti,mensaje=:m,severidad=:s,fecha_programada=:fp,fecha_vencimiento=:fv,metadata=:md,clave_idempotencia=:ci,estado=case when tipo<>:t or severidad<>:s then 'PENDIENTE' else estado end,enviada_at=case when tipo<>:t or severidad<>:s then null else enviada_at end,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where origen_tipo=:ot and origen_id=:oi and tipo in ("+tipos+") and estado in('PROGRAMADA','PENDIENTE','ENVIADA','ATENDIDA','ERROR') returning id";Optional<String> id=jdbc.sql(sql).param("t",a.tipo().name()).param("ti",a.titulo()).param("m",a.mensaje()).param("s",a.severidad().name()).param("fp",ts(a.fechaProgramada())).param("fv",ts(a.fechaVencimiento())).param("md",write(a.metadata())).param("ci",a.claveIdempotencia()).param("ot",a.origenTipo()).param("oi",a.origenId()).query(String.class).optional();return id.map(UUID::fromString).flatMap(x->buscar(x,a.empresaId()));}
 public Optional<Alerta>buscar(UUID id,UUID e){return jdbc.sql("select * from alerta where id=:id").param("id",id).query(this::map).optional();}
 public List<Alerta>listar(UUID e,EstadoAlerta s,TipoAlerta t,UUID a){String sql="select * from alerta where 1=1"+(s==null?"":" and estado=:s")+(t==null?"":" and tipo=:t")+(a==null?"":" and animal_id=:a")+" order by fecha_programada desc";var q=jdbc.sql(sql);if(s!=null)q=q.param("s",s.name());if(t!=null)q=q.param("t",t.name());if(a!=null)q=q.param("a",a);return q.query(this::map).list();}
 public void resolverOrigen(UUID e,String o,UUID id,UUID actor){jdbc.sql("update alerta set estado='RESUELTA',resuelta_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),resuelta_por=:a,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where origen_tipo=:o and origen_id=:id and estado in('PROGRAMADA','PENDIENTE','ENVIADA','ATENDIDA','ERROR')").param("a",actor).param("o",o).param("id",id).update();}public void cancelarOrigen(UUID e,String o,UUID id,String motivo){jdbc.sql("update alerta set estado='CANCELADA',cancelada_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),motivo_cancelacion=:m,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where origen_tipo=:o and origen_id=:id and estado in('PROGRAMADA','PENDIENTE','ENVIADA','ATENDIDA','ERROR')").param("m",motivo).param("o",o).param("id",id).update();}
 public Alerta atender(UUID id,UUID e,UUID a){return cambio(id,e,a,"ATENDIDA","atendida_at","atendida_por");}public Alerta resolver(UUID id,UUID e,UUID a){return cambio(id,e,a,"RESUELTA","resuelta_at","resuelta_por");}private Alerta cambio(UUID id,UUID e,UUID a,String estado,String fecha,String actor){int n=jdbc.sql("update alerta set estado='"+estado+"',"+fecha+"=strftime('%Y-%m-%dT%H:%M:%fZ','now'),"+actor+"=:a,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where id=:id and estado not in('RESUELTA','CANCELADA')").param("a",a).param("id",id).update();if(n==0)throw new BusinessException(ErrorCode.ALERTA_NOT_FOUND);return buscar(id,e).orElseThrow();}
  public int activarVencidas(Instant now,int limite){return jdbc.sql("update alerta set estado='PENDIENTE',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where id in (select id from alerta where estado='PROGRAMADA' and fecha_programada<=:n order by fecha_programada limit :l)").param("n",ts(now)).param("l",limite).update();}
 public List<Alerta>listarPendientes(Instant ahora,int limite){return jdbc.sql("select * from alerta where estado='PENDIENTE' and fecha_programada<=:n order by fecha_programada limit :l").param("n",ts(ahora)).param("l",limite).query(this::map).list();}
  public void marcarEnviada(UUID id){jdbc.sql("update alerta set estado='ENVIADA',enviada_at=coalesce(enviada_at,strftime('%Y-%m-%dT%H:%M:%fZ','now')),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where id=:id").param("id",id).update();}
  public void marcarError(UUID id,String error){jdbc.sql("update alerta set estado='ERROR',ultimo_error=:e,intentos_envio=intentos_envio+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') where id=:id").param("e",error==null?null:error.substring(0,Math.min(error.length(),1000))).param("id",id).update();}
  private Alerta map(ResultSet r,int n)throws SQLException{return new Alerta(Rows.uuid(r,"id"),null,Rows.uuid(r,"animal_id"),TipoAlerta.valueOf(r.getString("tipo")),r.getString("titulo"),r.getString("mensaje"),SeveridadAlerta.valueOf(r.getString("severidad")),Rows.instant(r,"fecha_programada"),Rows.instant(r,"fecha_vencimiento"),r.getString("origen_tipo"),Rows.uuid(r,"origen_id"),EstadoAlerta.valueOf(r.getString("estado")),read(r.getString("metadata")),Rows.instant(r,"enviada_at"),Rows.instant(r,"atendida_at"),Rows.instant(r,"resuelta_at"),Rows.instant(r,"cancelada_at"),Rows.uuid(r,"atendida_por"),Rows.uuid(r,"resuelta_por"),r.getString("motivo_cancelacion"),r.getInt("intentos_envio"),r.getString("ultimo_error"),Rows.instant(r,"created_at"),Rows.instant(r,"updated_at"),r.getString("clave_idempotencia"));}private String write(Map<String,Object>m){try{return json.writeValueAsString(m==null?Map.of():m);}catch(Exception e){throw new IllegalArgumentException(e);}}private Map<String,Object>read(String s){try{return json.readValue(s,new TypeReference<>(){});}catch(Exception e){return Map.of();}} private static String ts(Instant i){return i==null?null:i.toString();}
}
