package bo.com.ganadero.propiedades.infrastructure;
import bo.com.ganadero.propiedades.domain.*; import bo.com.ganadero.shared.db.Rows; import bo.com.ganadero.shared.error.*;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.ResultSet; import java.sql.SQLException; import java.util.*;
/** App de escritorio: una sola finca local (tabla "propiedad" de una sola fila) y sectores sin jerarquia de propiedad/empresa. */
@Repository class JdbcPropiedadAdapter implements PropiedadRepository,SectorRepository {
 private final JdbcClient jdbc; JdbcPropiedadAdapter(JdbcClient j){jdbc=j;}
 private static final String PROPERTY_SELECT="select id,nombre,descripcion,departamento,municipio,localidad,direccion_referencia,superficie_ha,ubicacion_wkt,limite_geografico_wkt,version from propiedad";
 public List<Propiedad> findAll(UUID empresa,Set<UUID> allowed){return jdbc.sql(PROPERTY_SELECT+" order by nombre").query(this::property).list();}
 public Optional<Propiedad> findById(UUID id,UUID empresa){return jdbc.sql(PROPERTY_SELECT+" where id=:id").param("id",id.toString()).query(this::property).optional();}
 public Propiedad create(Propiedad p,UUID actor){try{jdbc.sql("insert into propiedad(id,nombre,descripcion,departamento,municipio,localidad,direccion_referencia,superficie_ha,ubicacion_wkt,limite_geografico_wkt) values(:id,:n,:d,:dep,:mun,:loc,:dir,:sup,:point,:polygon)").params(propertyParams(p,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.PROPERTY_CODE_ALREADY_EXISTS);}return findById(p.id(),p.empresaId()).orElseThrow();}
 public Propiedad update(Propiedad p,UUID actor){int changed;try{changed=jdbc.sql("update propiedad set nombre=coalesce(:n,nombre),descripcion=coalesce(:d,descripcion),departamento=coalesce(:dep,departamento),municipio=coalesce(:mun,municipio),localidad=coalesce(:loc,localidad),direccion_referencia=coalesce(:dir,direccion_referencia),superficie_ha=coalesce(:sup,superficie_ha),ubicacion_wkt=coalesce(:point,ubicacion_wkt),limite_geografico_wkt=coalesce(:polygon,limite_geografico_wkt),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),version=version+1 where id=:id and version=:v").params(propertyParams(p,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.PROPERTY_CODE_ALREADY_EXISTS);}if(changed==0)throw missingOrConflict(findById(p.id(),p.empresaId()).isPresent());return findById(p.id(),p.empresaId()).orElseThrow();}
 public boolean hasActiveAnimals(UUID id,UUID empresa){return jdbc.sql("select exists(select 1 from animal where estado='ACTIVO')").query(Boolean.class).single();}
 public List<Sector> findAll(UUID propiedad,UUID empresa){return jdbc.sql("select * from sector order by nombre").query(this::sector).list();}
 public Optional<Sector> findSectorById(UUID id,UUID empresa){return jdbc.sql("select * from sector where id=:id").param("id",id.toString()).query(this::sector).optional();}
 public Sector create(Sector s,UUID actor){try{jdbc.sql("insert into sector(id,codigo,nombre,descripcion,activo,created_by,updated_by) values(:id,:c,:n,:d,:a,:actor,:actor)").params(sectorParams(s,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.SECTOR_CODE_ALREADY_EXISTS);}return findSectorById(s.id(),s.empresaId()).orElseThrow();}
 public Sector update(Sector s,UUID actor){int changed;try{changed=jdbc.sql("update sector set codigo=coalesce(:c,codigo),nombre=coalesce(:n,nombre),descripcion=coalesce(:d,descripcion),activo=:a,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id and version=:v").params(sectorParams(s,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.SECTOR_CODE_ALREADY_EXISTS);}if(changed==0)throw new BusinessException(findSectorById(s.id(),s.empresaId()).isPresent()?ErrorCode.VERSION_CONFLICT:ErrorCode.SECTOR_NOT_FOUND);return findSectorById(s.id(),s.empresaId()).orElseThrow();}
 private Map<String,Object> propertyParams(Propiedad p,UUID actor){Map<String,Object> m=new HashMap<>();m.put("id",p.id().toString());m.put("n",p.nombre());m.put("d",p.descripcion());m.put("dep",p.departamento());m.put("mun",p.municipio());m.put("loc",p.localidad());m.put("dir",p.direccionReferencia());m.put("sup",p.superficieHa());m.put("point",p.ubicacionWkt());m.put("polygon",p.limiteGeograficoWkt());m.put("v",p.version());return m;}
 private Map<String,Object> sectorParams(Sector s,UUID actor){Map<String,Object> m=new HashMap<>();m.put("id",s.id().toString());m.put("c",s.codigo());m.put("n",s.nombre());m.put("d",s.descripcion());m.put("a",s.activo());m.put("v",s.version());m.put("actor",actor.toString());return m;}
 private Propiedad property(ResultSet r,int n)throws SQLException{return new Propiedad(Rows.uuid(r,"id"),null,"LOCAL",r.getString("nombre"),r.getString("descripcion"),r.getString("departamento"),r.getString("municipio"),r.getString("localidad"),r.getString("direccion_referencia"),r.getBigDecimal("superficie_ha"),r.getString("ubicacion_wkt"),r.getString("limite_geografico_wkt"),true,r.getLong("version"));}
 private Sector sector(ResultSet r,int n)throws SQLException{return new Sector(Rows.uuid(r,"id"),null,null,r.getString("codigo"),r.getString("nombre"),r.getString("descripcion"),r.getBoolean("activo"),r.getLong("version"));}
 private BusinessException duplicate(Exception e,ErrorCode code){return new BusinessException(code);}
 private BusinessException missingOrConflict(boolean exists){return new BusinessException(exists?ErrorCode.VERSION_CONFLICT:ErrorCode.PROPERTY_NOT_FOUND);}
}
