package bo.com.ganadero.propiedades.infrastructure;
import bo.com.ganadero.propiedades.domain.*; import bo.com.ganadero.shared.error.*;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.ResultSet; import java.sql.SQLException; import java.util.*;
@Repository class JdbcPropiedadAdapter implements PropiedadRepository,SectorRepository {
 private final JdbcClient jdbc; JdbcPropiedadAdapter(JdbcClient j){jdbc=j;}
 private static final String PROPERTY_SELECT="select id,empresa_id,codigo,nombre,descripcion,departamento,municipio,localidad,direccion_referencia,superficie_ha,case when ubicacion is null then null else st_astext(ubicacion::geometry) end ubicacion_wkt,case when limite_geografico is null then null else st_astext(limite_geografico::geometry) end limite_wkt,activo,version from core.propiedades";
 public List<Propiedad> findAll(UUID empresa,Set<UUID> allowed){String scope=allowed.isEmpty()?"":" and id in (:allowed)";JdbcClient.StatementSpec q=jdbc.sql(PROPERTY_SELECT+" where empresa_id=:e"+scope+" order by nombre").param("e",empresa);if(!allowed.isEmpty())q=q.param("allowed",allowed);return q.query(this::property).list();}
 public Optional<Propiedad> findById(UUID id,UUID empresa){return jdbc.sql(PROPERTY_SELECT+" where id=:id and empresa_id=:e").param("id",id).param("e",empresa).query(this::property).optional();}
 public Propiedad create(Propiedad p,UUID actor){try{jdbc.sql("insert into core.propiedades(id,empresa_id,codigo,nombre,descripcion,departamento,municipio,localidad,direccion_referencia,superficie_ha,ubicacion,limite_geografico,activo,created_by,updated_by) values(:id,:e,:c,:n,:d,:dep,:mun,:loc,:dir,:sup,case when cast(:point as text) is null then null else st_geogfromtext(cast(:point as text)) end,case when cast(:polygon as text) is null then null else st_geogfromtext(cast(:polygon as text)) end,:a,:actor,:actor)").params(propertyParams(p,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.PROPERTY_CODE_ALREADY_EXISTS);}return findById(p.id(),p.empresaId()).orElseThrow();}
 public Propiedad update(Propiedad p,UUID actor){int changed;try{changed=jdbc.sql("update core.propiedades set codigo=coalesce(:c,codigo),nombre=coalesce(:n,nombre),descripcion=coalesce(:d,descripcion),departamento=coalesce(:dep,departamento),municipio=coalesce(:mun,municipio),localidad=coalesce(:loc,localidad),direccion_referencia=coalesce(:dir,direccion_referencia),superficie_ha=coalesce(:sup,superficie_ha),ubicacion=case when cast(:point as text) is null then ubicacion else st_geogfromtext(cast(:point as text)) end,limite_geografico=case when cast(:polygon as text) is null then limite_geografico else st_geogfromtext(cast(:polygon as text)) end,activo=:a,updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e and version=:v").params(propertyParams(p,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.PROPERTY_CODE_ALREADY_EXISTS);}if(changed==0)throw missingOrConflict(findById(p.id(),p.empresaId()).isPresent());return findById(p.id(),p.empresaId()).orElseThrow();}
 public boolean hasActiveAnimals(UUID id,UUID empresa){Boolean exists=jdbc.sql("select to_regclass('ganado.animales') is not null").query(Boolean.class).single();if(!Boolean.TRUE.equals(exists))return false;return jdbc.sql("select exists(select 1 from ganado.animales where empresa_id=:e and propiedad_actual_id=:p and estado='ACTIVO')").param("e",empresa).param("p",id).query(Boolean.class).single();}
 public List<Sector> findAll(UUID propiedad,UUID empresa){return jdbc.sql("select * from campo.sectores where propiedad_id=:p and empresa_id=:e order by nombre").param("p",propiedad).param("e",empresa).query(this::sector).list();}
 public Optional<Sector> findSectorById(UUID id,UUID empresa){return jdbc.sql("select * from campo.sectores where id=:id and empresa_id=:e").param("id",id).param("e",empresa).query(this::sector).optional();}
 public Sector create(Sector s,UUID actor){try{jdbc.sql("insert into campo.sectores(id,empresa_id,propiedad_id,codigo,nombre,descripcion,activo,created_by,updated_by) values(:id,:e,:p,:c,:n,:d,:a,:actor,:actor)").params(sectorParams(s,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.SECTOR_CODE_ALREADY_EXISTS);}return findSectorById(s.id(),s.empresaId()).orElseThrow();}
 public Sector update(Sector s,UUID actor){int changed;try{changed=jdbc.sql("update campo.sectores set codigo=coalesce(:c,codigo),nombre=coalesce(:n,nombre),descripcion=coalesce(:d,descripcion),activo=:a,updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e and propiedad_id=:p and version=:v").params(sectorParams(s,actor)).update();}catch(DataIntegrityViolationException e){throw duplicate(e,ErrorCode.SECTOR_CODE_ALREADY_EXISTS);}if(changed==0)throw new BusinessException(findSectorById(s.id(),s.empresaId()).isPresent()?ErrorCode.VERSION_CONFLICT:ErrorCode.SECTOR_NOT_FOUND);return findSectorById(s.id(),s.empresaId()).orElseThrow();}
 private Map<String,Object> propertyParams(Propiedad p,UUID actor){Map<String,Object> m=new HashMap<>();m.put("id",p.id());m.put("e",p.empresaId());m.put("c",p.codigo());m.put("n",p.nombre());m.put("d",p.descripcion());m.put("dep",p.departamento());m.put("mun",p.municipio());m.put("loc",p.localidad());m.put("dir",p.direccionReferencia());m.put("sup",p.superficieHa());m.put("point",p.ubicacionWkt());m.put("polygon",p.limiteGeograficoWkt());m.put("a",p.activo());m.put("v",p.version());m.put("actor",actor);return m;}
 private Map<String,Object> sectorParams(Sector s,UUID actor){Map<String,Object> m=new HashMap<>();m.put("id",s.id());m.put("e",s.empresaId());m.put("p",s.propiedadId());m.put("c",s.codigo());m.put("n",s.nombre());m.put("d",s.descripcion());m.put("a",s.activo());m.put("v",s.version());m.put("actor",actor);return m;}
 private Propiedad property(ResultSet r,int n)throws SQLException{return new Propiedad(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getString("codigo"),r.getString("nombre"),r.getString("descripcion"),r.getString("departamento"),r.getString("municipio"),r.getString("localidad"),r.getString("direccion_referencia"),r.getBigDecimal("superficie_ha"),r.getString("ubicacion_wkt"),r.getString("limite_wkt"),r.getBoolean("activo"),r.getLong("version"));}
 private Sector sector(ResultSet r,int n)throws SQLException{return new Sector(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getObject("propiedad_id",UUID.class),r.getString("codigo"),r.getString("nombre"),r.getString("descripcion"),r.getBoolean("activo"),r.getLong("version"));}
 private BusinessException duplicate(Exception e,ErrorCode code){return new BusinessException(code);}
 private BusinessException missingOrConflict(boolean exists){return new BusinessException(exists?ErrorCode.VERSION_CONFLICT:ErrorCode.PROPERTY_NOT_FOUND);}
}
