package bo.com.ganadero.potreros.application;
import bo.com.ganadero.potreros.domain.*; import bo.com.ganadero.shared.codigos.*; import bo.com.ganadero.shared.error.*; import bo.com.ganadero.shared.security.*;
import org.springframework.context.ApplicationEventPublisher; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.Instant; import java.util.*;
@Service public class PotreroService {
 private final PotreroRepository repo; private final TipoPastoRepository grasses; private final UserContext context; private final ApplicationEventPublisher events; private final CodigoService codigos;
 public PotreroService(PotreroRepository r,TipoPastoRepository g,UserContext c,ApplicationEventPublisher e,CodigoService codes){repo=r;grasses=g;context=c;events=e;codigos=codes;}
 @Transactional(readOnly=true) public List<Potrero> list(UUID property,EstadoPotrero state,UUID sector){CurrentUser u=context.requirePermission("POTRERO_VER");if(property!=null)context.requirePropertyAccess(u,property);if(!u.accesoTodasPropiedades()&&u.propiedadesPermitidas().isEmpty())return List.of();return repo.findAll(u.empresaId(),u.propiedadesPermitidas(),property,state,sector);}
 @Transactional(readOnly=true) public Potrero get(UUID id){CurrentUser u=context.requirePermission("POTRERO_VER");Potrero p=require(id,u.empresaId());context.requirePropertyAccess(u,p.propiedadId());return p;}
 @Transactional(readOnly=true) public List<TipoPasto> grasses(){CurrentUser u=context.requirePermission("POTRERO_VER");return grasses.findActive(u.empresaId());}
 @Transactional public Potrero create(PotreroCommand c){CurrentUser u=context.requirePermission("POTRERO_CREAR");validateRelations(c.propiedadId(),c.sectorId(),c.tipoPastoId(),u);String codigo=codigos.paraCreacion(u,TipoCodigo.POTRERO,c.propiedadId(),null,c.codigo());Potrero p=new Potrero(UUID.randomUUID(),u.empresaId(),c.propiedadId(),c.sectorId(),codigo,c.nombre(),c.superficieHa(),c.tipoPastoId(),c.capacidadUa(),Boolean.TRUE.equals(c.tieneAgua()),c.estado()==null?EstadoPotrero.DISPONIBLE:c.estado(),c.geometriaWkt(),true,0);Potrero saved=repo.create(p,u.userId());audit(u,"CREAR",saved.id());return saved;}
 @Transactional public Potrero update(UUID id,PotreroCommand c){CurrentUser u=context.requirePermission("POTRERO_EDITAR");Potrero old=require(id,u.empresaId());context.requirePropertyAccess(u,old.propiedadId());UUID property=c.propiedadId()==null?old.propiedadId():c.propiedadId();context.requirePropertyAccess(u,property);boolean clearSector=Boolean.TRUE.equals(c.quitarSector());boolean clearGrass=Boolean.TRUE.equals(c.quitarTipoPasto());boolean clearArea=Boolean.TRUE.equals(c.quitarSuperficie());boolean clearCapacity=Boolean.TRUE.equals(c.quitarCapacidad());UUID sector=clearSector?null:(c.sectorId()==null?old.sectorId():c.sectorId());UUID grass=clearGrass?null:(c.tipoPastoId()==null?old.tipoPastoId():c.tipoPastoId());validateRelations(property,sector,grass,u);boolean active=c.activo()==null?old.activo():c.activo();if(old.activo()&&!active&&repo.hasActiveAnimals(id,u.empresaId()))throw new BusinessException(ErrorCode.PADDOCK_HAS_ACTIVE_ANIMALS);String codigo=codigos.paraActualizacion(u,TipoCodigo.POTRERO,property,null,old.codigo(),c.codigo());Potrero p=new Potrero(id,u.empresaId(),property,sector,codigo,c.nombre(),c.superficieHa(),grass,c.capacidadUa(),c.tieneAgua()==null?old.tieneAgua():c.tieneAgua(),c.estado()==null?old.estado():c.estado(),c.geometriaWkt(),active,Objects.requireNonNull(c.version()));Potrero saved=repo.update(p,u.userId(),clearSector,clearGrass,clearArea,clearCapacity);audit(u,"ACTUALIZAR",id);return saved;}
 private void validateRelations(UUID property,UUID sector,UUID grass,CurrentUser u){context.requirePropertyAccess(u,property);if(!repo.propertyExists(property,u.empresaId()))throw new BusinessException(ErrorCode.PROPERTY_NOT_FOUND);if(sector!=null&&!repo.sectorBelongs(sector,property,u.empresaId()))throw new BusinessException(ErrorCode.SECTOR_NOT_FOUND);if(grass!=null&&!repo.grassTypeExists(grass,u.empresaId()))throw new BusinessException(ErrorCode.GRASS_TYPE_NOT_FOUND);}
 private Potrero require(UUID id,UUID e){return repo.findById(id,e).orElseThrow(()->new BusinessException(ErrorCode.PADDOCK_NOT_FOUND));}
 private void audit(CurrentUser u,String action,UUID id){events.publishEvent(new PotreroAuditEvent(u.empresaId(),u.userId(),action,"POTRERO",id,Instant.now()));}
}
