import { http } from '@/shared/api/http';import type { ApiResponse } from '@/shared/api/types'
export type AlertState='PROGRAMADA'|'PENDIENTE'|'ENVIADA'|'ATENDIDA'|'RESUELTA'|'CANCELADA'|'ERROR';export type AlertSeverity='INFO'|'WARNING'|'URGENTE'|'CRITICA'
export type AlertType='CELO_DETECTADO'|'DIAGNOSTICO_PENDIENTE'|'PARTO_PROXIMO'|'DESTETE_PROXIMO'|'VACUNA_PROXIMA'|'VACUNA_VENCIDA'|'TRATAMIENTO_PROXIMO'|'TRATAMIENTO_ATRASADO'|'RETIRO_CARNE_VIGENTE'|'RETIRO_LECHE_VIGENTE'|'PESAJE_ATRASADO'|'CASO_CLINICO_CRITICO'|'RECORDATORIO_SANIDAD'|'CUARENTENA_POR_FINALIZAR'|'MOVIMIENTO_PENDIENTE'|'INVENTARIO_BAJO'|'SISTEMA_REQUIERE_ATENCION'
export interface GanaderoAlert{id:string;animalId?:string;tipo:AlertType;titulo:string;mensaje:string;severidad:AlertSeverity;fechaProgramada:string;fechaVencimiento?:string;origenTipo:string;origenId?:string;estado:AlertState;metadata:Record<string,unknown>}
export interface AlertCount{total:number;urgentes:number;criticas:number}export interface AlertSummary{pendientes:number;urgentes:number;hoy:number;resueltas:number}
export async function listAlerts(params?:{estado?:AlertState;tipo?:string}){return(await http.get<ApiResponse<GanaderoAlert[]>>('/api/v1/alertas',{params})).data.data}export async function getAlertCount(){return(await http.get<ApiResponse<AlertCount>>('/api/v1/alertas/no-leidas/count')).data.data}export async function getAlertSummary(){return(await http.get<ApiResponse<AlertSummary>>('/api/v1/alertas/resumen')).data.data}export async function attendAlert(id:string){return(await http.post<ApiResponse<GanaderoAlert>>(`/api/v1/alertas/${id}/atender`)).data.data}export async function resolveAlert(id:string){return(await http.post<ApiResponse<GanaderoAlert>>(`/api/v1/alertas/${id}/resolver`)).data.data}
export type ReminderState='ACTIVO'|'PAUSADO'|'COMPLETADO'|'CANCELADO'
export interface Reminder{id:string;titulo:string;mensaje:string;severidad:AlertSeverity;animalId?:string;fechaEvento:string;proximaEjecucion:string;cantidadNotificaciones:number;intervaloMinutos?:number;notificacionesGeneradas:number;estado:ReminderState;version:number}
export interface CreateReminder{titulo:string;mensaje:string;severidad:AlertSeverity;fechaEvento:string;primeraNotificacion:string;cantidadNotificaciones:number;intervaloMinutos?:number}
export async function listReminders(){return(await http.get<ApiResponse<Reminder[]>>('/api/v1/alertas/recordatorios')).data.data}
export async function createReminder(value:CreateReminder){return(await http.post<ApiResponse<Reminder>>('/api/v1/alertas/recordatorios',value)).data.data}
export async function changeReminder(id:string,action:'pausar'|'reanudar'|'cancelar',version:number){return(await http.post<ApiResponse<Reminder>>(`/api/v1/alertas/recordatorios/${id}/${action}`,null,{params:{version}})).data.data}
