import { useMemo,useState,type FormEvent } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { BellRing,CalendarClock,Pause,Play,Plus,XCircle } from 'lucide-react'
import { useAuth } from '@/auth/auth-context'
import { Alert } from '@/shared/components/Alert'
import { Button } from '@/shared/components/Button'
import { Card } from '@/shared/components/Card'
import { Field } from '@/shared/components/Field'
import { Modal } from '@/shared/components/Modal'
import { changeReminder,createReminder,listReminders,type AlertSeverity } from './api'

const localValue=(date:Date)=>{const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}
const format=(value:string)=>new Date(value).toLocaleString('es-BO',{dateStyle:'medium',timeStyle:'short'})

export function RecordatoriosPanel(){
 const{can}=useAuth();const allowed=can('ALERTA_CONFIGURAR');const[open,setOpen]=useState(false)
 const[count,setCount]=useState(1);const[interval,setInterval]=useState(60);const[first,setFirst]=useState('');const[event,setEvent]=useState('')
 const client=useQueryClient();const reminders=useQuery({queryKey:['reminders'],queryFn:listReminders})
 const refresh=()=>client.invalidateQueries({queryKey:['reminders']})
 const create=useMutation({mutationFn:createReminder,onSuccess:()=>{setOpen(false);refresh()}})
 const change=useMutation({mutationFn:({id,action,version}:{id:string;action:'pausar'|'reanudar'|'cancelar';version:number})=>changeReminder(id,action,version),onSuccess:refresh})
 const preview=useMemo(()=>{if(!first)return[];const start=new Date(first);if(Number.isNaN(start.getTime()))return[];return Array.from({length:count},(_,i)=>new Date(start.getTime()+i*interval*60_000))},[first,count,interval])
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);create.mutate({titulo:String(data.get('titulo')),mensaje:String(data.get('mensaje')),severidad:String(data.get('severidad')) as AlertSeverity,fechaEvento:new Date(String(data.get('fechaEvento'))).toISOString(),primeraNotificacion:new Date(String(data.get('primeraNotificacion'))).toISOString(),cantidadNotificaciones:count,intervaloMinutos:count>1?interval:undefined})}
 const defaults=()=>{setFirst(localValue(new Date(Date.now()+3_600_000)));setEvent(localValue(new Date(Date.now()+86_400_000)));setCount(1);setInterval(60);setOpen(true)}
 return <section className="page-stack"><div className="section-heading"><div><h2>Recordatorios programados</h2><p>Agenda avisos sanitarios con fecha, hora y repeticiones.</p></div>{allowed?<Button onClick={defaults}><Plus size={17}/>Programar recordatorio</Button>:null}</div>
 {reminders.error?<Alert tone="danger">No se pudieron cargar los recordatorios.</Alert>:null}
 <div className="notification-center-list">{(reminders.data??[]).map(r=><Card key={r.id}><div className="notification-card-main"><span className="notification-priority">{r.estado}</span><h3>{r.titulo}</h3><p>{r.mensaje}</p><small><CalendarClock size={14}/> Evento: {format(r.fechaEvento)} · {r.notificacionesGeneradas}/{r.cantidadNotificaciones} avisos generados</small></div>{allowed&&['ACTIVO','PAUSADO'].includes(r.estado)?<div className="inline-actions">{r.estado==='ACTIVO'?<Button variant="secondary" onClick={()=>change.mutate({id:r.id,action:'pausar',version:r.version})}><Pause size={15}/>Pausar</Button>:<Button variant="secondary" onClick={()=>change.mutate({id:r.id,action:'reanudar',version:r.version})}><Play size={15}/>Reanudar</Button>}<Button variant="danger" onClick={()=>change.mutate({id:r.id,action:'cancelar',version:r.version})}><XCircle size={15}/>Cancelar</Button></div>:null}</Card>)}</div>
 <Modal open={open} title="Programar recordatorio sanitario" onClose={()=>setOpen(false)} wide><form className="form-grid" onSubmit={submit}><Field label="Título" required><input name="titulo" maxLength={200} placeholder="Vacunar lote de terneras"/></Field><Field label="Prioridad" required><select name="severidad" defaultValue="WARNING"><option value="INFO">Informativa</option><option value="WARNING">Importante</option><option value="URGENTE">Urgente</option><option value="CRITICA">Crítica</option></select></Field><Field label="Mensaje" required><textarea name="mensaje" maxLength={1000} rows={3} placeholder="Aplicar vacuna y registrar la jornada sanitaria"/></Field><Field label="Fecha y hora del evento" required><input name="fechaEvento" type="datetime-local" value={event} min={localValue(new Date())} onChange={e=>setEvent(e.target.value)}/></Field><Field label="Primera notificación" required><input name="primeraNotificacion" type="datetime-local" value={first} min={localValue(new Date())} onChange={e=>setFirst(e.target.value)}/></Field><Field label="Cantidad de avisos" hint="Máximo 10"><input type="number" min={1} max={10} value={count} onChange={e=>setCount(Number(e.target.value))}/></Field>{count>1?<Field label="Intervalo entre avisos"><select value={interval} onChange={e=>setInterval(Number(e.target.value))}><option value={15}>15 minutos</option><option value={30}>30 minutos</option><option value={60}>1 hora</option><option value={120}>2 horas</option><option value={360}>6 horas</option><option value={1440}>1 día</option></select></Field>:null}<Card><BellRing size={18}/><strong>Vista previa</strong>{preview.map((d,i)=><div key={d.toISOString()}>Aviso {i+1}: {d.toLocaleString('es-BO')}</div>)}{preview.some(d=>event&&d>new Date(event))?<Alert tone="warning">Todos los avisos deben ocurrir antes del evento.</Alert>:null}</Card>{create.error?<Alert tone="danger">No se pudo crear. Verifica que los avisos ocurran antes del evento.</Alert>:null}<div className="inline-actions"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" loading={create.isPending} disabled={!event||!first||preview.some(d=>d>new Date(event))}>Guardar recordatorio</Button></div></form></Modal></section>
}
