package bo.com.ganadero.animales.application;
import bo.com.ganadero.animales.domain.*; import bo.com.ganadero.shared.codigos.CodigoService; import bo.com.ganadero.shared.error.*; import bo.com.ganadero.shared.security.*;
import bo.com.ganadero.timeline.application.TimelineService;
import org.junit.jupiter.api.*; import java.time.LocalDate; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class AnimalServiceTest {
 private AnimalRepository animals;private RazaRepository breeds;private CategoriaAnimalRepository categories;private UUID company,property,paddock;private AnimalService service;
 @BeforeEach void setup(){animals=mock(AnimalRepository.class);breeds=mock(RazaRepository.class);categories=mock(CategoriaAnimalRepository.class);company=UUID.randomUUID();property=UUID.randomUUID();paddock=UUID.randomUUID();CurrentUser user=new CurrentUser(UUID.randomUUID(),company,UUID.randomUUID(),Set.of(),Set.of("ANIMAL_CREAR","ANIMAL_EDITAR","ANIMAL_CAMBIAR_ESTADO","ANIMAL_REGISTRAR_BAJA"),Set.of(),true);service=new AnimalService(animals,breeds,categories,new UserContext(()->user),event->{},event->{},mock(TimelineService.class),mock(CodigoService.class));}
 @Test void rejectsCategoryForDifferentSex(){UUID breed=UUID.randomUUID(),category=UUID.randomUUID();when(breeds.findById(breed,company)).thenReturn(Optional.of(new Raza(breed,null,"BRAHMAN","Brahman","BOVINO",null,true)));when(categories.findById(category,company)).thenReturn(Optional.of(new CategoriaAnimal(category,null,"VACA","Vaca","HEMBRA",36,null,null,true)));AnimalCommand c=new AnimalCommand(null,"A-1",null,SexoAnimal.MACHO,null,false,breed,category,null,PropositoAnimal.CARNE,OrigenAnimal.NACIDO,property,paddock,null,LocalDate.now(),null,null,null,null,null,0L);assertThatThrownBy(()->service.create(c)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.code()).isEqualTo(ErrorCode.ANIMAL_CATEGORY_SEX_MISMATCH));verify(animals,never()).create(any(),any());}
 @Test void deadAnimalCannotReturnToActive(){UUID id=UUID.randomUUID();when(animals.findById(id,company)).thenReturn(Optional.of(animal(id,EstadoAnimal.MUERTO)));assertThatThrownBy(()->service.changeState(id,EstadoAnimal.ACTIVO,"Corrección",0)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.code()).isEqualTo(ErrorCode.INVALID_ANIMAL_STATE_TRANSITION));verify(animals,never()).changeState(any(),any(),any(),any(),any(),anyLong(),any());}
 @Test void soldAnimalCannotMoveToAnotherPaddock(){UUID id=UUID.randomUUID();when(animals.findById(id,company)).thenReturn(Optional.of(animal(id,EstadoAnimal.VENDIDO)));AnimalCommand c=new AnimalCommand(null,null,null,null,null,null,null,null,null,null,null,property,UUID.randomUUID(),null,null,null,null,null,null,null,0L);assertThatThrownBy(()->service.update(id,c)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.code()).isEqualTo(ErrorCode.ANIMAL_NOT_ACTIVE));verify(animals,never()).update(any(),any());}
 private Animal animal(UUID id,EstadoAnimal state){return new Animal(id,company,"A-1",null,SexoAnimal.HEMBRA,null,false,UUID.randomUUID(),UUID.randomUUID(),null,PropositoAnimal.CARNE,OrigenAnimal.NACIDO,property,paddock,null,state,LocalDate.now(),null,null,null,null,null,0);}
}
