package bo.com.ganadero.potreros.infrastructure;
import bo.com.ganadero.potreros.domain.*; import bo.com.ganadero.shared.db.Rows; import bo.com.ganadero.shared.error.*;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*; import java.util.*;
@Repository class JdbcPotreroAdapter implements PotreroRepository,TipoPastoRepository {
 private final JdbcClient jdbc; JdbcPotreroAdapter(JdbcClient j){jdbc=j;}
 private static final String SELECT="select id,propiedad_id,sector_id,codigo,nombre,superficie_ha,tipo_pasto_id,capacidad_ua,tiene_agua,estado,geometria_wkt,activo,version from potrero";
 public List<Potrero> findAll(UUID empresa,Set<UUID> allowed,UUID property,EstadoPotrero state,UUID sector){StringBuilder sql=new StringBuilder(SELECT+" where 1=1");if(property!=null)sql.append(" and propiedad_id=:property");if(state!=null)sql.append(" and estado=:state");if(sector!=null)sql.append(" and sector_id=:sector");sql.append(" order by nombre");JdbcClient.StatementSpec q=jdbc.sql(sql.toString());if(property!=null)q=q.param("property",property.toString());if(state!=null)q=q.param("state",state.name());if(sector!=null)q=q.param("sector",sector.toString());return q.query(this::paddock).list();}
 public PotreroPage findPage(UUID empresa,Set<UUID> allowed,PotreroFilter f){StringBuilder from=new StringBuilder(" where 1=1");Map<String,Object> p=new HashMap<>();if(f.propiedadId()!=null){from.append(" and propiedad_id=:property");p.put("property",f.propiedadId().toString());}if(f.estado()!=null){from.append(" and estado=:state");p.put("state",f.estado().name());}if(f.sectorId()!=null){from.append(" and sector_id=:sector");p.put("sector",f.sectorId().toString());}long total=jdbc.sql("select count(*) from potrero"+from).params(p).query(Long.class).single();p.put("limit",f.size());p.put("offset",(long)f.page()*f.size());List<Potrero> values=jdbc.sql(SELECT+from+" order by nombre limit :limit offset :offset").params(p).query(this::paddock).list();return PotreroPage.of(values,f.page(),f.size(),total);}
 public Optional<Potrero> findById(UUID id,UUID empresa){return jdbc.sql(SELECT+" where id=:id").param("id",id.toString()).query(this::paddock).optional();}
 public Potrero create(Potrero p,UUID actor){try{jdbc.sql("insert into potrero(id,propiedad_id,sector_id,codigo,nombre,superficie_ha,tipo_pasto_id,capacidad_ua,tiene_agua,estado,geometria_wkt,activo,created_by,updated_by) values(:id,:property,:sector,:code,:name,:area,:grass,:capacity,:water,:state,:geometry,:active,:actor,:actor)").params(params(p,actor)).update();}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.PADDOCK_CODE_ALREADY_EXISTS);}return findById(p.id(),p.empresaId()).orElseThrow();}
 public Potrero update(Potrero p,UUID actor,boolean quitarSector,boolean quitarTipoPasto,boolean quitarSuperficie,boolean quitarCapacidad){int changed;Map<String,Object> values=params(p,actor);values.put("clearSector",quitarSector?1:0);values.put("clearGrass",quitarTipoPasto?1:0);values.put("clearArea",quitarSuperficie?1:0);values.put("clearCapacity",quitarCapacidad?1:0);try{changed=jdbc.sql("update potrero set propiedad_id=coalesce(:property,propiedad_id),sector_id=case when :clearSector=1 then null else coalesce(:sector,sector_id) end,codigo=coalesce(:code,codigo),nombre=coalesce(:name,nombre),superficie_ha=case when :clearArea=1 then null else coalesce(:area,superficie_ha) end,tipo_pasto_id=case when :clearGrass=1 then null else coalesce(:grass,tipo_pasto_id) end,capacidad_ua=case when :clearCapacity=1 then null else coalesce(:capacity,capacidad_ua) end,tiene_agua=:water,estado=:state,geometria_wkt=coalesce(:geometry,geometria_wkt),activo=:active,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id and version=:version").params(values).update();}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.PADDOCK_CODE_ALREADY_EXISTS);}if(changed==0)throw new BusinessException(findById(p.id(),p.empresaId()).isPresent()?ErrorCode.VERSION_CONFLICT:ErrorCode.PADDOCK_NOT_FOUND);return findById(p.id(),p.empresaId()).orElseThrow();}
 public boolean propertyExists(UUID p,UUID e){return jdbc.sql("select exists(select 1 from propiedad where id=:p and activo)").param("p",p.toString()).query(Boolean.class).single();}
 public boolean sectorBelongs(UUID s,UUID p,UUID e){return jdbc.sql("select exists(select 1 from sector where id=:s and propiedad_id=:p and activo)").param("s",s.toString()).param("p",p.toString()).query(Boolean.class).single();}
 public boolean grassTypeExists(UUID g,UUID e){return jdbc.sql("select exists(select 1 from tipo_pasto where id=:g and activo)").param("g",g.toString()).query(Boolean.class).single();}
 public boolean hasActiveAnimals(UUID p,UUID e){return jdbc.sql("select exists(select 1 from animal where potrero_actual_id=:p and estado='ACTIVO')").param("p",p.toString()).query(Boolean.class).single();}
 public List<TipoPasto> findActive(UUID e){return jdbc.sql("select * from tipo_pasto where activo order by nombre").query(this::grass).list();}
 private Map<String,Object> params(Potrero p,UUID actor){Map<String,Object> m=new HashMap<>();m.put("id",p.id().toString());m.put("property",p.propiedadId()==null?null:p.propiedadId().toString());m.put("sector",p.sectorId()==null?null:p.sectorId().toString());m.put("code",p.codigo());m.put("name",p.nombre());m.put("area",p.superficieHa());m.put("grass",p.tipoPastoId()==null?null:p.tipoPastoId().toString());m.put("capacity",p.capacidadUa());m.put("water",p.tieneAgua());m.put("state",p.estado().name());m.put("geometry",p.geometriaWkt());m.put("active",p.activo());m.put("version",p.version());m.put("actor",actor.toString());return m;}
 private Potrero paddock(ResultSet r,int n)throws SQLException{return new Potrero(Rows.uuid(r,"id"),null,Rows.uuid(r,"propiedad_id"),Rows.uuid(r,"sector_id"),r.getString("codigo"),r.getString("nombre"),r.getBigDecimal("superficie_ha"),Rows.uuid(r,"tipo_pasto_id"),r.getBigDecimal("capacidad_ua"),r.getBoolean("tiene_agua"),EstadoPotrero.valueOf(r.getString("estado")),r.getString("geometria_wkt"),r.getBoolean("activo"),r.getLong("version"));}
 private TipoPasto grass(ResultSet r,int n)throws SQLException{return new TipoPasto(Rows.uuid(r,"id"),null,r.getString("codigo"),r.getString("nombre"),r.getString("nombre_cientifico"),r.getString("descripcion"),r.getBoolean("activo"));}
}
