package bo.com.ganadero.animales.infrastructure;
import bo.com.ganadero.animales.domain.*; import bo.com.ganadero.shared.error.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*; import java.time.LocalDate; import java.util.*;
@Repository class JdbcAnimalRepository implements AnimalRepository {
 private final JdbcClient jdbc;JdbcAnimalRepository(JdbcClient j){jdbc=j;}
 private static final String SELECT="select a.* from ganado.animales a";
 public AnimalPage findAll(UUID e,Set<UUID> allowed,AnimalFilter f){StringBuilder from=new StringBuilder(" from ganado.animales a join ganado.categorias_animal c on c.id=a.categoria_actual_id where a.empresa_id=:e");Map<String,Object> p=new HashMap<>();p.put("e",e);if(!allowed.isEmpty()){from.append(" and a.propiedad_actual_id in (:allowed)");p.put("allowed",allowed);}if(f.estado()!=null){from.append(" and a.estado=:estado");p.put("estado",f.estado().name());}if(f.propiedadId()!=null){from.append(" and a.propiedad_actual_id=:property");p.put("property",f.propiedadId());}if(f.potreroId()!=null){from.append(" and a.potrero_actual_id=:paddock");p.put("paddock",f.potreroId());}if(f.loteId()!=null){from.append(" and a.lote_actual_id=:lot");p.put("lot",f.loteId());}if(f.categoria()!=null&&!f.categoria().isBlank()){from.append(" and upper(c.codigo)=upper(:category)");p.put("category",f.categoria());}if(f.sexo()!=null){from.append(" and a.sexo=:sex");p.put("sex",f.sexo().name());}if(f.search()!=null&&!f.search().isBlank()){from.append(" and (lower(a.codigo) like :search or lower(coalesce(a.nombre,'')) like :search)");p.put("search","%"+f.search().toLowerCase(Locale.ROOT)+"%");}long total=jdbc.sql("select count(*)"+from).params(p).query(Long.class).single();p.put("limit",f.size());p.put("offset",f.page()*f.size());List<Animal> values=jdbc.sql("select a.*"+from+" order by a.codigo limit :limit offset :offset").params(p).query(this::map).list();return AnimalPage.of(values,f.page(),f.size(),total);}
 public Optional<Animal> findById(UUID id,UUID e){return jdbc.sql(SELECT+" where a.id=:id and a.empresa_id=:e").param("id",id).param("e",e).query(this::map).optional();}
  public List<AnimalEvent> findEvents(UUID animalId,UUID e){return jdbc.sql("select id,tipo,fecha_evento,estado_anterior,estado_nuevo,motivo,registrado_por,titulo,descripcion,modulo_origen,registro_origen,dispositivo,metadata,created_by from ganado.eventos_animal where animal_id=:animal and empresa_id=:e order by fecha_evento desc,created_at desc").param("animal",animalId).param("e",e).query(this::mapEvent).list();}
 public Animal create(Animal a,UUID actor){try{jdbc.sql("insert into ganado.animales(id,empresa_id,codigo,nombre,sexo,fecha_nacimiento,fecha_nacimiento_estimada,raza_principal_id,categoria_actual_id,color,proposito,origen,propiedad_actual_id,potrero_actual_id,lote_actual_id,estado,fecha_ingreso,precio_adquisicion,peso_nacimiento_kg,condicion_corporal_actual,foto_principal_path,observaciones,created_by,updated_by) values(:id,:e,:code,:name,:sex,:birth,:estimated,:breed,:category,:color,:purpose,:origin,:property,:paddock,:lot,:state,:entry,:price,:weight,:condition,:photo,:notes,:actor,:actor)").params(params(a,actor)).update();}catch(DataIntegrityViolationException ex){throw new BusinessException(ErrorCode.ANIMAL_CODE_ALREADY_EXISTS);}String type=switch(a.origen()){case NACIDO->"NACIMIENTO";case COMPRADO->"COMPRA";case TRANSFERIDO->"INGRESO";};insertEvent(a.id(),a.empresaId(),type,null,a.estado(),"Registro inicial",actor);return findById(a.id(),a.empresaId()).orElseThrow();}
 public Animal update(Animal a,UUID actor){int changed;try{changed=jdbc.sql("update ganado.animales set codigo=coalesce(:code,codigo),nombre=coalesce(:name,nombre),sexo=:sex,fecha_nacimiento=coalesce(:birth,fecha_nacimiento),fecha_nacimiento_estimada=:estimated,raza_principal_id=:breed,categoria_actual_id=:category,color=coalesce(:color,color),proposito=:purpose,propiedad_actual_id=:property,potrero_actual_id=:paddock,fecha_ingreso=coalesce(:entry,fecha_ingreso),precio_adquisicion=coalesce(:price,precio_adquisicion),peso_nacimiento_kg=coalesce(:weight,peso_nacimiento_kg),condicion_corporal_actual=coalesce(:condition,condicion_corporal_actual),foto_principal_path=coalesce(:photo,foto_principal_path),observaciones=coalesce(:notes,observaciones),updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e and version=:version").params(params(a,actor)).update();}catch(DataIntegrityViolationException ex){throw new BusinessException(ErrorCode.ANIMAL_CODE_ALREADY_EXISTS);}if(changed==0)throw missingOrConflict(findById(a.id(),a.empresaId()).isPresent());insertEvent(a.id(),a.empresaId(),"ACTUALIZACION",a.estado(),a.estado(),"Datos del animal actualizados",actor);return findById(a.id(),a.empresaId()).orElseThrow();}
 public Animal changeState(UUID id,UUID e,EstadoAnimal from,EstadoAnimal to,String reason,long version,UUID actor){int changed=jdbc.sql("update ganado.animales set estado=:state,updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e and version=:version and estado=:old").param("state",to.name()).param("actor",actor).param("id",id).param("e",e).param("version",version).param("old",from.name()).update();if(changed==0)throw missingOrConflict(findById(id,e).isPresent());insertEvent(id,e,"CAMBIO_ESTADO",from,to,reason,actor);return findById(id,e).orElseThrow();}
  public boolean validLocation(UUID e,UUID property,UUID paddock){return jdbc.sql("select exists(select 1 from campo.potreros p join core.propiedades pr on pr.id=p.propiedad_id where p.id=:paddock and p.propiedad_id=:property and p.empresa_id=:e and pr.empresa_id=:e and p.activo and pr.activo)").param("paddock",paddock).param("property",property).param("e",e).query(Boolean.class).single();}
  public void updateLote(UUID animalId,UUID empresa,UUID loteId,UUID actor){jdbc.sql("update ganado.animales set lote_actual_id=:lote,updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e").param("lote",loteId).param("actor",actor).param("id",animalId).param("e",empresa).update();}
  public void move(UUID animalId,UUID empresa,UUID propiedadId,UUID potreroId,UUID loteId,UUID actor){jdbc.sql("update ganado.animales set propiedad_actual_id=coalesce(:propiedad,propiedad_actual_id),potrero_actual_id=coalesce(:potrero,potrero_actual_id),lote_actual_id=coalesce(:lote,lote_actual_id),updated_at=now(),updated_by=:actor,version=version+1 where id=:id and empresa_id=:e").param("propiedad",propiedadId).param("potrero",potreroId).param("lote",loteId).param("actor",actor).param("id",animalId).param("e",empresa).update();}
  private void insertEvent(UUID animal,UUID e,String type,EstadoAnimal old,EstadoAnimal state,String reason,UUID actor){insertFullEvent(animal,e,type,old,state,reason,actor,type.replace('_',' ').toLowerCase(),reason,null,null,null);}
  private void insertFullEvent(UUID animal,UUID e,String type,EstadoAnimal old,EstadoAnimal state,String reason,UUID actor,String titulo,String descripcion,String modulo,UUID registro,String metadata){jdbc.sql("insert into ganado.eventos_animal(id,empresa_id,animal_id,tipo,estado_anterior,estado_nuevo,motivo,registrado_por,titulo,descripcion,modulo_origen,registro_origen,dispositivo,metadata,created_by) values(:id,:e,:animal,:type,:old,:state,:reason,:actor,:titulo,:descripcion,:modulo,:registro,null,coalesce(:metadata,'{}')::jsonb,:actor)").param("id",UUID.randomUUID()).param("e",e).param("animal",animal).param("type",type).param("old",old==null?null:old.name()).param("state",state.name()).param("reason",reason).param("actor",actor).param("titulo",titulo).param("descripcion",descripcion).param("modulo",modulo).param("registro",registro).param("metadata",metadata).update();}
 private Map<String,Object> params(Animal a,UUID actor){Map<String,Object> p=new HashMap<>();p.put("id",a.id());p.put("e",a.empresaId());p.put("code",a.codigo());p.put("name",a.nombre());p.put("sex",a.sexo().name());p.put("birth",a.fechaNacimiento());p.put("estimated",a.fechaNacimientoEstimada());p.put("breed",a.razaPrincipalId());p.put("category",a.categoriaActualId());p.put("color",a.color());p.put("purpose",a.proposito().name());p.put("origin",a.origen().name());p.put("property",a.propiedadActualId());p.put("paddock",a.potreroActualId());p.put("lot",a.loteActualId());p.put("state",a.estado().name());p.put("entry",a.fechaIngreso());p.put("price",a.precioAdquisicion());p.put("weight",a.pesoNacimientoKg());p.put("condition",a.condicionCorporalActual());p.put("photo",a.fotoPrincipalPath());p.put("notes",a.observaciones());p.put("version",a.version());p.put("actor",actor);return p;}
 private Animal map(ResultSet r,int n)throws SQLException{return new Animal(r.getObject("id",UUID.class),r.getObject("empresa_id",UUID.class),r.getString("codigo"),r.getString("nombre"),SexoAnimal.valueOf(r.getString("sexo")),r.getObject("fecha_nacimiento",LocalDate.class),r.getBoolean("fecha_nacimiento_estimada"),r.getObject("raza_principal_id",UUID.class),r.getObject("categoria_actual_id",UUID.class),r.getString("color"),PropositoAnimal.valueOf(r.getString("proposito")),OrigenAnimal.valueOf(r.getString("origen")),r.getObject("propiedad_actual_id",UUID.class),r.getObject("potrero_actual_id",UUID.class),r.getObject("lote_actual_id",UUID.class),EstadoAnimal.valueOf(r.getString("estado")),r.getObject("fecha_ingreso",LocalDate.class),r.getBigDecimal("precio_adquisicion"),r.getBigDecimal("peso_nacimiento_kg"),r.getBigDecimal("condicion_corporal_actual"),r.getString("foto_principal_path"),r.getString("observaciones"),r.getLong("version"));}
  private AnimalEvent mapEvent(ResultSet r,int n)throws SQLException{String previous=r.getString("estado_anterior");String next=r.getString("estado_nuevo");return new AnimalEvent(r.getObject("id",UUID.class),r.getString("tipo"),r.getTimestamp("fecha_evento").toInstant(),previous==null?null:EstadoAnimal.valueOf(previous),next==null?null:EstadoAnimal.valueOf(next),r.getString("motivo"),r.getObject("registrado_por",UUID.class),r.getString("titulo"),r.getString("descripcion"),r.getString("modulo_origen"),r.getObject("registro_origen",UUID.class),r.getString("dispositivo"),r.getString("metadata"),r.getObject("created_by",UUID.class));}
 private BusinessException missingOrConflict(boolean exists){return new BusinessException(exists?ErrorCode.VERSION_CONFLICT:ErrorCode.ANIMAL_NOT_FOUND);}
}
