package bo.com.ganadero.animales.infrastructure;
import bo.com.ganadero.animales.domain.*; import bo.com.ganadero.shared.error.*; import bo.com.ganadero.shared.db.Rows; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Repository;
import java.sql.*; import java.time.Instant; import java.time.LocalDate; import java.util.*;
@Repository class JdbcAnimalRepository implements AnimalRepository {
 private final JdbcClient jdbc;JdbcAnimalRepository(JdbcClient j){jdbc=j;}
 private static final String SELECT="select a.* from animal a";
 public AnimalPage findAll(UUID e,Set<UUID> allowed,AnimalFilter f){StringBuilder from=new StringBuilder(" from animal a join categoria_animal c on c.id=a.categoria_actual_id where 1=1");Map<String,Object> p=new HashMap<>();if(f.estado()!=null){from.append(" and a.estado=:estado");p.put("estado",f.estado().name());}if(f.potreroId()!=null){from.append(" and a.potrero_actual_id=:paddock");p.put("paddock",f.potreroId().toString());}if(f.loteId()!=null){from.append(" and a.lote_actual_id=:lot");p.put("lot",f.loteId().toString());}if(f.categoria()!=null&&!f.categoria().isBlank()){from.append(" and upper(c.codigo)=upper(:category)");p.put("category",f.categoria());}if(f.sexo()!=null){from.append(" and a.sexo=:sex");p.put("sex",f.sexo().name());}if(f.search()!=null&&!f.search().isBlank()){from.append(" and (lower(a.codigo) like :search or lower(coalesce(a.nombre,'')) like :search)");p.put("search","%"+f.search().toLowerCase(Locale.ROOT)+"%");}long total=jdbc.sql("select count(*)"+from).params(p).query(Long.class).single();p.put("limit",f.size());p.put("offset",f.page()*f.size());List<Animal> values=jdbc.sql("select a.*"+from+" order by a.codigo limit :limit offset :offset").params(p).query(this::map).list();return AnimalPage.of(values,f.page(),f.size(),total);}
 public Optional<Animal> findById(UUID id,UUID e){return jdbc.sql(SELECT+" where a.id=:id").param("id",id.toString()).query(this::map).optional();}
 public Optional<Animal> findByIdAnyCompany(UUID id){return jdbc.sql(SELECT+" where a.id=:id").param("id",id.toString()).query(this::map).optional();}
 public Optional<Animal> findByIdForUpdate(UUID id,UUID e){return jdbc.sql(SELECT+" where a.id=:id").param("id",id.toString()).query(this::map).optional();}
   public List<AnimalEvent> findEvents(UUID animalId,UUID e){return jdbc.sql("select id,tipo,fecha_evento,estado_anterior,estado_nuevo,motivo,usuario_id,titulo,descripcion,modulo_origen,registro_origen,dispositivo,metadata,created_by from evento_animal where animal_id=:animal order by fecha_evento desc,created_at desc").param("animal",animalId.toString()).query(this::mapEvent).list();}
   public AnimalEventPage findEventsPage(UUID animalId,UUID e,String tipo,Instant desde,Instant hasta,int page,int size){StringBuilder where=new StringBuilder(" where animal_id=:animal");Map<String,Object> p=new HashMap<>();p.put("animal",animalId.toString());if(tipo!=null&&!tipo.isBlank()){where.append(" and tipo=:tipo");p.put("tipo",tipo);}if(desde!=null){where.append(" and fecha_evento>=:desde");p.put("desde",desde.toString());}if(hasta!=null){where.append(" and fecha_evento<:hasta");p.put("hasta",hasta.toString());}long total=jdbc.sql("select count(*) from evento_animal"+where).params(p).query(Long.class).single();p.put("limit",size);p.put("offset",(long)page*size);List<AnimalEvent> values=jdbc.sql("select id,tipo,fecha_evento,estado_anterior,estado_nuevo,motivo,usuario_id,titulo,descripcion,modulo_origen,registro_origen,dispositivo,metadata,created_by from evento_animal"+where+" order by fecha_evento desc,created_at desc limit :limit offset :offset").params(p).query(this::mapEvent).list();return AnimalEventPage.of(values,page,size,total);}
  public Animal create(Animal a,UUID actor){try{jdbc.sql("insert into animal(id,codigo,nombre,sexo,fecha_nacimiento,fecha_nacimiento_estimada,raza_principal_id,categoria_actual_id,color,proposito,origen,potrero_actual_id,lote_actual_id,estado,fecha_ingreso,precio_adquisicion,peso_nacimiento_kg,condicion_corporal_actual,foto_principal_path,observaciones,created_by,updated_by) values(:id,:code,:name,:sex,:birth,:estimated,:breed,:category,:color,:purpose,:origin,:paddock,:lot,:state,:entry,:price,:weight,:condition,:photo,:notes,:actor,:actor)").params(params(a,actor)).update();}catch(DataIntegrityViolationException ex){throw new BusinessException(ErrorCode.ANIMAL_CODE_ALREADY_EXISTS);}return findById(a.id(),a.empresaId()).orElseThrow();}
  public Animal update(Animal a,UUID actor){int changed;try{changed=jdbc.sql("update animal set codigo=coalesce(:code,codigo),nombre=coalesce(:name,nombre),sexo=:sex,fecha_nacimiento=coalesce(:birth,fecha_nacimiento),fecha_nacimiento_estimada=:estimated,raza_principal_id=:breed,categoria_actual_id=:category,color=coalesce(:color,color),proposito=:purpose,potrero_actual_id=coalesce(:paddock,potrero_actual_id),fecha_ingreso=coalesce(:entry,fecha_ingreso),precio_adquisicion=coalesce(:price,precio_adquisicion),peso_nacimiento_kg=coalesce(:weight,peso_nacimiento_kg),condicion_corporal_actual=coalesce(:condition,condicion_corporal_actual),foto_principal_path=coalesce(:photo,foto_principal_path),observaciones=coalesce(:notes,observaciones),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id and version=:version").params(params(a,actor)).update();}catch(DataIntegrityViolationException ex){throw new BusinessException(ErrorCode.ANIMAL_CODE_ALREADY_EXISTS);}if(changed==0)throw missingOrConflict(findById(a.id(),a.empresaId()).isPresent());return findById(a.id(),a.empresaId()).orElseThrow();}
  public Animal changeState(UUID id,UUID e,EstadoAnimal from,EstadoAnimal to,String reason,long version,UUID actor){int changed=jdbc.sql("update animal set estado=:state,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id and version=:version and estado=:old").param("state",to.name()).param("actor",actor.toString()).param("id",id.toString()).param("version",version).param("old",from.name()).update();if(changed==0)throw missingOrConflict(findById(id,e).isPresent());return findById(id,e).orElseThrow();}
  public boolean validLocation(UUID e,UUID property,UUID paddock){return jdbc.sql("select exists(select 1 from potrero p where p.id=:paddock and p.activo=1)").param("paddock",paddock.toString()).query(Boolean.class).single();}
   public void updateLote(UUID animalId,UUID empresa,UUID loteId,UUID actor){jdbc.sql("update animal set lote_actual_id=:lote,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id").param("lote",loteId==null?null:loteId.toString()).param("actor",actor.toString()).param("id",animalId.toString()).update();}
   public void updateFotoPrincipal(UUID animalId,UUID empresa,String path,UUID actor){jdbc.sql("update animal set foto_principal_path=:path,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id").param("path",path).param("actor",actor.toString()).param("id",animalId.toString()).update();}
   public void move(UUID animalId,UUID empresa,UUID propiedadId,UUID potreroId,UUID loteId,UUID actor){jdbc.sql("update animal set potrero_actual_id=:potrero,lote_actual_id=:lote,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_by=:actor,version=version+1 where id=:id").param("potrero",potreroId==null?null:potreroId.toString()).param("lote",loteId==null?null:loteId.toString()).param("actor",actor.toString()).param("id",animalId.toString()).update();}
   public void restoreLocation(UUID animalId,UUID empresa,UUID propiedadId,UUID potreroId,UUID loteId,UUID actor){move(animalId,empresa,propiedadId,potreroId,loteId,actor);}
   public List<Animal> findEligible(UUID e,UUID propiedad,UUID lote,UUID categoria,SexoAnimal sexo){StringBuilder q=new StringBuilder(SELECT+" where a.estado='ACTIVO'");Map<String,Object>x=new HashMap<>();if(lote!=null){q.append(" and a.lote_actual_id=:l");x.put("l",lote.toString());}if(categoria!=null){q.append(" and a.categoria_actual_id=:c");x.put("c",categoria.toString());}if(sexo!=null){q.append(" and a.sexo=:s");x.put("s",sexo.name());}return jdbc.sql(q+" order by a.codigo").params(x).query(this::map).list();}
  private Map<String,Object> params(Animal a,UUID actor){Map<String,Object> p=new HashMap<>();p.put("id",a.id().toString());p.put("code",a.codigo());p.put("name",a.nombre());p.put("sex",a.sexo().name());p.put("birth",a.fechaNacimiento()==null?null:a.fechaNacimiento().toString());p.put("estimated",a.fechaNacimientoEstimada());p.put("breed",a.razaPrincipalId()==null?null:a.razaPrincipalId().toString());p.put("category",a.categoriaActualId()==null?null:a.categoriaActualId().toString());p.put("color",a.color());p.put("purpose",a.proposito().name());p.put("origin",a.origen().name());p.put("paddock",a.potreroActualId()==null?null:a.potreroActualId().toString());p.put("lot",a.loteActualId()==null?null:a.loteActualId().toString());p.put("state",a.estado().name());p.put("entry",a.fechaIngreso()==null?null:a.fechaIngreso().toString());p.put("price",a.precioAdquisicion());p.put("weight",a.pesoNacimientoKg());p.put("condition",a.condicionCorporalActual());p.put("photo",a.fotoPrincipalPath());p.put("notes",a.observaciones());p.put("version",a.version());p.put("actor",actor.toString());return p;}
 private Animal map(ResultSet r,int n)throws SQLException{return new Animal(Rows.uuid(r,"id"),null,r.getString("codigo"),r.getString("nombre"),SexoAnimal.valueOf(r.getString("sexo")),r.getString("fecha_nacimiento")==null?null:LocalDate.parse(r.getString("fecha_nacimiento")),r.getBoolean("fecha_nacimiento_estimada"),Rows.uuid(r,"raza_principal_id"),Rows.uuid(r,"categoria_actual_id"),r.getString("color"),PropositoAnimal.valueOf(r.getString("proposito")),OrigenAnimal.valueOf(r.getString("origen")),null,Rows.uuid(r,"potrero_actual_id"),Rows.uuid(r,"lote_actual_id"),EstadoAnimal.valueOf(r.getString("estado")),r.getString("fecha_ingreso")==null?null:LocalDate.parse(r.getString("fecha_ingreso")),r.getBigDecimal("precio_adquisicion"),r.getBigDecimal("peso_nacimiento_kg"),r.getBigDecimal("condicion_corporal_actual"),r.getString("foto_principal_path"),r.getString("observaciones"),r.getLong("version"));}
  private AnimalEvent mapEvent(ResultSet r,int n)throws SQLException{String previous=r.getString("estado_anterior");String next=r.getString("estado_nuevo");return new AnimalEvent(Rows.uuid(r,"id"),r.getString("tipo"),Rows.instant(r,"fecha_evento"),previous==null?null:EstadoAnimal.valueOf(previous),next==null?null:EstadoAnimal.valueOf(next),r.getString("motivo"),Rows.uuid(r,"usuario_id"),r.getString("titulo"),r.getString("descripcion"),r.getString("modulo_origen"),Rows.uuid(r,"registro_origen"),r.getString("dispositivo"),r.getString("metadata"),Rows.uuid(r,"created_by"));}
 private BusinessException missingOrConflict(boolean exists){return new BusinessException(exists?ErrorCode.VERSION_CONFLICT:ErrorCode.ANIMAL_NOT_FOUND);}
}
