import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router'
import { supabase } from '@/auth/supabase'
import { Alert } from '@/shared/components/Alert'
import { Button } from '@/shared/components/Button'
import { Field } from '@/shared/components/Field'
export function PasswordActionPage({ invitation=false }:{invitation?:boolean}){const navigate=useNavigate();const[ready,setReady]=useState(false);const[invalid,setInvalid]=useState(!supabase);const[password,setPassword]=useState('');const[confirmation,setConfirmation]=useState('');const[loading,setLoading]=useState(false);const[message,setMessage]=useState<string|null>(null)
 useEffect(()=>{if(supabase)void supabase.auth.getSession().then(({data})=>{setReady(Boolean(data.session));setInvalid(!data.session)})},[])
 async function submit(event:FormEvent){event.preventDefault();setMessage(null);if(password.length<10){setMessage('La contraseña debe tener al menos 10 caracteres.');return}if(password!==confirmation){setMessage('Las contraseñas no coinciden.');return}if(!supabase||!ready){setInvalid(true);return}setLoading(true);const{error}=await supabase.auth.updateUser({password});if(error){setMessage('No se pudo actualizar la contraseña. El enlace puede haber vencido.');setLoading(false);return}await supabase.auth.signOut();setMessage('Contraseña actualizada correctamente.');window.setTimeout(()=>navigate('/login',{replace:true}),1200)}
 return <main className="simple-auth-page"><form className="auth-card" onSubmit={submit}><h1>{invitation?'Aceptar invitación':'Nueva contraseña'}</h1><p className="muted">{invitation?'Define tu contraseña para activar el acceso.':'Define una contraseña nueva para tu cuenta.'}</p>{invalid&&<Alert tone="danger">El enlace es inválido, venció o ya fue utilizado.</Alert>}{message&&<Alert tone={message.includes('correctamente')?'success':'danger'}>{message}</Alert>}<Field label="Nueva contraseña"><input type="password" autoComplete="new-password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></Field><Field label="Confirmar contraseña"><input type="password" autoComplete="new-password" minLength={10} required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></Field><Button type="submit" fullWidth loading={loading} disabled={!ready}>Guardar contraseña</Button><Link className="text-link centered" to="/login">Volver al login</Link></form></main>}
