package bo.com.ganadero.animales.api; import bo.com.ganadero.animales.application.AnimalService; import bo.com.ganadero.animales.domain.*; import bo.com.ganadero.shared.api.ApiResponse; import bo.com.ganadero.shared.web.CorrelationIdFilter;
import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.validation.annotation.Validated; import org.springframework.web.bind.annotation.*; import java.util.*;
@Validated @RestController @RequestMapping("/api/v1") public class AnimalController {private final AnimalService service;public AnimalController(AnimalService s){service=s;}
 @GetMapping("/animales") ApiResponse<AnimalPageResponse> list(@RequestParam(required=false) EstadoAnimal estado,@RequestParam(required=false) UUID propiedadId,@RequestParam(required=false) UUID potreroId,@RequestParam(required=false) UUID loteId,@RequestParam(required=false) String categoria,@RequestParam(required=false) SexoAnimal sexo,@RequestParam(required=false) String search,@RequestParam(defaultValue="0") @Min(0) int page,@RequestParam(defaultValue="20") @Min(1) @Max(500) int size,HttpServletRequest r){return ok(AnimalPageResponse.from(service.list(new AnimalFilter(estado,propiedadId,potreroId,loteId,categoria,sexo,search,page,size))),r);}
 @PostMapping("/animales") ApiResponse<AnimalResponse> create(@Valid @RequestBody CrearAnimalRequest b,HttpServletRequest r){return ok(AnimalResponse.from(service.create(b.command())),r);}
 @GetMapping("/animales/{id}") ApiResponse<AnimalResponse> get(@PathVariable UUID id,HttpServletRequest r){return ok(AnimalResponse.from(service.get(id)),r);}
 @GetMapping("/animales/{id}/historial") ApiResponse<List<AnimalEventResponse>> history(@PathVariable UUID id,HttpServletRequest r){return ok(service.history(id).stream().map(AnimalEventResponse::from).toList(),r);}
 @GetMapping("/animales/{id}/timeline") ApiResponse<List<AnimalEventResponse>> timeline(@PathVariable UUID id,HttpServletRequest r){return ok(service.history(id).stream().map(AnimalEventResponse::from).toList(),r);}
 @PatchMapping("/animales/{id}") ApiResponse<AnimalResponse> update(@PathVariable UUID id,@Valid @RequestBody ActualizarAnimalRequest b,HttpServletRequest r){return ok(AnimalResponse.from(service.update(id,b.command())),r);}
 @PatchMapping("/animales/{id}/estado") ApiResponse<AnimalResponse> state(@PathVariable UUID id,@Valid @RequestBody CambiarEstadoAnimalRequest b,HttpServletRequest r){return ok(AnimalResponse.from(service.changeState(id,b.estado(),b.motivo(),b.version())),r);}
 @GetMapping("/razas") ApiResponse<List<RazaResponse>> breeds(HttpServletRequest r){return ok(service.breeds().stream().map(RazaResponse::from).toList(),r);}
 @GetMapping("/categorias-animal") ApiResponse<List<CategoriaAnimalResponse>> categories(HttpServletRequest r){return ok(service.categories().stream().map(CategoriaAnimalResponse::from).toList(),r);}
 private <T> ApiResponse<T> ok(T d,HttpServletRequest r){Object c=r.getAttribute(CorrelationIdFilter.ATTRIBUTE);return ApiResponse.success(d,c==null?"unknown":c.toString());}}
