package bo.com.ganadero.animales.api; import bo.com.ganadero.animales.application.AnimalCommand; import bo.com.ganadero.animales.application.EstimacionEdadAnimal; import bo.com.ganadero.animales.domain.*; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.UUID;
public record CrearAnimalRequest(@Size(max=60) String codigo,@Size(max=160) String nombre,@NotNull SexoAnimal sexo,
 LocalDate fechaNacimiento,Boolean fechaNacimientoEstimada,@NotNull UUID razaPrincipalId,UUID categoriaActualId,
 String color,@NotNull PropositoAnimal proposito,@NotNull OrigenAnimal origen,@NotNull UUID propiedadActualId,
 @NotNull UUID potreroActualId,LocalDate fechaIngreso,@PositiveOrZero BigDecimal precioAdquisicion,
 @PositiveOrZero BigDecimal pesoNacimientoKg,@DecimalMin("1.0") @DecimalMax("5.0") BigDecimal condicionCorporalActual,
  String fotoPrincipalPath,String observaciones,@Positive BigDecimal pesoIngresoKg,Boolean pesoIngresoEstimado,
  @Positive Integer edadDeclaradaValor,UnidadEdadDeclarada edadDeclaradaUnidad,LocalDate fechaReferenciaEdad,
  FuenteEdadDeclarada fuenteEdad,String observacionEstimacion,String categoriaManualMotivo){AnimalCommand command(){var edad=EstimacionEdadAnimal.resolver(fechaNacimiento,fechaNacimientoEstimada,edadDeclaradaValor,edadDeclaradaUnidad,fechaReferenciaEdad,fuenteEdad,observacionEstimacion);return new AnimalCommand(null,codigo,nombre,sexo,edad.fechaNacimiento(),edad.estimada(),razaPrincipalId,categoriaActualId,color,proposito,origen,propiedadActualId,potreroActualId,null,fechaIngreso,precioAdquisicion,pesoNacimientoKg,condicionCorporalActual,fotoPrincipalPath,observaciones,0L,pesoIngresoKg,pesoIngresoEstimado,false,false,edad.valorDeclarado(),edad.unidad(),edad.fechaReferencia(),edad.fuente(),edad.detalle(),categoriaManualMotivo,false,null);}}
